In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r'techcorp_workforce.csv',index_col='id')
df.head()

   first_name  last_name department  salary phone_number joining_date
id
1       Sarah   Mitchell         HR   95000     555-0101   15-03-2021
2     Michael       Chen         HR   88000     555-0102   01-06-2022
3       Emily  Rodriguez         HR   82500          NaN   20-09-2021
4       David       Park         HR   80000     555-0104   10-01-2023
5        Lisa   Thompson         HR   65000          NaN   05-04-2021

# Selecting Columns 
## As DF 
`df[['column_name']]`

In [4]:
type(df[['department']])

pandas.DataFrame

## As Series
`df['column_name']`

In [5]:
type(df['department'])

pandas.Series

## Multiple columns 
`df[['column_name1','column_name2','column_name3']]`

In [6]:
type(df[['department','salary']])

pandas.DataFrame

# Knowing Data
## How many rows and columns 
`df.shape`

In [7]:
df.shape

(51, 6)

## what are the columns 
`df.columns`

In [8]:
df.columns

Index(['first_name', 'last_name', 'department', 'salary', 'phone_number',
       'joining_date'],
      dtype='str')

## datatype of each column 
`df.dtypes`

In [9]:
df.dtypes

first_name        str
last_name         str
department        str
salary          int64
phone_number      str
joining_date      str
dtype: object

## full summary: columns, types, non-null counts
`df.info()`

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51 entries, 1 to 51
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   first_name    51 non-null     str
 1   last_name     51 non-null     str
 2   department    51 non-null     str
 3   salary        51 non-null     int64
 4   phone_number  35 non-null     str
 5   joining_date  51 non-null     str
dtypes: int64(1), str(5)
memory usage: 2.5 KB

# Statistical summary 
## numerical datatype
`df.describe()`

In [11]:
df.describe()

              salary
count      51.000000
mean    80784.313725
std     17561.963131
min     48000.000000
25%     68500.000000
50%     81000.000000
75%     91000.000000
max    130000.000000

## all datatype 
`df.describe(include='all')`

In [12]:
df.describe(include='all')

,first_name,last_name,department,salary,phone_number,joining_date
count,51,51,51,51.000000,35,51
unique,51,50,6,NaN,35,51
top,Sarah,Mitchell,HR,NaN,555-0101,15-03-2021
freq,1,2,10,NaN,1,1
mean,NaN,NaN,NaN,80784.313725,NaN,NaN
std,NaN,NaN,NaN,17561.963131,NaN,NaN
min,NaN,NaN,NaN,48000.000000,NaN,NaN
25%,NaN,NaN,NaN,68500.000000,NaN,NaN
50%,NaN,NaN,NaN,81000.000000,NaN,NaN
75%,NaN,NaN,NaN,91000.000000,NaN,NaN
max,NaN,NaN,NaN,130000.000000,NaN,NaN

# Renaming 
## Instance column rename
`df.rename(columns={"actual name" : "new name"})`

Note:- this doesn't update the dataframe but only the instance. To save the updated instance, we can refer that to a variable.

In [147]:
renamed_df = df.rename(columns={
    "first_name" : "First Name",
    "last_name" : "Last Name",
    "phone_number" : "phone number".title(),
    "joining_date" : "joining date".title()
})
renamed_df.head()

   First Name  Last Name department  salary Phone Number Joining Date
id
1       Sarah   Mitchell         HR   95000     555-0101   15-03-2021
2     Michael       Chen         HR   88000     555-0102   01-06-2022
3       Emily  Rodriguez         HR   82500          NaN   20-09-2021
4       David       Park         HR   80000     555-0104   10-01-2023
5        Lisa   Thompson         HR   65000          NaN   05-04-2021

In [148]:
df.rename(columns={
    "first_name" : "First Name",
    "last_name" : "Last Name",
    "phone_number" : "phone number".title(),
    "joining_date" : "joining date".title()
}).head()

   First Name  Last Name department  salary Phone Number Joining Date
id
1       Sarah   Mitchell         HR   95000     555-0101   15-03-2021
2     Michael       Chen         HR   88000     555-0102   01-06-2022
3       Emily  Rodriguez         HR   82500          NaN   20-09-2021
4       David       Park         HR   80000     555-0104   10-01-2023
5        Lisa   Thompson         HR   65000          NaN   05-04-2021

In [149]:
df.head()

   first_name  last_name department  salary phone_number joining_date
id
1       Sarah   Mitchell         HR   95000     555-0101   15-03-2021
2     Michael       Chen         HR   88000     555-0102   01-06-2022
3       Emily  Rodriguez         HR   82500          NaN   20-09-2021
4       David       Park         HR   80000     555-0104   10-01-2023
5        Lisa   Thompson         HR   65000          NaN   05-04-2021

## Permanent column rename
`df.rename(columns={"actual name" : "new name"},inplace=True)`

Note:- this update the dataframe and store in the same.

In [150]:
df2 = df.copy(deep=True)
df2.head()

   first_name  last_name department  salary phone_number joining_date
id
1       Sarah   Mitchell         HR   95000     555-0101   15-03-2021
2     Michael       Chen         HR   88000     555-0102   01-06-2022
3       Emily  Rodriguez         HR   82500          NaN   20-09-2021
4       David       Park         HR   80000     555-0104   10-01-2023
5        Lisa   Thompson         HR   65000          NaN   05-04-2021

In [151]:
df2.rename(columns={
    "first_name" : "First Name",
    "last_name" : "Last Name",
    "phone_number" : "phone number".title(),
    "joining_date" : "joining date".title()
},inplace=True)
df2.head()

   First Name  Last Name department  salary Phone Number Joining Date
id
1       Sarah   Mitchell         HR   95000     555-0101   15-03-2021
2     Michael       Chen         HR   88000     555-0102   01-06-2022
3       Emily  Rodriguez         HR   82500          NaN   20-09-2021
4       David       Park         HR   80000     555-0104   10-01-2023
5        Lisa   Thompson         HR   65000          NaN   05-04-2021

# Creating New Columns
## Simple column
New column can be created using the new name for a column that is not present already in the dataframe.
`df['new_column_name'] = df['existing_column_name']`

In [33]:
df2['new_salary']= df2['salary']
df2.head()

,First Name,Last Name,department,salary,Phone Number,Joining Date,new_salary
id,,,,,,,
1,Sarah,Mitchell,HR,95000,555-0101,15-03-2021,95000
2,Michael,Chen,HR,88000,555-0102,01-06-2022,88000
3,Emily,Rodriguez,HR,82500,NaN,20-09-2021,82500
4,David,Park,HR,80000,555-0104,10-01-2023,80000
5,Lisa,Thompson,HR,65000,NaN,05-04-2021,65000

## Calculated column
any arithmetic or logical operation can  also be performed columnwise

In [35]:
df2['new_salary_monthly']= df2['salary']/12.0
df2.head()

,First Name,Last Name,department,salary,Phone Number,Joining Date,new_salary,new_salary_monthly
id,,,,,,,,
1,Sarah,Mitchell,HR,95000,555-0101,15-03-2021,95000,7916.666667
2,Michael,Chen,HR,88000,555-0102,01-06-2022,88000,7333.333333
3,Emily,Rodriguez,HR,82500,NaN,20-09-2021,82500,6875.000000
4,David,Park,HR,80000,555-0104,10-01-2023,80000,6666.666667
5,Lisa,Thompson,HR,65000,NaN,05-04-2021,65000,5416.666667

# Copy
## Refer the og
when we want to refer the original dataframe with another name 
`df1 = df`

Note:- Any change in df1 affects df too

In [ ]:
og_df = pd.read_csv(r'techcorp_workforce.csv')
og_df.head()

   id first_name  last_name department  salary phone_number joining_date
0   1      Sarah   Mitchell         HR   95000     555-0101   15-03-2021
1   2    Michael       Chen         HR   88000     555-0102   01-06-2022
2   3      Emily  Rodriguez         HR   82500          NaN   20-09-2021
3   4      David       Park         HR   80000     555-0104   10-01-2023
4   5       Lisa   Thompson         HR   65000          NaN   05-04-2021

In [ ]:
copy_df = og_df
copy_df.head()

   id first_name  last_name department  salary phone_number joining_date
0   1      Sarah   Mitchell         HR   95000     555-0101   15-03-2021
1   2    Michael       Chen         HR   88000     555-0102   01-06-2022
2   3      Emily  Rodriguez         HR   82500          NaN   20-09-2021
3   4      David       Park         HR   80000     555-0104   10-01-2023
4   5       Lisa   Thompson         HR   65000          NaN   05-04-2021

In [ ]:
copy_df.rename(columns={
    "first_name":"first name".title()
},
inplace=True)
copy_df.head()

   id First Name  last_name department  salary phone_number joining_date
0   1      Sarah   Mitchell         HR   95000     555-0101   15-03-2021
1   2    Michael       Chen         HR   88000     555-0102   01-06-2022
2   3      Emily  Rodriguez         HR   82500          NaN   20-09-2021
3   4      David       Park         HR   80000     555-0104   10-01-2023
4   5       Lisa   Thompson         HR   65000          NaN   05-04-2021

In [ ]:
og_df.head()

   id First Name  last_name department  salary phone_number joining_date
0   1      Sarah   Mitchell         HR   95000     555-0101   15-03-2021
1   2    Michael       Chen         HR   88000     555-0102   01-06-2022
2   3      Emily  Rodriguez         HR   82500          NaN   20-09-2021
3   4      David       Park         HR   80000     555-0104   10-01-2023
4   5       Lisa   Thompson         HR   65000          NaN   05-04-2021

## Shallow copy 
Modifying the structure (adding/deleting columns or changing cell values via .loc) in df2 will not affect df.    
But by default in standard Python, a shallow copy can sometimes still mutate nested Python objects (like lists or dicts stored inside cells) in the original DataFrame.    
This is the standard way to safely duplicate a DataFrame for normal data analysis steps without worrying about the SettingWithCopyWarning

`df2 = df.copy()`

In [156]:
og_df = pd.read_csv(r'techcorp_workforce.csv')
og_df.head()

   id first_name  last_name department  salary phone_number joining_date
0   1      Sarah   Mitchell         HR   95000     555-0101   15-03-2021
1   2    Michael       Chen         HR   88000     555-0102   01-06-2022
2   3      Emily  Rodriguez         HR   82500          NaN   20-09-2021
3   4      David       Park         HR   80000     555-0104   10-01-2023
4   5       Lisa   Thompson         HR   65000          NaN   05-04-2021

In [157]:
copy_df2 = og_df.copy()
copy_df.head()

   id First Name  last_name department  salary phone_number joining_date
0   1      Sarah   Mitchell         HR   95000     555-0101   15-03-2021
1   2    Michael       Chen         HR   88000     555-0102   01-06-2022
2   3      Emily  Rodriguez         HR   82500          NaN   20-09-2021
3   4      David       Park         HR   80000     555-0104   10-01-2023
4   5       Lisa   Thompson         HR   65000          NaN   05-04-2021

In [158]:
copy_df.rename(columns={
    "first_name":"first name".title()
},
inplace=True)
copy_df.head()

   id First Name  last_name department  salary phone_number joining_date
0   1      Sarah   Mitchell         HR   95000     555-0101   15-03-2021
1   2    Michael       Chen         HR   88000     555-0102   01-06-2022
2   3      Emily  Rodriguez         HR   82500          NaN   20-09-2021
3   4      David       Park         HR   80000     555-0104   10-01-2023
4   5       Lisa   Thompson         HR   65000          NaN   05-04-2021

In [159]:
og_df.head()

   id first_name  last_name department  salary phone_number joining_date
0   1      Sarah   Mitchell         HR   95000     555-0101   15-03-2021
1   2    Michael       Chen         HR   88000     555-0102   01-06-2022
2   3      Emily  Rodriguez         HR   82500          NaN   20-09-2021
3   4      David       Park         HR   80000     555-0104   10-01-2023
4   5       Lisa   Thompson         HR   65000          NaN   05-04-2021

## Deep copy 
Completely isolation between both the dataframes

`df3 = df.copy(deep=True)`

in pandas by default `deep=True`

# Dupliactes
## Remove Duplicates    
Removes the rows with the duplicate values for the given column

`df[['column_name']].drop_duplicates()` 

This works on a dataframe and return a dataframe

In [165]:
orders_df = pd.read_csv(r'orders.csv')
orders_df.head()

   id  cust_id  order_date order_details  total_order_cost
0   1        3  04-03-2019          Coat               100
1   2        3  01-03-2019         Shoes                80
2   3        3  07-03-2019         Skirt                30
3   4        7  01-02-2019          Coat                25
4   5        7  10-03-2019         Shoes                80

In [176]:
odf1= orders_df.copy(deep=True)
unique_details_df = odf1[["order_details"]].drop_duplicates()
type(unique_details_df)

pandas.DataFrame

## Multiple column names 
When multiple columns passed, it removes rows where the entire combination is duplicated:

In [178]:
odf1[['order_details','cust_id']].drop_duplicates().head()

  order_details  cust_id
0          Coat        3
1         Shoes        3
2         Skirt        3
3          Coat        7
4         Shoes        7

## Single column
When a single column needs to be worked on we can use 

`df['column_name'].unique()`

this returns a series of unique values.

In [179]:
odf1['order_details'].unique()

<StringArray>
[   'Coat',   'Shoes',   'Skirt',   'Boats',  'Shirts', 'Slipper',   'Jeans',
    'Suit', 'Dresses',  'Gloves',     'Tie',     'Cap',  'Jacket']
Length: 13, dtype: str