# Section 1 :- Intro into pandas

In [1]:
import pandas as pd
import numpy as np
pd.__version__
np.__version__

'2.4.6'

## 1.1. Simple Pandas settings

There are certain configurations that can be set before commencing a project 

To set these configurations we can use 

`pd.set_options('configuration' , value)`

| Configuration | Values it can take (default inside) | Purpose | Effect on Output (Detailed) | When to use each value |
|---------------|-------------------------------------|---------|------------------------------|------------------------|
| display.max_rows | int, None (**default: 60**) | Controls how many rows pandas prints before truncating | If rows > limit → pandas shows top + bottom rows with "..." in between. If None → entire dataset prints (can flood output). | Small int → large datasets <br> None → small datasets only |
| display.min_rows | int (**default: 10**) | Ensures a minimum number of rows are shown even when truncated | Output will always include at least this many combined head + tail rows, giving context from both ends instead of only a few top rows | Use when max_rows is small but context is needed |
| display.max_columns | int, None (**default: 20**) | Limits number of columns visible | If columns exceed limit → some columns are hidden and replaced with "..." in the middle. None → all columns rendered | Small int → wide datasets <br> None → narrow datasets |
| display.width | int, None (**default: 80**) | Controls total horizontal width of output | If content exceeds width → wrapping or truncation occurs. Larger width → more columns fit in a single row view | Increase for wide screens <br> None → auto-detect |
| display.expand_frame_repr | True / False (**default: True**) | Controls whether wide DataFrames wrap | True → DataFrame splits into multiple lines (vertical stacking of columns) <br> False → keeps everything in one horizontal row (may overflow) | True → readability <br> False → compact view |
| display.max_colwidth | int, None (**default: 50**) | Limits visible text per column cell | Long text gets truncated with "..." if it exceeds limit. None → full text shown (can stretch layout heavily) | Small → text-heavy data <br> None → inspection of full text |
| display.precision | int (**default: 6**) | Controls decimal precision of floats | Floating values are rounded visually (not in memory). Fewer decimals → cleaner output; more → detailed numbers | Lower → reports <br> Higher → calculations |
| display.float_format | function, None (**default: None**) | Applies consistent float formatting | Overrides default float display (e.g., removes scientific notation, fixes decimal places across all columns) | Use `{:.2f}` for readability |
| display.large_repr | 'truncate', 'info' (**default: 'truncate'**) | Behavior for very large DataFrames | 'truncate' → partial data preview <br> 'info' → replaces table output entirely with `.info()` summary |
| display.memory_usage | True / False, None (**default: True**) | Shows memory usage in `.info()` | Adds memory consumption stats at bottom of `.info()` output, helping identify heavy columns | True → optimization <br> False → cleaner logs |
| display.encoding | str (**default: 'utf-8'**) | Encoding used for string display | Ensures correct rendering of special characters; wrong encoding → garbled or broken text | Keep utf-8 |
| display.multi_sparse | True / False (**default: True**) | Controls MultiIndex repetition display | True → repeated index values hidden (compact view) <br> False → all levels repeated row-wise for clarity |
| display.html.table_schema | True / False (**default: False**) | Adds schema metadata to HTML output | When enabled, notebook output includes additional structure (useful for integrations like dashboards/tools) |
| display.notebook_repr_html | True / False (**default: True**) | Controls notebook rendering style | True → formatted HTML table (grid-like) <br> False → plain text output (like terminal) |
| mode.chained_assignment | 'warn', 'raise', None (**default: 'warn'**) | Controls handling of chained assignment ambiguity | 'warn' → shows warning <br> 'raise' → throws error <br> None → silent (risk of unnoticed bugs) |
| display.max_info_rows | int (**default: 1690785**) | Threshold for `.info()` detail level | If row count exceeds this → `.info()` skips per-column null counts for speed |
| display.max_info_columns | int (**default: 100**) | Threshold for `.info()` column detail | If too many columns → `.info()` summarizes instead of listing all columns fully |

In [2]:
pd.set_option("display.max_rows",400)

Once we set thes values we can check the avlue for this configuration using

`pd.describe_option()`

| Function | Purpose | When to use |
|----------|--------|-------------|
| pd.describe_option() | Shows all pandas config options | When exploring available settings |
| pd.describe_option('display') | Shows only display-related options | When focusing on UI/printing configs |
| pd.describe_option('max_rows') | Shows details of a specific option | When unsure about a configuration |

In [3]:
pd.describe_option("display")

display.chop_threshold : float or None
    if set to a float value, all float values smaller than the given threshold
    will be displayed as exactly 0 by repr and friends.
    [default: None] [currently: None]
display.colheader_justify : 'left'/'right'
    Controls the justification of column headers. used by DataFrameFormatter.
    [default: right] [currently: right]
display.date_dayfirst : boolean
    When True, prints and parses dates with the day first, eg 20/01/2005
    [default: False] [currently: False]
display.date_yearfirst : boolean
    When True, prints and parses dates with the year first, eg 2005/01/20
    [default: False] [currently: False]
display.encoding : str/unicode
    Defaults to the detected encoding of the console.
    Specifies the encoding to be used for strings returned by to_string,
    these are generally strings meant to be displayed on the console.
    [default: UTF-8] [currently: UTF-8]
display.expand_frame_repr : boolean
    Whether to print out the full DataFrame repr for wide DataFrames across
    multiple lines, `max_columns` is still respected, but the output will
    wrap-around across multiple "pages" if its width exceeds `display.width`.
    [default: True] [currently: True]
display.float_format : callable
    The callable should accept a floating point number and return
    a string with the desired format of the number. This is used
    in some places like SeriesFormatter.
    See formats.format.EngFormatter for an example.
    [default: None] [currently: None]
display.html.border : int
    A ``border=value`` attribute is inserted in the ``<table>`` tag
    for the DataFrame HTML repr.
    [default: 1] [currently: 1]
display.html.table_schema : boolean
    Whether to publish a Table Schema representation for frontends
    that support it.
    (default: False)
    [default: False] [currently: False]
display.html.use_mathjax : boolean
    When True, Jupyter notebook will process table contents using MathJax,
    rendering mathematical expressions enclosed by the dollar symbol.
    (default: True)
    [default: True] [currently: True]
display.large_repr : 'truncate'/'info'
    For DataFrames exceeding max_rows/max_cols, the repr (and HTML repr) can
    show a truncated table, or switch to the view from
    df.info() (the behaviour in earlier versions of pandas).
    [default: truncate] [currently: truncate]
display.max_categories : int
    This sets the maximum number of categories pandas should output when
    printing out a `Categorical` or a Series of dtype "category".
    [default: 8] [currently: 8]
display.max_columns : int
    If max_cols is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view.

    'None' value means unlimited. Beware that printing a large number of
    columns could cause your rendering environment (the browser, etc.) to
    crash.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 or None and pandas will auto-detect
    the width of the terminal and print a truncated object which fits
    the screen width. The IPython notebook, IPython qtconsole, or IDLE
    do not run in a terminal and hence it is not possible to do
    correct auto-detection and defaults to 20.
    [default: 20] [currently: 20]
display.max_colwidth : int or None
    The maximum width in characters of a column in the repr of
    a pandas data structure. When the column overflows, a "..."
    placeholder is embedded in the output. A 'None' value means unlimited.
    [default: 50] [currently: 50]
display.max_dir_items : int
    The number of items that will be added to `dir(...)`. 'None' value means
    unlimited. Because dir is cached, changing this option will not immediately
    affect already existing dataframes until a column is deleted or added.

    This is for instance used to suggest columns from a dataframe to tab
    completion.
    [default: 100] [currently: 100]
display.max_info_columns : int
    max_info_columns is used in DataFrame.info method to decide if
    per column information will be printed.
    [default: 100] [currently: 100]
display.max_info_rows : int
    df.info() will usually show null-counts for each column.
    For large frames this can be quite slow. max_info_rows and max_info_cols
    limit this null check only to frames with smaller dimensions than
    specified.
    [default: 1690785] [currently: 1690785]
display.max_rows : int
    If max_rows is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view.

    'None' value means unlimited. Beware that printing a large number of rows
    could cause your rendering environment (the browser, etc.) to crash.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 and pandas will auto-detect
    the height of the terminal and print a truncated object which fits
    the screen height. The IPython notebook, IPython qtconsole, or
    IDLE do not run in a terminal and hence it is not possible to do
    correct auto-detection.
    [default: 60] [currently: 400]
display.max_seq_items : int or None
    When pretty-printing a long sequence, no more then `max_seq_items`
    will be printed. If items are omitted, they will be denoted by the
    addition of "..." to the resulting string.

    If set to None, the number of items to be printed is unlimited.
    [default: 100] [currently: 100]
display.memory_usage : bool, string or None
    This specifies if the memory usage of a DataFrame should be displayed when
    df.info() is called. Valid values True,False,'deep'
    [default: True] [currently: True]
display.min_rows : int
    The numbers of rows to show in a truncated view (when `max_rows` is
    exceeded). Ignored when `max_rows` is set to None or 0. When set to
    None, follows the value of `max_rows`.
    [default: 10] [currently: 10]
display.multi_sparse : boolean
    "sparsify" MultiIndex display (don't display repeated
    elements in outer levels within groups)
    [default: True] [currently: True]
display.notebook_repr_html : boolean
    When True, IPython notebook will use html representation for
    pandas objects (if it is available).
    [default: True] [currently: True]
display.pprint_nest_depth : int
    Controls the number of nested levels to process when pretty-printing
    [default: 3] [currently: 3]
display.precision : int
    Floating point output precision in terms of number of places after the
    decimal, for regular formatting as well as scientific notation. Similar
    to ``precision`` in :meth:`numpy.set_printoptions`.
    [default: 6] [currently: 6]
display.show_dimensions : boolean or 'truncate'
    Whether to print out dimensions at the end of DataFrame repr.
    If 'truncate' is specified, only print out the dimensions if the
    frame is truncated (e.g. not display all rows and/or columns)
    [default: truncate] [currently: truncate]
display.unicode.ambiguous_as_wide : boolean
    Whether to use the Unicode East Asian Width to calculate the display text
    width.
    Enabling this may affect to the performance (default: False)
    [default: False] [currently: False]
display.unicode.east_asian_width : boolean
    Whether to use the Unicode East Asian Width to calculate the display text
    width.
    Enabling this may affect to the performance (default: False)
    [default: False] [currently: False]
display.width : int
    Width of the display in characters. In case python/IPython is running in
    a terminal this can be set to None and pandas will correctly auto-detect
    the width.
    Note that the IPython notebook, IPython qtconsole, or IDLE do not run in a
    terminal and hence it is not possible to correctly detect the width.
    [default: 80] [currently: 80]

To reset the configurations we can use 

`pd.reset_option(' ')`

| Function | Purpose | When to use |
|----------|--------|-------------|
| pd.reset_option('option_name') | Reset specific config | When one config is incorrect |
| pd.reset_option('all') | Reset everything to default | Fresh start or debugging issues |

To get the current option that is set

`pd.get_option()`

In [4]:
pd.get_option("display.max_rows")

400

To temperorily update the value of any settings we can use this 

`pd.get_option(" setting_name ")`

In [5]:
with pd.option_context('display.max_rows', 12):
    print(pd.get_option("display.max_rows"))
    # print(df)
pd.get_option("display.max_rows")

12

400

# Section 2:-  Series

Series is an 1-dimensional labeled array capable of holding any data type.

A Series is backed by an array-like structure. Arrays are homogeneous.

A Series has a single dtype. If all values can be represented by one efficient dtype (like `int64` or `float64`), Pandas uses that. If not, it uses `object` (or another suitable extension dtype) so every element still has the same dtype.

Series has 3 important components

1. Values → actual data (data)
2. Index → labels for each data point (metadata)
3. Dtype → datype of the values (metadata)


index by default is auto generated but can be customized 

The auto-generated index is a *RangeIndex* starting from 0 to n-1 where n is the number of values in the series

RangeIndex or even the customized index are metadata that is used to access the values in the series, they are not the part of the actual data. 

both values and index can contain any datatypes 

index and value need not be homogenous 

`len(index) == len(value)`

## 2.1 Creating Series 

Any ordered iterables can be converted into series using the contructor in pandas.

`pd.Series( iterable_name )`

Hence we are creating an object of type Series. It wraps existing data into a richer data structure.

### 1. From list

In [6]:
i1 = [1,2,3,4,5,6]
print(type(i1))
series1 = pd.Series(i1)
print(type(series1))
series1

<class 'list'>
<class 'pandas.Series'>

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

### 2. From tuple

Even thou tuple is immutable, the resulting series is mutable

In [7]:
i1 = (1,2,3,4,5,6)
print(type(i1))
series1 = pd.Series(i1)
print(type(series1))
series1

<class 'tuple'>
<class 'pandas.Series'>

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

### 3. From Numpy array 

pandas is built on top of numpy array.

So unlike for list, dict, tuple, pandas doesn't want to look for each element to determine the dtype, numpy is already int/ float

Pandas doesn't always invent the dtype—it often inherits it from the underlying array.

The real difference between numpy and series is 

| Feature               | NumPy Array                                                         | Pandas Series                                                                                      |
| --------------------- | ------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------- |
| **Data type (dtype)** | One dtype for the entire array                                      | One dtype for the entire Series (except `object` or extension dtypes can hold more general values) |
| **Index**             | Positional index (0, 1, 2, ...)                                     | Has an explicit index (can be labels like `"A"`, `"B"`, etc.)                                      |
| **Arithmetic**        | Position-based                                                      | **Index-aligned**                                                                                  |
| **Missing values**    | Limited (`NaN` only for floats, newer nullable types in some cases) | Better support (`NaN`, `<NA>`, nullable dtypes)                                                    |
| **Purpose**           | Fast numerical computing                                            | Labeled data analysis                                                                              |

In [8]:
print(pd.Series(np.array([10, 20, 30, 40])))

0    10
1    20
2    30
3    40
dtype: int64

### 4. From Series
We can pass a series inside theh `Series` constructor and get the Series

### 5. From Dictionary

dictionaries passed inside `Series` behave a bit different from the other ways 

By using Dictionary we can have our custom index.

The keys of the series becomes the index and the values becomes the values

### Single value Series

We can pass a string or a number as a single entry inside a Series and unlike collections, this single value is considered as a whole.

In [9]:
print(pd.Series("Shiva"))
print(pd.Series(2))

0    Shiva
dtype: str
0    2
dtype: int64

### Wrong ways to create a series

When we pass the **Set** we get type error as Series can take only ordered iterables and **set is unordered**

In [10]:
# i1 = {1,2,3,4,5,6}
# print(type(i1))
# series1 = pd.Series(i1)
# print(type(series1))
# series1

# ---------------------------------------------------------------------------
# TypeError                                 Traceback (most recent call last)
# Cell In[227], line 3
#       1 i1 = {1,2,3,4,5,6}
#       2 print(type(i1))
# ----> 3 series1 = pd.Series(i1)
#       4 print(type(series1))
#       5 series1

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\series.py:514, in Series.__init__(self, data, index, dtype, name, copy)
#     512         data = data.copy(deep=True)
#     513 else:
# --> 514     data = sanitize_array(data, index, dtype, copy)
#     515     data = SingleBlockManager.from_array(data, index, refs=refs)
#     517 NDFrame.__init__(self, data)

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\construction.py:656, in sanitize_array(data, index, dtype, copy, allow_2d)
#     647     return sanitize_array(
#     648         data,
#     649         index=index,
#    (...)    652         allow_2d=allow_2d,
#     653     )
#     655 else:
# --> 656     _sanitize_non_ordered(data)
#     657     # materialize e.g. generators, convert e.g. tuples, abc.ValueView
#     658     data = list(data)

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\construction.py:715, in _sanitize_non_ordered(data)
#     711 """
#     712 Raise only for unordered sets, e.g., not for dict_keys
#     713 """
#     714 if isinstance(data, (set, frozenset)):
# --> 715     raise TypeError(f"'{type(data).__name__}' type is unordered")

# TypeError: 'set' type is unordered

## 2.2. Series constr args

Series can be created from a constructor 

this constructor can take arguments like 

1. data
2. index
3. dtype
4. name
5. copy

These are the common constructor args of a Series 

1. **data :-** 

    stores the values in the series object. 

    This can be a keyword or a positional arg

2. **index:-**

    forms the label for these data and is a metadata 

    this can be RangedIndex or a custom one 

3. **dtype:-**

    This is another metadata about the Series 

    this represents what is the data type each value is inside the series 

    this doesn't care about the datatype of index

    We can provide any suitable dataype to out series ( int can be represented as loat and vice verse, but dont convert string to int, etc. )

4. **name:-**

    This gives a name to the values inside the object 

    This is not the variable but a metadata and this travels with the object 

    It helps Pandas preserve meaningful labels instead of treating everything as anonymous data.

    This acts as a column name when we are trying to convert a series into a dataframe 

5. **copy:-**

    provides the asnwer to how this series going to be: Should the Series use the original data, or should it create its own independent copy

In [11]:
[print(type(x)) for x in (pd.Series([1,2,3,4],index=["hi",4,True,3.4]).index )]
(pd.Series([1,2,3,4],index=["hi",4,True,3.4]))

<class 'str'>
<class 'int'>
<class 'bool'>
<class 'float'>

hi      1
4       2
True    3
3.4     4
dtype: int64

In [12]:
pd.Series(
    [10, 20, 30],
    name="Marks"
)

0    10
1    20
2    30
Name: Marks, dtype: int64

In [13]:
print(pd.Series(
    np.array(
        [10, 20, 30],
        dtype=np.float32
    )
)
)

0    10.0
1    20.0
2    30.0
dtype: float32

## 2.3 Index of Series 

The general list or array or rangedIndex provides only the positional number, but what if we want to provide a meaning to the values rather than just the positional numbers 

Thus we use `index`, this can be having rangedIndex or positional number but also holds the label of the values 

So if we want to have mapping to data we can use `dict` but the need of `series` is computational efficiency, index provides the mapping part.

index is not a mart of the business data (main data) but rather an meta data

Position gives the info of where the data is stored 

`pd.Series([10, 20, 30])`

Here 20 is in position 1 but when we delete 10 then 20 becomes position(in terms of list or other collections) 0  

But, in pandas the index doesn't work in that concept, each position is considered as a label.  

When we give index

`pd.Series([10, 20, 30], index=['a', 'b', 'c'])`

even if we delete 10 the label of 20 is b, the position in the series is 0 but label is not changed. 

Pandas keep the data of both position and the label

In [14]:
print(type(pd.Series([10, 20, 30]).index))

<class 'pandas.RangeIndex'>

In [15]:
s  = pd.Series([10, 20, 30]) 
print(s)

0    10
1    20
2    30
dtype: int64

In [16]:
s = s.drop(0)
print(s)

1    20
2    30
dtype: int64


Pandas primarily thinks in terms of labels, not positions.

Almost every advanced Pandas feature depends on this distinction.

We can access the index of the series using the attribute `.index` on  series

When you:

    - align two Series,
    - join datasets,
    - merge tables,
    - reindex,
    - group data


### 2.3.1 Default Index

By default the pandas create a rangeindex, when we check the type of the index on a series we get `RangeIndex`

This is because if we store the index as a list then the python memory has to store the data from 0-n 

but when we store it as rangeindex we need to store `start=0 stop=n step=1`

Thus it is a memory saving approach

In [17]:
s  = pd.Series([10, 20, 30]) 
print(s)

0    10
1    20
2    30
dtype: int64

### 2.3.2 Custom Index 

An index whose labels are chosen by you instead of being automatically generated by Pandas.

customindex provides more meaning to the data.

Almost any hashable value can be an index label.

When we use custom label instead of the rangeindex it will be of type index.

In [18]:
print(type(pd.Series([10, 20, 30],index=["A", "B", "C"]).index))

<class 'pandas.Index'>

we create custom index when each value already have a meaningful business identity

We can create custom index by 2 ways 
1. dictionary 
2. `index` arg


#### 2.3.2.1. From Dictionary

When we pass a dictionary as an arg for Series constructor, the 
1. **keys = index** 
2.  **values = elements**

In [19]:
# dictionary 
print(type({1:2,3:4,5:6}))

# series with dictionary 
print(type(pd.Series({1:2,3:4,5:6})))

print((pd.Series({1:2,3:4,5:6})))

# type of the index
print(type(pd.Series({1:2,3:4,5:6}).index))

print((pd.Series({1:2,3:4,5:6}).index))

<class 'dict'>
<class 'pandas.Series'>
1    2
3    4
5    6
dtype: int64
<class 'pandas.RangeIndex'>
RangeIndex(start=1, stop=7, step=2)

#### 2.3.2.2. Using `index`

We can create/ define the index for our series using the arg. index in Series constructor.

`pd.Series( iterable_values , index= iterable_index )`

The iterable index can also be another collection like list/tuple , else we'll get ***TypeError***

In [20]:
print(pd.Series([10, 20, 30], index=['a', 'b', 'c']))

a    10
b    20
c    30
dtype: int64

**Note:-**

The ***len(index) == len(value)*** if the lenghts didn't match then we will get error 

**ValueError** when ***len(index) != len(value)***

In [21]:
# print(pd.Series([10, 20, 30], index=['a', 'b', 'c', 'd']))


# ---------------------------------------------------------------------------
# ValueError                                Traceback (most recent call last)
# Cell In[244], line 1
# ----> 1 print(pd.Series([10, 20, 30], index=['a', 'b', 'c', 'd']))

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\series.py:503, in Series.__init__(self, data, index, dtype, name, copy)
#     501     index = default_index(len(data))
#     502 elif is_list_like(data):
# --> 503     com.require_length_match(data, index)
#     505 # create/copy the manager
#     506 if isinstance(data, SingleBlockManager):

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\common.py:601, in require_length_match(data, index)
#     597 """
#     598 Check the length of data matches the length of the index.
#     599 """
#     600 if len(data) != len(index):
# --> 601     raise ValueError(
#     602         "Length of values "
#     603         f"({len(data)}) "
#     604         "does not match length of index "
#     605         f"({len(index)})"
#     606     )

# ValueError: Length of values (3) does not match length of index (4)

**Note:-** :
What happens when we pass both index and dictionary for this series constructor. 

we could see the order changes.

we could see one index which is not included in index is not appearing in the series 

So Pandas use the index to get the values needed from the dict to create the series. 

This index is also customized to provide a different order than the one in the dict.

In [22]:
print(pd.Series({
    "Alice": 95,
    "Bob": 88,
    "Charlie": 91
},
index=["Charlie", "Alice"]))

Charlie    91
Alice      95
dtype: int64

In [23]:
print(pd.Series({
    "Alice": 95,
    "Charlie": 91
},
index=["Charlie", "Alice","Siva"]))

Charlie    91.0
Alice      95.0
Siva        NaN
dtype: float64

When the `len(index) != len(dict)` there is no error, because
1. pandas uses the index to get the values from the dict
2. value present -> use that to form a series 
3. value missin -> make that value as `Nan`
4. The order of the output follows the index you supplied


This is thus different from tuple or list


From the above we can see that :

*The dtype changed from int64 to float64*

This is because `NaN` is defined in the floating point standard and integer cannot have `Nan` values and this `NaN` is from numpy

In [24]:
pd.Series([1, None, 3])

0    1.0
1    NaN
2    3.0
dtype: float64

In [25]:
pd.Series([1, None, 3], dtype="Int64")

0       1
1    <NA>
2       3
dtype: Int64

### 2.3.3 Duplicate Index 

The index of a series can have duplicate values. Because Pandas is built for data analysis, not enforcing database constraints. 

When we try to access a data with duplicate enntries, instead of fetching only one or the first one or throwing error it gives all the matching results.

To check if the series has unique index or not we can use  `.is_unique` on the index of the series.

In [26]:
sales = pd.Series(
    [100, 150, 200],
    index=["Chennai", "Delhi", "Chennai"]
)
emp = pd.Series(
    [200,100,30],
    index= ["IT","Finance","HR"]
)
print(f"Unique index:- \n{sales["Delhi"]}")
print(f"Duplicate index:- \n{sales["Chennai"]}")
print(f"Series has unique index:- {sales.index.is_unique}")
print(f"Series has unique index:- {emp.index.is_unique}")

Unique index:-
150
Duplicate index:-
Chennai    100
Chennai    200
dtype: int64
Series has unique index:- False
Series has unique index:- True

### 2.3.4 Index Immutability 

The index of the series is immutable. i.e once created it cannot be edited

Trying to edit the index will throw `TypeError` 

Remaning the index would have 3 approaches 
1. `.rename()`
2. assigning the new index values `.index` of the series object 
3. `.reset_index()` <- for rangedIndex


So how does the functions `rename()` or assigning values works <- this is not editing the index name it is creating a new index 

Now the need for this index to be immutable is to 
1. increase efficiency
2. provide safety

In [27]:
s = pd.Series(
    [50000, 65000, 70000],
    index=["Alice", "Bob", "Charlie"]
)

print(f"index of position 0:- {s.index[0]}")

# commenting as the value below code causing error in higher python libraries


# print(f"Value of position 0:- {s[0]}")

# s[0] = 60000

# print(f"Value of position 0 after editing:- {s[0]}")

index of position 0:- Alice

In [28]:
## Trying to override the index

# s.index[0] = "David"


# ---------------------------------------------------------------------------
# TypeError                                 Traceback (most recent call last)
# Cell In[84], line 8
#       6 print(f"index of position 0:- {s.index[0]}")
#       7 print(f"Value of position 0:- {s[0]}")
# ----> 8 s.index[0] = "David"

# File h:\Coding\Anaconda\Lib\site-packages\pandas\core\indexes\base.py:5371, in Index.__setitem__(self, key, value)
#    5369 @final
#    5370 def __setitem__(self, key, value) -> None:
# -> 5371     raise TypeError("Index does not support mutable operations")

# TypeError: Index does not support mutable operations

In [29]:
# updating the index
print(s.index)
s.index = ['A','B','C']
print(s.index)
print(s)

Index(['Alice', 'Bob', 'Charlie'], dtype='str')
Index(['A', 'B', 'C'], dtype='str')
A    50000
B    65000
C    70000
dtype: int64

In [30]:
# s.index[0]='X'

# ---------------------------------------------------------------------------
# TypeError                                 Traceback (most recent call last)
# Cell In[102], line 1
# ----> 1 s.index[0:1]=['X']

# File h:\Coding\Anaconda\Lib\site-packages\pandas\core\indexes\base.py:5371, in Index.__setitem__(self, key, value)
#    5369 @final
#    5370 def __setitem__(self, key, value) -> None:
# -> 5371     raise TypeError("Index does not support mutable operations")

# TypeError: Index does not support mutable operations

### 2.3.5 Index Alignment

The important need for the index in series is to maintain the alignment. 

When we use numpy all the operations were based on the position and not the index 

So pandas series uses the index to maintain the proper corresponding values are involved in the computation

Alignment is Pandas' automatic process of matching data based on index labels before performing operations. 

Instead of combining values by their positions, Pandas first aligns records with the same index labels, ensuring that calculations are performed on logically corresponding data. 

If a label is missing in one Series, the result for that label becomes NaN rather than producing an incorrect calculation.

In [31]:
# without the custom index - order not maintained

salary = pd.Series(
    [50000,60000,70000])

bonus = pd.Series(
    [0.7,0.5,0.6])

print(salary+bonus)

0    50000.7
1    60000.5
2    70000.6
dtype: float64

In [32]:
# with custom index - order maintained

salary = pd.Series(
    [50000,60000,70000],
    index=["Alice","Bob","Charlie"]
)

bonus = pd.Series(
    [0.7,0.5,0.6],
    index=["Charlie","Alice","Bob"]
)

print(salary+bonus)

Alice      50000.5
Bob        60000.6
Charlie    70000.7
dtype: float64

When the series are of different size, now the missing index gets`Nan` value as one series is not able to find that index

in positional based, the last value gets `Nan`

In [33]:
salary = pd.Series(
    [50000,60000,70000])

bonus = pd.Series(
    [5000,7000])
print(salary+bonus)

0    55000.0
1    67000.0
2        NaN
dtype: float64

In [34]:
salary = pd.Series(
    [50000,60000,70000],
    index=["Alice","Bob","Charlie"]
)

bonus = pd.Series(
    [5000,7000],
    index=["Alice","Charlie"]
)
print(salary+bonus)

Alice      55000.0
Bob            NaN
Charlie    77000.0
dtype: float64

### 2.3.6 Reset Index

Reset index is for discarding the existing index and produce a new default RangeIndex for the data 

this is useful during filter and sorting 

For DataFrames, the old index can be converted into a normal column.

For a Series, the behavior is slightly different because a Series has only one data column.

We can do that by using `.reset_index()`

## 2.4 Attributes in Series 

Attributes are properties of an object that provide information about its state or characteristics. 

For a Pandas Series, attributes often give metadata about the Series.

These attributes, based on the meta data it provides we can classify them as 

1. Structural
2. Metadata 
3. Advanced  

These are based on the data they return and is not structured likely in python. Advanced ttributes are rarely used in the day-to-day activity 


1. Structural Attributes 

    a. `.index` <- returns type *Index or Rangeindex* with index of the Series 

    b. `.value` <- returns type *numpy.ndarray* the underlying data of the Series as a NumPy array.

    It is not advisable to do operations on using the values alone as, 
    Using values removes the index (identity layer), so Pandas can no longer perform automatic alignment. Subsequent operations are performed positionally like NumPy arrays, which can lead to incorrect results if the data is not in the same order.

    c. `.dtype` <-  Describes the dataype of the entire series object. 

    d. `.shape` <- pandas always returns a *tuple* that contains the dimension of the object i.e. in series (no. elements,) in the series 

    To create a tuple with one element, Python requires a trailing comma. Hence the trailing comma.

    This changes for dataframes as (no. rows, no. columns)

    Shape thus describes how the elements are arranged

    e. `.size` <- return the *int* of how many individual values exist i.e. total no. of elements 

    f. `.ndim` <- returns no. of dimensions, this is 0 for a scalar, 1 for series and 2 for dataframe  


2. Metadata Attributes 

    a. `.name` <- the constructor takes `name` arg, this attribute returns that name of the series 

    b. `.empty` <- returns a boolean response on whether the series has empty values (no values) or has any values inside it. 

    If all the values are `Nan` in the series then also it is **not considered as an empty series**.

    Empty meanns no rows exist at all. So there should be absolutely no values while `nan` is considered to be a value.


    c. `.hasnans` <- returns *boolean* response if there are any presence of `Nan` in the series. 

    Even a single `nan` in the list will provide this to be `True`


3. Advanced Attributes

    a. `.array` <- returns the *pandas* extension array of values of a series.

    Even thou `.values` returnt he array of values they are represented by numpy array, but pandas has their own array structure. 

    Numpy cannot always be represented perfectly for thefollowing imporovements in pandas 
    - Nullable integers (Int64)
    - Nullable booleans
    - StringDtype
    - Categorical data
    - Arrow-backed arrays

    thus we use pandas extension array 

    b. `.flags` <- returns an object containing internal implementation flags.

    These flags help Pandas manage certain behaviors and internal guarantees.

    this is almost never used.

In [35]:
s.index

Index(['A', 'B', 'C'], dtype='str')

In [36]:
type(pd.Series([1,2,3,4],index=[1,2,3,4]).values)

numpy.ndarray

In [37]:
print("+"*10+" Structured Attributes "+"+"*10 )
for att in ['index', 'values', 'dtype', 'shape','size', 'ndim']:
    print(f"{'='*5} Attribute: .{att} {'='*5}")
    print(getattr(s, att))

print("+"*10+" Metadata Attributes "+"+"*10 )
for att in ['name', 'empty', 'hasnans']:
    print(f"{'='*5} Attribute: .{att} {'='*5}")
    print(getattr(s, att))

print("+"*10+" Advanced Attributes "+"+"*10 )
for att in ['flags', 'array']:
    print(f"{'='*5} Attribute: .{att} {'='*5}")
    print(getattr(s, att))

++++++++++ Structured Attributes ++++++++++
===== Attribute: .index =====
Index(['A', 'B', 'C'], dtype='str')
===== Attribute: .values =====
[50000 65000 70000]
===== Attribute: .dtype =====
int64
===== Attribute: .shape =====
(3,)
===== Attribute: .size =====
3
===== Attribute: .ndim =====
1
++++++++++ Metadata Attributes ++++++++++
===== Attribute: .name =====
None
===== Attribute: .empty =====
False
===== Attribute: .hasnans =====
False
++++++++++ Advanced Attributes ++++++++++
===== Attribute: .flags =====
<Flags(allows_duplicate_labels=True)>
===== Attribute: .array =====
<NumpyExtensionArray>
[50000, 65000, 70000]
Length: 3, dtype: int64

**Note:-**
1. to get the list of all the attributes of a series or an object into `dir()`. 
2. To apply a particular attribute on a series we can use  `getattr(object, name_of the_attribute)`

### 2.4.1 Summary of Attributes 

| Syntax             | Purpose                                               | When to Use                                            | Returns                                             | Interview Note                                                                                                                            |
| ------------------ | ----------------------------------------------------- | ------------------------------------------------------ | --------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------- |
| `s.index`          | Returns the identity layer (labels) of the Series     | Inspect, reuse, or verify labels; understand alignment | `Index` / `RangeIndex` object                       | Returns an **Index object**, not a Python list. The Index is immutable and powers label-based operations.                                 |
| `s.values`         | Returns the underlying data                           | Interoperate with NumPy or libraries expecting arrays  | `numpy.ndarray`                                     | Returns only the **raw values**. The index is lost, so label-based alignment no longer applies. Modern Pandas often prefers `to_numpy()`. |
| `s.dtype`          | Shows how the values are stored internally            | Check data types before calculations or conversions    | `dtype` object (e.g., `int64`, `float64`, `object`) | Describes the **entire Series**, not individual elements. Determines which operations are valid.                                          |
| `s.shape`          | Describes the structure of the Series                 | Quickly inspect dimensions                             | Tuple `(n,)`                                        | Always returns a **tuple**. For a Series, it contains one value because a Series is one-dimensional.                                      |
| `s.size`           | Counts the total number of elements                   | Count values without considering structure             | Integer                                             | `size` counts elements, **not memory usage**. For a Series, `size == shape[0]`.                                                           |
| `s.ndim`           | Returns the number of dimensions                      | Write generic code for Series/DataFrames               | Integer (`1` for Series)                            | A Series always has **1 dimension**. A DataFrame has **2 dimensions**.                                                                    |
| `s.name`           | Returns the name of the Series                        | Reporting, labeling, converting to DataFrame           | `str` or `None`                                     | The name belongs to the **entire Series**, not the index or values.                                                                       |
| `s.empty`          | Checks whether the Series contains zero elements      | Validate input before processing                       | `bool`                                              | A Series containing only `NaN` values is **not** empty. Empty means **no elements exist**.                                                |
| `s.hasnans`        | Checks whether the Series contains any missing values | Data cleaning and preprocessing                        | `bool`                                              | Returns `True` if **at least one** value is missing.                                                                                      |
| `s.array`          | Returns the underlying Pandas ExtensionArray          | Advanced Pandas internals and extension dtypes         | `ExtensionArray`                                    | Preserves Pandas-specific dtypes. Different from `values`, which typically returns a NumPy array.                                         |
| `s.axes`           | Returns the axes of the Series                        | Generic Pandas programming                             | List containing the Index object                    | For a Series, it's essentially `[s.index]`. More useful with DataFrames than Series.                                                      |
| `s.flags`          | Returns internal configuration flags                  | Advanced debugging and library development             | `Flags` object                                      | Rarely used in day-to-day development. Provides information about internal behavior (e.g., duplicate label handling).                     |
| `s.memory_usage()` | Returns memory consumed by the Series                 | Performance tuning and memory optimization             | Integer (bytes)                                     | **Method**, not an attribute. Measures memory consumption, not the number of elements.                                                    |

## 2.5 Accessing Data

### 2.5.1 Accessors

The values of the data can be accessed by 5 common types 
1. `[]` operator
2. `.loc[]` indexer 
3. `.iloc` indexer
4. `.at[]` 
5. `.iat[]`

The last 2 types are not often used and they are attributes. 

1. `[]` operator 

    This is a very versatile operator that takes different type of input 

    The for accessing a value we pass only the *label* of the data and not the position inside this

    label slicing in Pandas is end inclusive.


    | Input Type   | Purpose             | Example                  |
    | ------------ | ------------------- | ------------------------ |
    | Single label | Get one value       | `s["B"]`                 |
    | Slice        | Get a range         | `s["A":"C"]` or `s[1:3]` |
    | List         | Get multiple values | `s[["A", "C"]]`          |
    | Boolean mask | Filter values       | `s[s > 20]`              |


    In pandas for slicing, this operator supports both index label and index position, but for accessing a single value the operators supports label alone. 

    Newer version of pandas are focusing only on using the `iloc` based approach for accessing by position.

    So we'll get a warning even if the code is working fine.

In [38]:
salary = pd.Series(
    [50000,60000,70000],
    index=["Alice","Bob","Charlie"]
)
print(salary['Bob'])
# print(salary[0])

60000

2. `.loc[]` indexer
    
    This is not a method but an accessor/ indexer

    We use is to access values by label 

    This is similar to that of `[]` operator. 

    Since this can take only label of the data, when there is no custom label, the rangedindex is the label of the data.

    in case of custom index, when we try to pass the position as the index we get the **KeyError** depending on the situation.

    Numbers, int, float can also be the custom labelfor the series to be searched using `.loc[]`

    For both `[]` operator and `.loc[]` indexer if we pass a key that is not there in the series we get **KeyError**
    
    So we use `.loc` instead of `[]` is to clearly denote that we are using label and not the index as this can be ambiguous with the `[]` operator. 

    We can perform the below operations with `.loc[]`
    
   - Single Label
   - Multiple Labels
   - Label Slice
   - Boolean Filtering

In [39]:
salary = pd.Series(
    [50000,60000,70000],
    index=["Alice","Bob","Charlie"]
)
print(salary.loc['Alice'])

50000

In [40]:
salary = pd.Series(
    [50000,60000,70000])
print(salary.loc[1])

60000

3. `iloc[]` operator

    `.iloc` is a position-based indexer used to access data using integer positions.
    
    This provides **TypeError** when we try to pass label inside it to access the data

    When the index passed is not in the series it raises to **IndexError**

    Even when the lables are int/ float it checks only the position and not the label. 

    We can perform the below operations with `.iloc[]`

   - Single Position
   - Multiple Positions
   - Position Slice
   - Boolean Filtering

In [41]:
salary = pd.Series(
    [50000,60000,70000])
print(salary.iloc[1])

60000

In [42]:
salary = pd.Series(
    [50000,60000,70000],
    index=["Alice","Bob","Charlie"]
)
print(salary.iloc[0])

50000

In [43]:
s = pd.Series(
    [100, 200, 300],
    index=[10, 20, 30]
)
print(s.iloc[1])
print(s.iloc[[1,0]])
print(s.iloc[0:2])

200
20    200
10    100
dtype: int64
10    100
20    200
dtype: int64

4. `.at[]` operator 

    `.at[]` is a label-based accessor optimized for retrieving or updating a single value.

    This is similar to that of `.loc[]`

In [44]:
s = pd.Series(
    [100, 200, 300],
    index=["A", "B", "B"]
)
print(s.at["B"])

B    200
B    300
dtype: int64

In [45]:
print(s.loc["B"])

B    200
B    300
dtype: int64

5. `iat[]` operator 

    `.iat[]` is a position-based accessor optimized for retrieving or updating a single value

    This is similar to that of `.iloc[]`

Both `.at[]` and `.iat[]` differs from `loc` and `iloc` is that using these `at` and `iat` we cannot perform the other operations like multiple label/position accessing, filtering or slicing

### 2.5.2 Access Patterns

We have a series and we have 4 accessors , we can use these accessors to access the values of the series 

We have different ways for accessing 
1. Scalar Access -> "Give me one."
2. Slice Access -> "Give me a continuous range."
3. Fancy Indexing -> "Give me these specific entries."
4. Boolean Indexing -> "Give me everything that satisfies a condition."

#### 2.5.2.1. Scalar access

Accessing just a single value is called as scalar value 

All the five accessor supports the scalar accessing 

It returns only a single scalar value and not the Series

In [46]:
s = pd.Series(
    [100, 200, 300, 400],
    index=["A", "B", "C", "D"]
)

print("+"*10+" Scalar  "+"+"*10 )
print("="*10+" [] Operator "+"="*10 )
print(s["B"])
print("="*10+" .loc[] Indexer "+"="*10 )
print(s.loc["B"])
print("+"*10+" .iloc[] Indexer "+"="*10 )
print(s.iloc[1])
print("+"*10+" .at[] Indexer "+"="*10 )
print(s.at["B"])
print("+"*10+" .iat[] Indexer "+"="*10 )
print(s.iat[1])

++++++++++ Scalar  ++++++++++
========== [] Operator ==========
200
========== .loc[] Indexer ==========
200
++++++++++ .iloc[] Indexer ==========
200
++++++++++ .at[] Indexer ==========
200
++++++++++ .iat[] Indexer ==========
200

#### 2.5.2.2. Slicing 

SLicing is to get a series or sequence of data from the series 

It returns a Series of data i.e. the type is also series 

Only 3 of the 5 operators supports slicing ( `.at` and `.iat` doesn't support slicing)

There are 2 types of slicing 
    1. position slicing 
    2. label slicing

Position slicing is done using `.iloc` and it behaves like normal python slicing i.e. end exclusive 

Label slicing is done using `.loc` and it is end inclusive

All slice opertations returns a Series

In [47]:
print("+"*10+" Slicing  "+"+"*10 )
print("="*10+" [] Operator "+"="*10 )
print(s["B":"C"])
print("="*10+" .loc[] Indexer "+"="*10 )
print(s.loc["B":"C"])
print("+"*10+" .iloc[] Indexer "+"="*10 )
print(s.iloc[1:2])

++++++++++ Slicing  ++++++++++
========== [] Operator ==========
B    200
C    300
dtype: int64
========== .loc[] Indexer ==========
B    200
C    300
dtype: int64
++++++++++ .iloc[] Indexer ==========
B    200
dtype: int64

#### 2.5.2.3. Multiple Values Accessing

Instead of slicing, when we want a radom values from the series we can pass a list of label/ position inside the respective accessor 

this also returns the list and Pandas returns results in the order you request, not the original order

all the values inside the list passed into the Series value accessor is included. 

When we try multiple values accessing with `[]` operator the list is considered as a list of lables only not as position

During label accessing when one of the key is not there we get **keyError** and none of the value is accessed. 

the return type is a series even if we pass a single item in the list.

In [48]:
print("+"*10+" Multiple  "+"+"*10 )
print("="*10+" [] Operator "+"="*10 )
print(s[["B","C"]])
print("="*10+" .loc[] Indexer "+"="*10 )
print(s.loc[["B","C"]])
print("+"*10+" .iloc[] Indexer "+"="*10 )
print(s.iloc[[1,2]])

++++++++++ Multiple  ++++++++++
========== [] Operator ==========
B    200
C    300
dtype: int64
========== .loc[] Indexer ==========
B    200
C    300
dtype: int64
++++++++++ .iloc[] Indexer ==========
B    200
C    300
dtype: int64

#### 2.5.2.4. Boolean indexing   

When we check a condition using a series we get a Boolean series and this is called as a Boolean mask 

When we pass this boolean mask to a series we get only the series that are satisfying the condition

We can directly pass the condition to the series accessor and get the resultant series. 

But only `[]` operator and `.loc[]` indexer works with this approach. 

When we try the same on the `iloc[]` it throws **ValueError**

But if we want to perform the same with `iloc[]` then we can convert the mask into a list and then pass it inside the indexer.

Boolean indexing always returns a Series, even if there is only one match.

In [49]:
print("+"*10+" Boolean Filtering  "+"+"*10 )
print("="*10+" [] Operator "+"="*10 )
print(s[s>200])
print("="*10+" .loc[] Indexer "+"="*10 )
print(s.loc[s>200])
print("+"*10+" .iloc[] Indexer "+"="*10 )
print(s.iloc[(s>200).to_list()])

++++++++++ Boolean Filtering  ++++++++++
========== [] Operator ==========
C    300
D    400
dtype: int64
========== .loc[] Indexer ==========
C    300
D    400
dtype: int64
++++++++++ .iloc[] Indexer ==========
C    300
D    400
dtype: int64

**Multiple Condition :-**
We can pass multiple conditions using the below operators 

1. For AND `&`
2. for OR `|`
3. For NOT `~`

We need to segment each condition inside a separate paranthesis.

In [50]:
print(s[(s < 150) | (s > 350)])
print(s[(s > 100) & (s < 400)])
print(s[~(s > 200)])

A    100
D    400
dtype: int64
B    200
C    300
dtype: int64
A    100
B    200
dtype: int64

## 2.6 Updating Data

Updating a data in Series is similar to the one we do in list. 

We access the data and assign the value to it. This updates the value for the accessed data position/ label.

`series['label'] = new_value`

When we try to update the values we need to make sure that the dtype of the new assignment matches the original series datatype.

The older versions may allow this assignment by converting the series into a type of object or needed one.

The values can be updated in 4 common scenarios 

1. update single value 
2. update multiple values 
3. update a slice
4. conditional update

### 2.6.1 Update a Single Value

We use one of the 5 operators to access the data and update its value by a simple assignment

In [51]:
# create a series
s = pd.Series(
    [100, 200, 300, 400],
    index=["A", "B", "C", "D"]
)
print(s)

# update the value
s['A'] = 300
print(s)

A    100
B    200
C    300
D    400
dtype: int64
A    300
B    200
C    300
D    400
dtype: int64

### 2.6.2 Update Multiple Values

Using fancy indexing we access multiple values by passing the list of position/ label and then updating them.

We can update the values for each of the index passed or can perform broadcasting

But during broadcasting we need to make sure that the assignment value is a scalar

During multiple updation, the value list length should be equal to the index list length else we'll get **ValueError**

In [52]:
print(s)
s.iloc[[1, 3]] = [250, 450]
print(s)

A    300
B    200
C    300
D    400
dtype: int64
A    300
B    250
C    300
D    450
dtype: int64

In [53]:
print(s)
s.loc[["B","D"]] = 250
print(s)

A    300
B    250
C    300
D    450
dtype: int64
A    300
B    250
C    300
D    250
dtype: int64

### 2.6.3 Update Sliced values 

we can use the concept of broadcasting here as this is one of the most commonly used combination 

### 2.6.4 Conditional updates

This is again the most combination of broadcasting for the conditional values. 

### 2.6.5 Broadcasting 

Assigning the same value to all or a sub-series of a whole is called broadcasting

In [54]:
# broadcasting - creation
a = pd.Series("Shiva",index=[1,2,3,4,5])
print(a)

# broadcasting - update
a.loc[2:5] = "Sai"
print(a)

1    Shiva
2    Shiva
3    Shiva
4    Shiva
5    Shiva
dtype: str
1    Shiva
2      Sai
3      Sai
4      Sai
5      Sai
dtype: str

In [55]:
print(s)
s[0:2] = 0
print(s)

A    300
B    250
C    300
D    250
dtype: int64
A      0
B      0
C    300
D    250
dtype: int64

**Note :-**

1. When we try to update a value by accessing the label, but the label is not present in the series, then it doesn't raise the error rather it creates a new entry inside the series

But this will not work when we try updating with position i.e. `iloc` or `iat`
2. If we try to update the value that is not the matching datatype then the series updates its datatype to a common one

**Pandas Multi-Row Assignment Rules:**

1. *Mixed Types (Works)*: Passing different data types with the same scalar shape—like integers and strings
`[500, 'Hi']` works automatically because NumPy can build a flat 1D array and safely upcast the Series to dtype: object.


2. *Mixed Shapes (Fails)*: Passing elements with different structural dimensions—like a scalar integer and a sequence container *[500, (10, 20)]* crashes with a ValueError because NumPy strictly rejects building arrays with inhomogeneous, asymmetrical shapes.

To overcome this we can use a dictionary approach `s.loc[["B", "C"]] = {"B": 500, "C": (10, 20)}`

In [56]:
print(s)
s['G'] = '10'
print(s)

A      0
B      0
C    300
D    250
dtype: int64
A      0
B      0
C    300
D    250
G     10
dtype: object

## 2.7 Series Vectorized Operations

Vectorization means applying an operation to every element of a Series (or DataFrame) at once, without writing an explicit Python loop.

Pandas loop inside its library, no explicit code has to be written for the looping - so loop happens but we are not writing

| Operator | Meaning               |
| -------- | --------------------- |
| `+`      | Add                   |
| `-`      | Subtract              |
| `*`      | Multiply              |
| `/`      | Divide                |
| `//`     | Floor Division        |
| `%`      | Modulus               |
| `**`     | Power                 |
| `>`      | Greater Than          |
| `<`      | Less Than             |
| `>=`     | Greater Than or Equal |
| `<=`     | Less Than or Equal    |
| `==`     | Equal                 |
| `!=`     | Not Equal             |


The vectorized operatiosn doesn't change the original series but returns a series as a result of this operation 

vectorization can be 
1. with a scalar `series operation scalar_value` eg:- `s*2`
2. between 2 series `series operation series`  eg:- `s1+s2`

In [57]:
s = pd.Series([1, 2, 3])
print(f"{'='*5} Multiplication {'='*5}")
print(s*2)
print(f"{'='*5} Addition {'='*5}")
print(s+2)
print(f"{'='*5} Division {'='*5}")
print(s/3)
print(f"{'='*5} Subtraction {'='*5}")
print(s-2)
print(f"{'='*5} Modulo {'='*5}")
print(s%2)
print(f"{'='*5} Square {'='*5}")
print(s**2)

===== Multiplication =====
0    2
1    4
2    6
dtype: int64
===== Addition =====
0    3
1    4
2    5
dtype: int64
===== Division =====
0    0.333333
1    0.666667
2    1.000000
dtype: float64
===== Subtraction =====
0   -1
1    0
2    1
dtype: int64
===== Modulo =====
0    1
1    0
2    1
dtype: int64
===== Square =====
0    1
1    4
2    9
dtype: int64

In [58]:
s1 = pd.Series(
    [100, 200, 300, 400],
    index=["A", "B", "C", "D"]
)

s2 = pd.Series(
    [10, 20, 30, 40],
    index=["A", "B", "C", "D"]
)

# between 2 series 
s1 * s2

A     1000
B     4000
C     9000
D    16000
dtype: int64

### 2.7.1 Automatic Alignment

When we are doing vectorization operations between 2 series, we could notice it was element to element operation between the series. 

But when the order of elements is different or the size of the series are different, pandas solves this by using the labels of each elements of the series. 

The vectorization operation is label based and not based on the position. 

Not just vectorization operation, all the automatic alignment are based on the label in pandas

In [59]:
s1 = pd.Series(
    [10,20,30],
    index=["A","B","C"]
)

s2 = pd.Series(
    [1,2,3],
    index=["B","C","A"]
)

print(s1 + s2)

A    13
B    21
C    32
dtype: int64

When there is a mismatch in labels then the mismatched labels are consider  to be in the series operation, then the mismatched label gets `NaN` values

In [60]:
s1 = pd.Series(
    [10,20,30],
    index=["A","B","C"]
)

s2 = pd.Series(
    [1,2,3],
    index=["B","C","D"]
)
print(s1 + s2)

A     NaN
B    21.0
C    32.0
D     NaN
dtype: float64

We do can ignore the alignment, but usually it is not done, by converting the series into a numpy array. 

When we do so the operation is purely based on the position and not based on the label.

In [61]:
print(s1.to_numpy() + s2.to_numpy())

[11 22 33]

## 2.8 Handling NaN 

### 2.8.1 `NaN`

`NaN`mean not a number, this means it is a missing value. It is a placeholder for missing information, not an actual number.

This doesn't originaly mean that `Nan` means missing value, Nan means not a number i.e. it is not a valid numeric value came as a result of 0/0. Pandas used this to represent the missing values too.

We use this from numpy library as pandas is originally built over numpy 

To create a numpy `nan` in pandas or in numpy array, we can use `np.nan`

Nan is a special floating-point value understood by NumPy and Pandas.

`Nan` is not same as `None`, None is *no object*, yet pandas can convert `none` into `nan`

`None` is a Python object. `NaN` is a special numeric missing value.

The need for conversion of `None` to `nan` inside pandas is when we try to perform any mathematical operation with `None`, we get **TypeError** and the calculation crashed. 

The reason for the datatype changing from int to float is that `nan` is basically from *IEE Floating numbers standard*.  A Series needs to be in a homogenous datatype. Hence the entire series is converted into a floating  datatye rather staying as int. 

It can keep it as an object, but it chose to keep float because object calculation is time consuming, Python has to inspect every object individually.

In cases like these, when we have int type but due to null values it is as float, the recent pandas has `pd.Nan` and not `np.Nan`. This keeps the column to be as int. 

This is not a default one but is done by using the arg `dtype="Int64"` inside the series constructor. 

Here `Int` is the class name for `int` type and `64` is the bites, we can use `8`, `16` and `32` based on the data.

The reason is for ata to scientists choose the uppercase Int64 format is for memory savings, precise matching, and data integrity.

Data processing is rarely just about raw math speed; it is also about memory limits and data accuracy.

In [62]:
# series with default numpy nan

print(pd.Series([100, np.nan, 300]))

0    100.0
1      NaN
2    300.0
dtype: float64

In [63]:
# series with default none

print(pd.Series([10, None, 30]))

0    10.0
1     NaN
2    30.0
dtype: float64

In [64]:
# series with forced pandas nan

print(pd.Series([10, 20, None], dtype="Int64"))

0      10
1      20
2    <NA>
dtype: Int64

### 2.8.2 `NaN` behaviour 

1. **Arithmetic Propagates `NaN` :-**

When we try to do mathematical operations with `nan` we get the result as `nan`


2. **Comparison of `nan` is false:-**

When we compare any value with `nan` it is always false.

Even comparing two `nan` is always false. because, Both are missing. That does not mean both represent the same value.

Hence when we try not equal it is always true. even between `nan`

3. **Aggregate Functions ignores `Nan`:-**

When we use aggregate functions like `sum()`, `mean()`, etc, they always ignore the `nan` from the calculation. 

So of the length of the series is 5 with 1 `Nan`, `sum()` or `mean()` will perfrom only on the 4 values 

When we have a whole series as nan then what happens with these aggregates 
that depends, 
1. sum() -> returns 0 as it ignored all the nan
2. count() -> returns 0 as it ignored all the nan
3. mean() -> return nan as sum/count = 0/0 = nan

In [65]:
print(10+np.nan)
print(np.nan+np.nan)

nan
nan

In [66]:
print(10>np.nan)
print(np.nan == np.nan)
print(5!= np.nan)
print( np.nan != np.nan)

False
False
True
True

In [67]:
s = pd.Series([np.nan, np.nan])
print(s.max())
print(s.sum())
print(s.count())
print(s.mean())
print(s.min())

nan
0.0
0
nan
nan

### 2.8.3 Detecting `NaN`

We can detect the presence of nan using the below approaches
1. `isna()` method <- returns the *boolean series*, `True` if a label has `nan` and `False` if a label has no `nan`
2. `notna()` method <- returns the *boolean series* opposite of `isna()`, `False` if a label has `nan` and `True` if a label has no `nan`


We can use them by either directly calling these functions on the series object. 

`series_obj.isna()`

Or, we can call these method on the pandas and pass the series object inside it as an arg.

`pd.isna(series_obj)`

With the help of these returned boolean series, we can even perform conditional filtering.  

Difference between this `isna()` and `.hasnans` is that the first one is a method and returns a boolean series, thus can be used for filtering, while the later is an attribute and can provide whether the whole series has any `nan` or not it cannot say which index.

In [68]:
s = pd.Series([100, np.nan, 300])

# using series object
print(s.isna())

# using pandas
print(pd.isna(s))

# hasnans attribute
print(s.hasnans)

0    False
1     True
2    False
dtype: bool
0    False
1     True
2    False
dtype: bool
True

### 2.8.4 Handling `Nan`

There are 3 common strategies to handle the missing values 

1. Remove the record  <- `dropna()`
2. Replace with a value  <- `fillna()`
3. fill it with neighbouring values <- (forward fill or backward fill)

#### 2.8..4.1 Remove the reocrd
We drop the `nan` records from the series by calling `.dropna()` on the series 

this will not modify the existing series but returns a *new series* 

for positional indexes if we perform `dropna()` the positional value doesn't change, the reason being that they are positional labels and not row numbers, so the label is not changed or updated automatically. 

To reset the postiotional index to be in theproper order again we need to perform `.reset_index(drop = True)`, the `drop = True` arg is important as the older index will become the separate column thus becoming a dataframe

If we have no `nan` in the series there is no error returned

If we have all the values as `nan` then the empty series is returned.

In [69]:
# series 
s = pd.Series([100, np.nan, 300])
print(s)
print("-"*10)

# droping 
s.dropna()
print(s)
print("-"*10)

#droping and assigning
s = s.dropna()
print(s)
print("-"*10)

#reseting the index
s.reset_index()
print(s)
print("-"*10)

# reseting and assigning
a=s.reset_index()
print(a)
print(type(a))
print("-"*10)

# reset and assign with drop
b=s.reset_index(drop=True)
print(b)

0    100.0
1      NaN
2    300.0
dtype: float64
----------
0    100.0
1      NaN
2    300.0
dtype: float64
----------
0    100.0
2    300.0
dtype: float64
----------
0    100.0
2    300.0
dtype: float64
----------
   index      0
0      0  100.0
1      2  300.0
<class 'pandas.DataFrame'>
----------
0    100.0
1    300.0
dtype: float64

#### 2.8..4.2 Replace with Fixed value 

When we replace the values of `nan` with a fixed or calculated value we can use `.fillna()` on the series

Return a *new series* and will not affect the original series 

Since no data is lost, there is no change in the index/ label

There are 2 ways of filling 
1. use a fixed value <- but this is not suitable for all the scenarios eg. `.fillna(0)`
2. use a statistical value 

    There are 3 common statistical methods to fill the `nan`

    - `.fillna(s.mean())` <- used when the data is continuous and numeric / distribution is symmetric / no major outliers
    - `.fillna(s.median())` <- only on numeric data / skewed distribuion / outliers is there
    - `.fillna(s.mode()[0])` <- used when the data is categorical / outliers is there 

    For mode <- there can be multiple frequently occuring data with the same frequency. So we use this separate calculation of mode on a series and use the first output.

    If we didnt provide [0] for mode then the last value so mode returns a series and the last value of the series is considered to be the value to replace

In [70]:
s = pd.Series([100, np.nan, 300, 200, 100,200])
print(s)
print("-"*10)


# filling 
print("filling".upper())
s.fillna(0)
print(s)
print("-"*10)

# filling and assigning
print("filling and assigning fixed value ".upper())
a = s.fillna(0)
print(a)
print("-"*10)


# filling and assigning
print("filling Mean".upper(),s.mean())
b = s.fillna(s.mean())
print(b)
print("-"*10)


# filling and assigning
print("filling median".upper(),s.median())
c = s.fillna(s.median())
print(c)
print("-"*10)


# filling and assigning
print("filling mode".upper(),s.mode())
d = s.fillna(s.mode())
print(d)
print("-"*10)


# filling and assigning
print("filling mode[0]".upper(),s.mode()[0])
e = s.fillna(s.mode()[0])
print(e)
print("-"*10)

0    100.0
1      NaN
2    300.0
3    200.0
4    100.0
5    200.0
dtype: float64
----------
FILLING
0    100.0
1      NaN
2    300.0
3    200.0
4    100.0
5    200.0
dtype: float64
----------
FILLING AND ASSIGNING FIXED VALUE
0    100.0
1      0.0
2    300.0
3    200.0
4    100.0
5    200.0
dtype: float64
----------
FILLING MEAN 180.0
0    100.0
1    180.0
2    300.0
3    200.0
4    100.0
5    200.0
dtype: float64
----------
FILLING MEDIAN 200.0
0    100.0
1    200.0
2    300.0
3    200.0
4    100.0
5    200.0
dtype: float64
----------
FILLING MODE 0    100.0
1    200.0
dtype: float64
0    100.0
1    200.0
2    300.0
3    200.0
4    100.0
5    200.0
dtype: float64
----------
FILLING MODE[0] 100.0
0    100.0
1    100.0
2    300.0
3    200.0
4    100.0
5    200.0
dtype: float64
----------

#### 2.8..4.3 Replace with previous or next values

When a series has values where there is no sudden jump between the 2 values we can use this approach 

1. If a `nan` value needs to be fixed based on the previous value, then we use `.ffill()` 

   This will fill all the `nan` values with the previous value 

   If the first value is also `nan` then it cannot fill that 


2. If a `nan` value needs to be fixed based on the nect value, then we use `.bfill()` 

   This will fill all the `nan` values with the next value 

   If the last value is also `nan` then it cannot fill that

In [71]:
s = pd.Series([np.nan,2,np.nan,np.nan,3,np.nan,7,np.nan])
print(s)
print("-"*10)


# filling with forward fill
print("forward filling".upper())
a = s.ffill()
print(a)
print("-"*10)

# filling with backward fill
print("backward filling".upper())
b = s.bfill()
print(b)
print("-"*10)

0    NaN
1    2.0
2    NaN
3    NaN
4    3.0
5    NaN
6    7.0
7    NaN
dtype: float64
----------
FORWARD FILLING
0    NaN
1    2.0
2    2.0
3    2.0
4    3.0
5    3.0
6    7.0
7    7.0
dtype: float64
----------
BACKWARD FILLING
0    2.0
1    2.0
2    3.0
3    3.0
4    3.0
5    7.0
6    7.0
7    NaN
dtype: float64
----------

## 2.9 Series methods

For Methods we provide `()` as these are the functions of the series class and we are trying to access it through the object. 

We can classify the commonly used methods in series into 
1. Aggregation Methods
2. Descriptive Methods
3. Sorting Methods
4. Transformation Methods
5. Utility Methods

### 2.9.1 Aggregation Methods

Used to summarize the data by producing a single result, such as the sum, average, minimum, maximum, or count of values

To have a better model we can classify these aggregation methods into mini-groups 
1. Counting <- How many values do I have
2. Arithmatic <- Whats the total/average
3. Extremes <- What's the smallest/largest
4. Dispersion <- How spread out is the data

**Counting:-** 

1. `.count()` <- return *int* of number of **non-null values** in the series

    The common differnece between `count()` and `size` is that `size` includes non-null values while `count()` excludes them 
    
**Arithmatic:-**

2. `.sum()` <- returns a *float* value of the total (addition) of all the values in the series. This excludes `nan` so that, even if there is `nan` value in the series the result is an integer and not `nan`. 

    Sum of a series with only `nan` is also 0 and not `nan`

3. `.mean()` <- returns a *float* value of the average of series. This internally is equivalent of sum()/count(), hence this also exculdes the `nan` values.

    But when the series is having only `nan` values then sum =0  and count =0 hence the mean will be `nan`


**Extremes:-**

4. `.max()` <- returns a *float* the largest value in the series

5. `.min()` <- returns a *float* the smallest value in the series

    in both min and max `nan` is excluded. 

    For as series with only `nan`, then `nan` is returned 

    Pandas does not need to sort the entire Series. It can determine the smallest/ largest value by scanning once, making it more efficient than sorting just to find an extreme.

**Dispersion:-** This provides how far each value is from the mean, thus we get a better understanding of the data spread

6. `.var()` <- returns a *float* the variance of the enteries in a series  By default it used (n-1) as total entries (sample variance formula).
     
    variance is the average squared distance of each values from the mean 

7. `.std()` <- return a *float* of standard-deviation i.e. sqroot of variance. 

    standard-deviation is the average actual distance from the mean

Statistically low dispersion means better or consistent data. 

Meaning :- 
    If variance or standard-deviation is closer to the mean then the dispersion is low. 

### 2.9.2 Descriptive Methods

8. `.describe()` <- returns the *series* of vital statistical summary. 

    The index of the series will be the name of the statistic and the value will be the computed value for that statistic. 

    For a numerical series this includes: 

    - count
    - mean
    - std
    - min
    - 25% 50% 75% quantiles 
    - max 
    
    For a str series this includes:

    - count 
    - unique
    - top 
    - frequency 

9. `unique()` <- returns a *ndarray* of the unqiue values present in the series. It preserves the order of first appearance.

10. `nunique()` <- returns *int* of unique values present in the series.  

    by default it ignores the `nan` value to count as an unique data, if present, in the series. 

    To include that, we can pass the argument `dropna = False`  

11. `value_counts()` <- returns a *series* with index as the unique values in the series and value as the count of each unique values in the series.
    
    By default it ignores the `nan` value to count as an unique data, if present, in the series. To include that, we can pass the argument `dropna = False`  

    The second most used method after `describe()` for data analysts. 

    It shows the most frequent value first, so the sort is based on the counts. 

### 2.9.3 Sorting Methods

12. `sort_values()` <- return a *series* that has the value sorted in ascending order by default 

    To have the descending order, we can pass attribute `ascending = False`

    `Nan` is always considered to be at the end irresepective of ascending or descending. But this can be updated with the attribute `na_position =  'first'`  

    Index travels with the values, i.e. Pandas moves the entire pair, not just the values.

13. `sort_index()` <-returns a *series* that has the index sorted in ascending order by default 

When the values / index is of string the alphabetical order decides the order 

When 2 values/ index is same, then the element that appears first in the original series is given the first preference 

### 2.9.4 Transformation Methods

14. `astype()` <- returns the *new series* with the values whose datatypes are converted to another datatype. 

    This is like converting string or float to int like that. 

    This changes only the type of each of the value

    We pass the datatype to be converted inside this like `s.astype(int)` or `float` or `str`

    We get **valueError** is the conversion fails 

15. `map()` <- returns a *new series* where each value is updated with a new value based on a common function. 

    This accepts a mapping as an arg, where mapping can be a 
    
    - Dictionary 
    - function (normal function or lambda function(common))
    - Another series

    The mapping acts on all the values of a series. So if any of the values/ position/ label is not found during any of the mapping technique `nan` is returned for that value/ position. 

    We usually use `.map()` when we want to have a simple value to value transformation and is common for lookups

16. `.apply()` <- returns a *new series* that operates on each values of the series using a custom function. 

    `map()` is designed for element-wise mapping and supports functions, dictionaries, and Series for value replacement. 
    
    `apply()` is a more general-purpose method that applies a function to each element of a Series. 
    
    When using a lambda function, both often produce the same result, but `map()` is preferred for simple mappings, while `apply()` is preferred for custom transformations.

    both the methods i.e. `apply()` or `map()` does not filter, rg. `pd.Series([5,10,15,20]).map(lambda x: x%2==0)` returns a boolean series and not the values that satisfies the series. 

17. `replace()` <- returns a *new series* and is used when we want to update only a selected values and not the whole series. 

    we pass the old_value and new_value as args to the method. `pd.Series(["IT", "HR", "Finance", "HR"]).replace("HR", "Human Resources")` now only 'HR' gets updated and not the other values. 

    Too replace multiple values we can pass it as a dictionary with keys of dict = old values and values of dict = new values. 

### 2.9.5 Utility Methods

18. `head()` <- returns a *new Series* that displays only the first *n-number* of series data pair(position/label - value). 

    By default n=5 but this can be updated by drectly specifying the n value as positional argument inside head


19. `tail()` <- returns a *new Series* that displays only the last *n-number* of series data pair(position/label - value). 

    By default n=5 but this can be updated by drectly specifying the n value as positional argument inside head


20. `rename()`<- updates the *new series* but with the change in only the attribute `name` of the series. 


21. `copy()` <- returns a *new series* which is the copy of the original series.

    when we use this instead of `=` to create a new series from the old one, then any changes in the new will also reflect in the old one.

    When we use `copy()` then this issue will not happen as a new series on a whole is created. 

    There is an issue with `copy()`, when any of the elements inside this old series is mutuable, then any change on this element in the new copied  will affect the old series too

    To over come this we have an arg `deep=True` this splits the new and old completly hence no issues.

In [72]:
s = pd.Series([x for x in range(1,100)])
print(s.head())

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [73]:
s = pd.Series([5,10,15,20])
print(s.name)
y = s.rename("Marks")
print(s.name)
print(y.name)

None
None
Marks

In [74]:
s = pd.Series([5,10,15,20])

s.map(lambda x: x%2==0)

0    False
1     True
2    False
3     True
dtype: bool

In [75]:
# mapping using dictionary
s = pd.Series(["M", "F", "M", "F"])
print(s)
gender_map = {
    "M": "Male",
    "F": "Female"
}
print(s.map(gender_map))
print(s.map(str.upper))

0    M
1    F
2    M
3    F
dtype: str
0      Male
1    Female
2      Male
3    Female
dtype: str
0    M
1    F
2    M
3    F
dtype: str

In [76]:
# mapping using function
s = pd.Series([1,2,3,4])
s.map(lambda x: x*x)

0     1
1     4
2     9
3    16
dtype: int64

In [77]:
s.astype(int)

0    1
1    2
2    3
3    4
dtype: int64

In [78]:
print(a.sort_values())

1    2.0
2    2.0
3    2.0
4    3.0
5    3.0
6    7.0
7    7.0
0    NaN
dtype: float64

In [79]:
print(s.sort_values(ascending=False,na_position='first'))

3    4
2    3
1    2
0    1
dtype: int64

### 2.9.6 Series Methods Cheat sheet


| Method           | Parameter          | What It Controls          | Default             | Purpose / Behavior                                                                                                                    | Example                 |
| ---------------- | ------------------ | ------------------------- | ------------------- | ------------------------------------------------------------------------------------------------------------------------------------- | ----------------------- |
| `rename()`       | `index` / `mapper` | New Series name           | `None`              | Provide the new name for the Series.                                                                                                  | `s.rename("Marks")`     |
|                  | `inplace`          | Modify original object    | `False`             | **False** → Returns a new Series.<br>**True** → Modifies the original Series.                                                         | `inplace=True`          |
| `reset_index()`  | `drop`             | Keep/remove old index     | `False`             | **False** → Old index becomes a column (returns DataFrame).<br>**True** → Discards old index and returns a Series with a fresh index. | `drop=True`             |
|                  | `name`             | Name of value column      | `None`              | Used when `drop=False` to assign a name to the value column.                                                                          | `name="Marks"`          |
| `isna()`         | —                  | Detect missing values     | —                   | Returns `True` for missing values and `False` otherwise.                                                                              | `s.isna()`              |
| `notna()`        | —                  | Detect non-missing values | —                   | Returns `True` for non-missing values and `False` for missing values.                                                                 | `s.notna()`             |
| `dropna()`       | `inplace`          | Modify original object    | `False`             | **False** → Returns a new Series.<br>**True** → Removes NaNs from the original Series.                                                | `dropna(inplace=True)`  |
| `fillna()`       | `value`            | Replacement value         | **Required**        | Replace NaNs using a scalar, dictionary, Series, or computed value (`mean()`, `median()`, etc.).                                      | `fillna(0)`             |
|                  | `inplace`          | Modify original object    | `False`             | **False** → Returns a new Series.<br>**True** → Modifies the original Series.                                                         | `inplace=True`          |
|                  | `limit`            | Maximum fills             | `None`              | **None** → Fill all eligible NaNs.<br>Integer → Fill only the first *n* consecutive NaNs.                                             | `limit=2`               |
| `ffill()`        | `limit`            | Maximum forward fills     | `None`              | **None** → Fill all eligible NaNs.<br>Integer → Fill only the first *n* consecutive NaNs.                                             | `ffill(limit=2)`        |
|                  | `inplace`          | Modify original object    | `False`             | **False** → Returns a new Series.<br>**True** → Updates the original Series.                                                          | `inplace=True`          |
| `bfill()`        | `limit`            | Maximum backward fills    | `None`              | **None** → Fill all eligible NaNs.<br>Integer → Fill only the first *n* consecutive NaNs.                                             | `bfill(limit=2)`        |
|                  | `inplace`          | Modify original object    | `False`             | **False** → Returns a new Series.<br>**True** → Updates the original Series.                                                          | `inplace=True`          |
| `max()`          | `skipna`           | Ignore missing values     | `True`              | **True** → Ignore NaNs.<br>**False** → NaN propagates if present.                                                                     | `max(skipna=False)`     |
| `sum()`          | `skipna`           | Ignore missing values     | `True`              | **True** → Ignore NaNs.<br>**False** → NaN propagates if present.                                                                     | `sum(skipna=False)`     |
| `count()`        | —                  | Count valid values        | —                   | Counts only non-NaN values.                                                                                                           | `count()`               |
| `mean()`         | `skipna`           | Ignore missing values     | `True`              | **True** → Ignore NaNs.<br>**False** → NaN propagates.                                                                                | `mean(skipna=False)`    |
| `mode()`         | `dropna`           | Include missing values    | `True`              | **True** → Ignore NaNs.<br>**False** → NaN can become the mode.                                                                       | `mode(dropna=False)`    |
| `median()`       | `skipna`           | Ignore missing values     | `True`              | **True** → Ignore NaNs.<br>**False** → NaN propagates.                                                                                | `median(skipna=False)`  |
| `min()`          | `skipna`           | Ignore missing values     | `True`              | **True** → Ignore NaNs.<br>**False** → NaN propagates.                                                                                | `min(skipna=False)`     |
| `var()`          | `skipna`           | Ignore missing values     | `True`              | **True** → Ignore NaNs.<br>**False** → NaN propagates.                                                                                | `var(skipna=False)`     |
|                  | `ddof`             | Degrees of freedom        | `1`                 | **1** → Sample variance.<br>**0** → Population variance.                                                                              | `var(ddof=0)`           |
| `std()`          | `skipna`           | Ignore missing values     | `True`              | **True** → Ignore NaNs.<br>**False** → NaN propagates.                                                                                | `std(skipna=False)`     |
|                  | `ddof`             | Degrees of freedom        | `1`                 | **1** → Sample standard deviation.<br>**0** → Population standard deviation.                                                          | `std(ddof=0)`           |
| `describe()`     | `percentiles`      | Percentiles displayed     | `[0.25, 0.5, 0.75]` | Customize percentile summary.                                                                                                         | `percentiles=[0.1,0.9]` |
|                  | `include`          | Data types to include     | `None`              | Include specific data types or `"all"`.                                                                                               | `include="all"`         |
|                  | `exclude`          | Data types to exclude     | `None`              | Exclude specific data types.                                                                                                          | `exclude="number"`      |
| `unique()`       | —                  | Unique values             | —                   | Returns all distinct values.                                                                                                          | `unique()`              |
| `nunique()`      | `dropna`           | Count NaN or not          | `True`              | **True** → Ignore NaN.<br>**False** → Count NaN as a unique value.                                                                    | `dropna=False`          |
| `value_counts()` | `normalize`        | Counts vs proportions     | `False`             | **False** → Frequency counts.<br>**True** → Proportions/percentages.                                                                  | `normalize=True`        |
|                  | `sort`             | Sort by frequency         | `True`              | **True** → Sort by frequency.<br>**False** → Preserve original order.                                                                 | `sort=False`            |
|                  | `ascending`        | Sort order                | `False`             | **False** → Highest frequency first.<br>**True** → Lowest frequency first.                                                            | `ascending=True`        |
|                  | `dropna`           | Include missing values    | `True`              | **True** → Exclude NaNs.<br>**False** → Include NaNs.                                                                                 | `dropna=False`          |
| `sort_values()`  | `ascending`        | Sort direction            | `True`              | **True** → Ascending.<br>**False** → Descending.                                                                                      | `ascending=False`       |
|                  | `na_position`      | Position of NaNs          | `"last"`            | `"last"` → NaNs at end.<br>`"first"` → NaNs at beginning.                                                                             | `na_position="first"`   |
|                  | `ignore_index`     | Reset index               | `False`             | **False** → Keep original index.<br>**True** → Create a new sequential index.                                                         | `ignore_index=True`     |
|                  | `inplace`          | Modify original object    | `False`             | **False** → Returns new Series.<br>**True** → Modifies original.                                                                      | `inplace=True`          |
| `sort_index()`   | `ascending`        | Index order               | `True`              | **True** → Ascending.<br>**False** → Descending.                                                                                      | `ascending=False`       |
|                  | `ignore_index`     | Reset index               | `False`             | **False** → Keep existing index.<br>**True** → Assign new sequential index.                                                           | `ignore_index=True`     |
| `astype()`       | `dtype`            | Target data type          | **Required**        | Convert Series to the specified type.                                                                                                 | `astype(float)`         |
|                  | `errors`           | Error handling            | `"raise"`           | **"raise"** → Raise exception.<br>**"ignore"** → Return original Series if conversion fails.                                          | `errors="ignore"`       |
| `map()`          | `arg`              | Mapping object/function   | **Required**        | Accepts dictionary, Series, or function for element-wise mapping.                                                                     | `map(mapping)`          |
|                  | `na_action`        | Handle NaNs               | `None`              | **None** → Apply mapping to all values.<br>**"ignore"** → Skip NaNs.                                                                  | `na_action="ignore"`    |
| `apply()`        | `func`             | Function to apply         | **Required**        | Apply a custom function to every element.                                                                                             | `apply(lambda x: x*2)`  |
|                  | `convert_dtype`    | Infer better dtype        | `True`              | **True** → Infer optimal dtype.<br>**False** → Preserve object dtype.                                                                 | `convert_dtype=False`   |
| `replace()`      | `to_replace`       | Value(s) to replace       | **Required**        | Specify scalar, list, dictionary, or regex to match.                                                                                  | `replace("A","B")`      |
|                  | `value`            | Replacement value         | `None`              | Value that replaces the matched entries.                                                                                              | `replace(1,100)`        |
|                  | `regex`            | Pattern matching          | `False`             | **False** → Exact match.<br>**True** → Regular expression matching.                                                                   | `regex=True`            |
|                  | `inplace`          | Modify original object    | `False`             | **False** → Returns new Series.<br>**True** → Modifies original.                                                                      | `inplace=True`          |
| `head()`         | `n`                | Number of rows            | `5`                 | Return the first *n* rows.                                                                                                            | `head(10)`              |
| `tail()`         | `n`                | Number of rows            | `5`                 | Return the last *n* rows.                                                                                                             | `tail(3)`               |
| `copy()`         | `deep`             | Deep vs shallow copy      | `True`              | **True** → Independent copy.<br>**False** → Shallow copy (shares underlying data where applicable).                                   | `copy(deep=False)`      |

# Section 3 :- Interview for Series

## 3.1 — Why Series?

### **Q1. Why isn't a Python list sufficient for data analysis?**

**Answer**

- Lists don't support efficient vectorized operations.
- Lists don't have meaningful labels (only positions).
- Data alignment isn't possible.
- Numerical computations are slower compared to NumPy-backed Pandas objects.

---

### **Q2. Why use a Series instead of a list?**

**Answer**

A Series combines:

- Values
- Index (labels)

This allows:

- Label-based access
- Automatic alignment
- Vectorized operations
- Missing value handling.

---

## 3.2 — Anatomy of a Series

### **Q3. What are the three components of a Series?**

**Answer**

- Values
- Index
- `dtype`

---

### **Q4. What is metadata?**

**Answer**

Metadata is **data that describes the actual data**.

Examples:

- Index
- `dtype`
- Shape
- Size

---

### **Q5. What happens if no index is provided?**

**Answer**

Pandas automatically creates a **RangeIndex** starting from **0**.

---

## 3.3 — Index

### **Q6. Why isn't the index just row numbers?**

**Answer**

The index provides the **identity** of the data.

- Positions may change.
- Labels represent what the data belongs to.

---

### **Q7. What is RangeIndex?**

**Answer**

The default integer index automatically created by Pandas.

---

### **Q8. Why use a custom index?**

**Answer**

To represent meaningful labels instead of positions.

Examples:

- Employee IDs
- Student Roll Numbers
- Product Codes

---

### **Q9. Can a Series have duplicate indices?**

**Answer**

Yes.

Pandas allows duplicate indices.

However, certain operations become ambiguous.

---

### **Q10. Why is an Index immutable?**

**Answer**

Because it provides:

- Protection against accidental modification.
- Safe sharing between multiple Series/DataFrames.
- Better performance.
- Reliable alignment.

---

### **Q11. What is Index Alignment?**

**Answer**

During arithmetic operations, Pandas matches values using **labels** rather than positions.

---

### **Q12. When should we reset an index?**

**Answer**

Reset the index after:

- Filtering
- Dropping rows
- Sorting

when sequential numbering is desired.

---

## 3.4 — Series Attributes

### **Q13. What does `.index` return?**

**Answer**

Returns the **Index object**.

---

### **Q14. What does `.values` return?**

**Answer**

Returns the underlying **NumPy array**.

---

### **Q15. Why use NumPy internally?**

**Answer**

Because NumPy provides:

- Fast computations
- Efficient memory usage
- Vectorized operations

---

### **Q16. What does `.dtype` return?**

**Answer**

Returns the datatype of the stored values.

---

### **Q17. Difference between `.shape`, `.size`, and `.ndim`**

**Answer**

| Attribute | Meaning |
|-----------|---------|
| `.shape` | Dimensions |
| `.size` | Number of elements |
| `.ndim` | Number of axes |

---

## 3.5 — Accessing Data

### **Q18. Difference between `.loc` and `.iloc`**

**Answer**

| `.loc` | `.iloc` |
|--------|---------|
| Label-based | Position-based |
| Uses index labels | Uses integer positions |

---

### **Q19. Difference between `.at` and `.iat`**

**Answer**

Both access a **single value**.

| `.at` | `.iat` |
|-------|--------|
| Label-based | Position-based |

They are optimized for **scalar access**.

---

### **Q20. What is Boolean Indexing?**

**Answer**

Filtering using a Boolean Series.

**Example**

```python
s[s > 100]
```

---

## 3.6 — Updating Data

### **Q21. Can you create new labels while assigning?**

**Answer**

Yes.

```python
s["C"] = 100
```

If the label doesn't exist, Pandas automatically creates it.

---

## 3.7 — Vectorization

### **Q22. What are vectorized operations?**

**Answer**

Operations performed on the **entire Series at once** without explicit loops.

---

### **Q23. Why are vectorized operations faster?**

**Answer**

Because Pandas delegates computation to optimized NumPy implementations instead of Python-level loops.

---

## 3.8 — Automatic Alignment

### **Q24. Does Pandas align by position?**

**Answer**

No.

Pandas aligns data using **index labels**, not positions.

---

### **Q25. What happens when labels don't match?**

**Answer**

- The union of labels is formed.
- Missing matches become `NaN`.

---

## 3.9 — Missing Values

### **Q26. What is NaN?**

**Answer**

A special floating-point value used by Pandas to represent **missing or unknown data**.

---

### **Q27. Why not use 0 instead of NaN?**

**Answer**

Because **0 is a valid value**, whereas **NaN specifically indicates missing information**.

---

### **Q28. Why does an integer Series become `float64` after introducing NaN?**

**Answer**

A Series stores one homogeneous datatype.

Traditional `int64` cannot represent `NaN`, so Pandas performs **type promotion (upcasting)** to `float64`.

---

### **Q29. Is `"NaN"` the same as `np.nan`?**

**Answer**

No.

- `"NaN"` → String
- `np.nan` → Special floating-point value

---

### **Q30. Is `None` the same as NaN?**

**Answer**

No.

- `None` is a Python object.
- `NaN` is a floating-point representation for missing values.

Pandas often converts `None` to `NaN` in numeric Series.

---

### **Q31. Why is `np.nan == np.nan` False?**

**Answer**

Because `NaN` represents an **unknown value**.

Two unknown values are **not guaranteed to be equal**.

---

### **Q32. Why shouldn't we use `== np.nan`?**

**Answer**

Because comparisons with `NaN` always return `False`.

Use:

```python
isna()
```

instead.

---

### **Q33. Difference between `isna()` and `notna()`**

**Answer**

| Function | Purpose |
|----------|---------|
| `isna()` | Detect missing values |
| `notna()` | Detect non-missing values |

---

### **Q34. What does `s[s.isna()]` do?**

**Answer**

Returns only the rows whose values are missing.

---

### **Q35. How does NaN behave in arithmetic?**

**Answer**

Arithmetic involving `NaN` generally propagates `NaN`.

Example:

```python
NaN + 5   # NaN
NaN * 10  # NaN
```

---

### **Q36. How do aggregate functions treat NaN?**

**Answer**

Most aggregate functions ignore `NaN` by default, including:

- `sum()`
- `mean()`
- `min()`
- `max()`

**Special cases**

- `sum()` of an all-NaN Series returns **0.0** (identity element for addition).
- `mean()` of an all-NaN Series returns **NaN** because the average is undefined.

---

## 3. Creating Dataframes

## 4. Importing Dataframe

we can import dataframe from many types of file but the most commonly used are
1. csv <- `.read_csv("file_path")`
2. json <- `.read.json("file_path")`

For csv the first row is always considered as a header column, making them a column names

If the csv file doesn't have any first row data which is a header then we need to pass attribute  **header= None**

`.read_csv("file_path", header= None)`


python by default assigns a index to each rows and if we want to make a custom column as a label index for our rows we use **index_col="column_name"**

`.read_csv("file_path", header= None, index_col="column_name")`


we can also import only the needed columns from a whole csv, this is by using `usecols = [index of the column, index of the column]`

eg. `.read_csv("file_path", header= None, index_col="column_name", usecols=  [0,1,2])`

In [80]:
df = pd.read_csv(r'techcorp_workforce.csv',index_col='id')
df.head()

   first_name  last_name department  salary phone_number joining_date
id
1       Sarah   Mitchell         HR   95000     555-0101   15-03-2021
2     Michael       Chen         HR   88000     555-0102   01-06-2022
3       Emily  Rodriguez         HR   82500          NaN   20-09-2021
4       David       Park         HR   80000     555-0104   10-01-2023
5        Lisa   Thompson         HR   65000          NaN   05-04-2021

In [81]:
sales_df = pd.read_csv(r'sales.csv')

In [82]:
rest_df = pd.read_csv(r"sf_restaurant_health_violations.csv" , index_col='business_id')
rest_df.head()

,business_name,business_address,business_city,business_state,business_postal_code,business_latitude,business_longitude,business_location,business_phone_number,inspection_id,inspection_date,inspection_score,inspection_type,violation_id,violation_description,risk_category
business_id,,,,,,,,,,,,,,,,
5800,John Chin Elementary School,350 Broadway St,San Francisco,CA,94133.0,37.80,-122.40,"{'longitude': '-122.403154', 'needs_recoding':...",NaN,5800_20171017,17-10-2017,98.0,Routine - Unscheduled,5800_20171017_103149,Wiping cloths not clean or properly stored or ...,Low Risk
64236,Sutter Pub and Restaurant,700 Sutter St,San Francisco,CA,94102.0,37.79,-122.41,"{'longitude': '-122.41188', 'needs_recoding': ...",NaN,64236_20170725,25-07-2017,88.0,Routine - Unscheduled,64236_20170725_103133,Foods not protected from contamination,Moderate Risk
1991,SRI THAI CUISINE,4621 LINCOLN Way,San Francisco,CA,94122.0,37.76,-122.51,"{'longitude': '-122.507779', 'needs_recoding':...",NaN,1991_20171129,29-11-2017,86.0,Routine - Unscheduled,1991_20171129_103139,Improper food storage,Low Risk
3816,Washington Bakery & Restaurant,733 Washington St,San Francisco,CA,94108.0,37.80,-122.41,"{'longitude': '-122.405845', 'needs_recoding':...",NaN,3816_20160728,28-07-2016,67.0,Routine - Unscheduled,3816_20160728_103108,Contaminated or adulterated food,High Risk
39119,Brothers Restaurant,4128 GEARY Blvd,San Francisco,CA,94118.0,37.78,-122.46,"{'longitude': '-122.463762', 'needs_recoding':...",NaN,39119_20160718,18-07-2016,79.0,Routine - Unscheduled,39119_20160718_103133,Foods not protected from contamination,Moderate Risk

In [83]:
orders_df = pd.read_csv(r'orders.csv')
orders_df.head()

   id  cust_id  order_date order_details  total_order_cost
0   1        3  04-03-2019          Coat               100
1   2        3  01-03-2019         Shoes                80
2   3        3  07-03-2019         Skirt                30
3   4        7  01-02-2019          Coat                25
4   5        7  10-03-2019         Shoes                80

In [84]:
hotelDf = pd.read_csv(r"hotel_bookings.csv")
hotelDf.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

 Exploring data

## 5. Exploring DataFrames

To display the first n columns of a dataframe 

`df.head()`

by default n=5 in pandas but we can pass any integer to it

In [85]:
df.head()

   first_name  last_name department  salary phone_number joining_date
id
1       Sarah   Mitchell         HR   95000     555-0101   15-03-2021
2     Michael       Chen         HR   88000     555-0102   01-06-2022
3       Emily  Rodriguez         HR   82500          NaN   20-09-2021
4       David       Park         HR   80000     555-0104   10-01-2023
5        Lisa   Thompson         HR   65000          NaN   05-04-2021

In [86]:
df.head(6)

   first_name  last_name department  salary phone_number joining_date
id
1       Sarah   Mitchell         HR   95000     555-0101   15-03-2021
2     Michael       Chen         HR   88000     555-0102   01-06-2022
3       Emily  Rodriguez         HR   82500          NaN   20-09-2021
4       David       Park         HR   80000     555-0104   10-01-2023
5        Lisa   Thompson         HR   65000          NaN   05-04-2021
6      Robert     Garcia         HR   58000     555-0106   15-11-2022

To display the last n columns of a dataframe 

`df.tail()`

by default n=5 in pandas but we can pass any integer to it

In [87]:
df.tail()

   first_name last_name   department  salary phone_number joining_date
id
47     Sandra    Parker        Admin   51000          NaN   01-02-2024
48       Paul   Collins  Engineering   88000     555-0309   10-03-2024
49   Kimberly   Stewart  Engineering   92000     555-0310   01-12-2021
50     Andrew   Sanchez        Sales   63000          NaN   20-01-2024
51      Betty    Morris      Finance   71000     555-0608   15-11-2021

## 6. Column types and missing values 

To understand the data type of each column and number of non-null values in each column 

`df.info()`

In [88]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51 entries, 1 to 51
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   first_name    51 non-null     str
 1   last_name     51 non-null     str
 2   department    51 non-null     str
 3   salary        51 non-null     int64
 4   phone_number  35 non-null     str
 5   joining_date  51 non-null     str
dtypes: int64(1), str(5)
memory usage: 2.5 KB

## 7. Knowing Data

### How many rows and columns 

basically the shape of the dataframe and it is an attribute and not a method

`df.shape`

In [89]:
df.shape

(51, 6)

### what are the columns 

basically the names of the columns in the dataframe and it is an attribute and not a method
 
`df.columns`

In [90]:
df.columns

Index(['first_name', 'last_name', 'department', 'salary', 'phone_number',
       'joining_date'],
      dtype='str')

### datatype of each column 

basically the column name and its datatype in the dataframe and it is an attribute and not a method


`df.dtypes`

In [91]:
df.dtypes

first_name        str
last_name         str
department        str
salary          int64
phone_number      str
joining_date      str
dtype: object

In [92]:
type(df.columns)

pandas.Index

#  Accessing Data

## 8.  Basic Selection 
### As DF 

The result of selecting one or more column from a dataframe


`df[['column_name']]`

or 

`df[['column_name1','column_name2','column_name3']]`

In [93]:
type(df[['department']])

pandas.DataFrame

In [94]:
df[['department']]

     department
id
1            HR
2            HR
3            HR
4            HR
5            HR
6            HR
7            HR
8            HR
9            HR
10        Admin
11        Admin
12        Admin
13        Admin
14        Admin
15        Admin
16        Admin
17  Engineering
18  Engineering
19  Engineering
20  Engineering
21  Engineering
22  Engineering
23  Engineering
24  Engineering
25    Marketing
26    Marketing
27    Marketing
28    Marketing
29    Marketing
30    Marketing
31        Sales
32        Sales
33        Sales
34        Sales
35        Sales
36        Sales
37        Sales
38      Finance
39      Finance
40      Finance
41      Finance
42      Finance
43      Finance
44      Finance
45      Finance
46           HR
47        Admin
48  Engineering
49  Engineering
50        Sales
51      Finance

In [95]:
type(df[['department','salary']])

pandas.DataFrame

In [96]:
df[['department','salary']]

     department  salary
id
1            HR   95000
2            HR   88000
3            HR   82500
4            HR   80000
5            HR   65000
6            HR   58000
7            HR   72000
8            HR   91000
9            HR   78000
10        Admin   87000
11        Admin   92000
12        Admin   81500
13        Admin   54000
14        Admin   62000
15        Admin   48000
16        Admin   85000
17  Engineering  125000
18  Engineering  118000
19  Engineering  105000
20  Engineering   98000
21  Engineering   75000
22  Engineering   68000
23  Engineering  130000
24  Engineering   95000
25    Marketing   72000
26    Marketing   85000
27    Marketing   68000
28    Marketing   91000
29    Marketing   95000
30    Marketing   78000
31        Sales   65000
32        Sales   71000
33        Sales   58000
34        Sales   82000
35        Sales   76000
36        Sales   69000
37        Sales   88000
38      Finance   92000
39      Finance   78000
40      Finance   85000
41      Finance   67000
42      Finance   73000
43      Finance   81000
44      Finance  105000
45      Finance   88000
46           HR   55000
47        Admin   51000
48  Engineering   88000
49  Engineering   92000
50        Sales   63000
51      Finance   71000

### As Series

The result of selecting only one column from a dataframe

`df['column_name']`

or 

`df.column_name`

In [97]:
type(df['department'])

pandas.Series

In [98]:
df['department']

id
1              HR
2              HR
3              HR
4              HR
5              HR
6              HR
7              HR
8              HR
9              HR
10          Admin
11          Admin
12          Admin
13          Admin
14          Admin
15          Admin
16          Admin
17    Engineering
18    Engineering
19    Engineering
20    Engineering
21    Engineering
22    Engineering
23    Engineering
24    Engineering
25      Marketing
26      Marketing
27      Marketing
28      Marketing
29      Marketing
30      Marketing
31          Sales
32          Sales
33          Sales
34          Sales
35          Sales
36          Sales
37          Sales
38        Finance
39        Finance
40        Finance
41        Finance
42        Finance
43        Finance
44        Finance
45        Finance
46             HR
47          Admin
48    Engineering
49    Engineering
50          Sales
51        Finance
Name: department, dtype: str

## 9. Advanced Selection

The another way of accessing data in a df is using 
1. **location by label** or `.loc[]`
2. **location by index** or `.iloc[]`


these both works good in series too where we'll pass only one arg instead of 2

### `.loc[]`

this takes **2 args**, 
1. row range 
2. column range 

to access the whole dataframe we use `df.loc[:,:]`

In [99]:
df.loc[:,:].head()

   first_name  last_name department  salary phone_number joining_date
id
1       Sarah   Mitchell         HR   95000     555-0101   15-03-2021
2     Michael       Chen         HR   88000     555-0102   01-06-2022
3       Emily  Rodriguez         HR   82500          NaN   20-09-2021
4       David       Park         HR   80000     555-0104   10-01-2023
5        Lisa   Thompson         HR   65000          NaN   05-04-2021

To access only a ranged data we provide the values to the rows and column 

here we need to **provide the label of the data not the index position** for both rows and columns


For rows the label by default assigns a unique integer value while importing so any column that we have isnot considered as an index by default 

To make the python consider a column as a row index we need to use the argument `index_col` and pass the name of the column to it. 

eg.: `rest_df = pd.read_csv("sf_restaurant_health_violations.csv", index_col="business_id")`

In [100]:
df.loc[1:5,'department':'phone_number']

   department  salary phone_number
id
1          HR   95000     555-0101
2          HR   88000     555-0102
3          HR   82500          NaN
4          HR   80000     555-0104
5          HR   65000          NaN

In [101]:
print(orders_df.loc[0])

id                           1
cust_id                      3
order_date          04-03-2019
order_details             Coat
total_order_cost           100
Name: 0, dtype: object

In [102]:
rest_df.loc[5800:1991,:]

,business_name,business_address,business_city,business_state,business_postal_code,business_latitude,business_longitude,business_location,business_phone_number,inspection_id,inspection_date,inspection_score,inspection_type,violation_id,violation_description,risk_category
business_id,,,,,,,,,,,,,,,,
5800,John Chin Elementary School,350 Broadway St,San Francisco,CA,94133.0,37.80,-122.40,"{'longitude': '-122.403154', 'needs_recoding':...",NaN,5800_20171017,17-10-2017,98.0,Routine - Unscheduled,5800_20171017_103149,Wiping cloths not clean or properly stored or ...,Low Risk
64236,Sutter Pub and Restaurant,700 Sutter St,San Francisco,CA,94102.0,37.79,-122.41,"{'longitude': '-122.41188', 'needs_recoding': ...",NaN,64236_20170725,25-07-2017,88.0,Routine - Unscheduled,64236_20170725_103133,Foods not protected from contamination,Moderate Risk
1991,SRI THAI CUISINE,4621 LINCOLN Way,San Francisco,CA,94122.0,37.76,-122.51,"{'longitude': '-122.507779', 'needs_recoding':...",NaN,1991_20171129,29-11-2017,86.0,Routine - Unscheduled,1991_20171129_103139,Improper food storage,Low Risk

We can also pass the list of values into them so that the order of data can be of our choise

In [103]:
df.loc[[1,4,2,3,5],['salary','department','phone_number']]

    salary department phone_number
id
1    95000         HR     555-0101
4    80000         HR     555-0104
2    88000         HR     555-0102
3    82500         HR          NaN
5    65000         HR          NaN

In [104]:
orders_df.loc[0]

id                           1
cust_id                      3
order_date          04-03-2019
order_details             Coat
total_order_cost           100
Name: 0, dtype: object

In [105]:
type(orders_df.loc[0])

pandas.Series

### `.iloc[]`
This is handy when we dont know the label of the column or rows and want to access them by their index position

In [106]:
# Index(['first_name', 'last_name', 'department', 'salary', 'phone_number','joining_date', 'name_len'],
#       dtype='str')

df.iloc[[1,2,4,3,5],[0,5,3]]

   first_name joining_date  salary
id
2     Michael   01-06-2022   88000
3       Emily   20-09-2021   82500
5        Lisa   05-04-2021   65000
4       David   10-01-2023   80000
6      Robert   15-11-2022   58000

We get index error when we try to use index that are not in the range of the data

In [107]:
# df.iloc[[1,2,4,3,5],[0,5,3,7]]

# ---------------------------------------------------------------------------
# IndexError                                Traceback (most recent call last)
# Cell In[144], line 1
# ----> 1 df.iloc[[1,2,4,3,5],[0,5,3,7]]

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\indexing.py:1200, in _LocationIndexer.__getitem__(self, key)
#    1198     if self._is_scalar_access(key):
#    1199         return self.obj._get_value(*key, takeable=self._takeable)
# -> 1200     return self._getitem_tuple(key)
#    1201 else:
#    1202     # we by definition only have the 0th axis
#    1203     axis = self.axis or 0

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\indexing.py:1711, in _iLocIndexer._getitem_tuple(self, tup)
#    1710 def _getitem_tuple(self, tup: tuple):
# -> 1711     tup = self._validate_tuple_indexer(tup)
#    1712     with suppress(IndexingError):
#    1713         return self._getitem_lowerdim(tup)

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\indexing.py:993, in _LocationIndexer._validate_tuple_indexer(self, key)
#     991 for i, k in enumerate(key):
#     992     try:
# --> 993         self._validate_key(k, i)
#     994     except ValueError as err:
#     995         raise ValueError(
# ...
# -> 1633             raise IndexError("positional indexers are out-of-bounds")
#    1634 else:
#    1635     raise ValueError(f"Can only index by location with a [{self._valid_types}]")

# IndexError: positional indexers are out-of-bounds
# Output is truncated. View as a scrollable element or open in a text editor. Adjust cell output settings...

We can step the values of rows or columns too using `iloc[]` by using `start:stop:step` just like in `range()`

In [108]:
# df.columns.to_series(index=[x for x in range(0,len(df.columns))])
# df.columns.to_series().reset_index(drop=True)
pd.Series(df.columns)

0      first_name
1       last_name
2      department
3          salary
4    phone_number
5    joining_date
dtype: str

In [109]:
df.iloc[0:20:3,::2]

   first_name   department phone_number
id
1       Sarah           HR     555-0101
4       David           HR     555-0104
7    Jennifer           HR     555-0107
10      James        Admin     555-0201
13   Michelle        Admin     555-0204
16    Matthew        Admin     555-0207
19      Brian  Engineering          NaN

### Selecting Columns using loc-iloc

we can use these functions to select the columns too

In [110]:
df[['department','salary','first_name']].head()

   department  salary first_name
id
1          HR   95000      Sarah
2          HR   88000    Michael
3          HR   82500      Emily
4          HR   80000      David
5          HR   65000       Lisa

In [111]:
df.loc[:,['department','salary','first_name']].head()

   department  salary first_name
id
1          HR   95000      Sarah
2          HR   88000    Michael
3          HR   82500      Emily
4          HR   80000      David
5          HR   65000       Lisa

# Splitting columns based on type

when we want to split the df based on its type we use `.select_dtypes(include=['data_type'])`

`df.select_dtypes(include=['data_type'])`

We can also extract the column name individually and then do 
```
cat_col = [col for col in df.columns if df[col].dtype == 'str']
cat_df  = df[cat_col]
cat_df.head()

```

In [112]:
num_df = df.select_dtypes(include=['int'])
num_df.head()

    salary
id
1    95000
2    88000
3    82500
4    80000
5    65000

In [113]:
# cat_df = df.select_dtypes(include=['str'])
# cat_df.head()

# Statistical summary 
## numerical datatype
`df.describe()`

### correlation

to find the correlation between the numerical columns we can use the `.corr()` on the df. 

but if the df has numeric + categorical/ text data we get error 

So we need use arrgument **numeric_only** and set is as `True`

In [114]:
# df.corr()

# ---------------------------------------------------------------------------
# ValueError                                Traceback (most recent call last)
# Cell In[181], line 1
# ----> 1 df.corr()

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\frame.py:13133, in DataFrame.corr(self, method, min_periods, numeric_only)
#   13129         """  # noqa: E501
#   13130         data = self._get_numeric_data() if numeric_only else self
#   13131         cols = data.columns
#   13132         idx = cols.copy()
# > 13133         mat = data.to_numpy(dtype=float, na_value=np.nan, copy=False)
#   13134 
#   13135         if method == "pearson":
#   13136             correl = libalgos.nancorr(mat, minp=min_periods)

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\frame.py:2081, in DataFrame.to_numpy(self, dtype, copy, na_value)
#    2077                [2, 4.5, Timestamp('2000-01-02 00:00:00')]], dtype=object)
#    2078         """
#    2079         if dtype is not None:
#    2080             dtype = np.dtype(dtype)
# -> 2081         result = self._mgr.as_array(dtype=dtype, copy=copy, na_value=na_value)
#    2082         if result.dtype is not dtype:
#    2083             result = np.asarray(result, dtype=dtype)
#    2084 
# ...
# --> 589 result = np.asarray(result, dtype=dtype)
#     591 if copy and result is self._ndarray:
#     592     result = result.copy()

# ValueError: could not convert string to float: 'Sarah'

In [115]:
df.corr(numeric_only=True)

        salary
salary     1.0

## all datatype 
`df.describe(include='all')`

In [116]:
df.describe(include='all')

,first_name,last_name,department,salary,phone_number,joining_date
count,51,51,51,51.000000,35,51
unique,51,50,6,NaN,35,51
top,Sarah,Mitchell,HR,NaN,555-0101,15-03-2021
freq,1,2,10,NaN,1,1
mean,NaN,NaN,NaN,80784.313725,NaN,NaN
std,NaN,NaN,NaN,17561.963131,NaN,NaN
min,NaN,NaN,NaN,48000.000000,NaN,NaN
25%,NaN,NaN,NaN,68500.000000,NaN,NaN
50%,NaN,NaN,NaN,81000.000000,NaN,NaN
75%,NaN,NaN,NaN,91000.000000,NaN,NaN
max,NaN,NaN,NaN,130000.000000,NaN,NaN

# Renaming 
## Instance column rename
`df.rename(columns={"actual name" : "new name"})`

Note:- this doesn't update the dataframe but only the instance. To save the updated instance, we can refer that to a variable.

In [117]:
renamed_df = df.rename(columns={
    "first_name" : "First Name",
    "last_name" : "Last Name",
    "phone_number" : "phone number".title(),
    "joining_date" : "joining date".title()
})
renamed_df.head()

   First Name  Last Name department  salary Phone Number Joining Date
id
1       Sarah   Mitchell         HR   95000     555-0101   15-03-2021
2     Michael       Chen         HR   88000     555-0102   01-06-2022
3       Emily  Rodriguez         HR   82500          NaN   20-09-2021
4       David       Park         HR   80000     555-0104   10-01-2023
5        Lisa   Thompson         HR   65000          NaN   05-04-2021

In [118]:
df.rename(columns={
    "first_name" : "First Name",
    "last_name" : "Last Name",
    "phone_number" : "phone number".title(),
    "joining_date" : "joining date".title()
}).head()

   First Name  Last Name department  salary Phone Number Joining Date
id
1       Sarah   Mitchell         HR   95000     555-0101   15-03-2021
2     Michael       Chen         HR   88000     555-0102   01-06-2022
3       Emily  Rodriguez         HR   82500          NaN   20-09-2021
4       David       Park         HR   80000     555-0104   10-01-2023
5        Lisa   Thompson         HR   65000          NaN   05-04-2021

In [119]:
df.head()

   first_name  last_name department  salary phone_number joining_date
id
1       Sarah   Mitchell         HR   95000     555-0101   15-03-2021
2     Michael       Chen         HR   88000     555-0102   01-06-2022
3       Emily  Rodriguez         HR   82500          NaN   20-09-2021
4       David       Park         HR   80000     555-0104   10-01-2023
5        Lisa   Thompson         HR   65000          NaN   05-04-2021

## Permanent column rename
`df.rename(columns={"actual name" : "new name"},inplace=True)`

Note:- this update the dataframe and store in the same.

In [120]:
df2 = df.copy(deep=True)
df2.head()

   first_name  last_name department  salary phone_number joining_date
id
1       Sarah   Mitchell         HR   95000     555-0101   15-03-2021
2     Michael       Chen         HR   88000     555-0102   01-06-2022
3       Emily  Rodriguez         HR   82500          NaN   20-09-2021
4       David       Park         HR   80000     555-0104   10-01-2023
5        Lisa   Thompson         HR   65000          NaN   05-04-2021

In [121]:
df2.rename(columns={
    "first_name" : "First Name",
    "last_name" : "Last Name",
    "phone_number" : "phone number".title(),
    "joining_date" : "joining date".title()
},inplace=True)
df2.head()

   First Name  Last Name department  salary Phone Number Joining Date
id
1       Sarah   Mitchell         HR   95000     555-0101   15-03-2021
2     Michael       Chen         HR   88000     555-0102   01-06-2022
3       Emily  Rodriguez         HR   82500          NaN   20-09-2021
4       David       Park         HR   80000     555-0104   10-01-2023
5        Lisa   Thompson         HR   65000          NaN   05-04-2021

# Creating New Columns
## Simple column
New column can be created using the new name for a column that is not present already in the dataframe.
`df['new_column_name'] = df['existing_column_name']`

In [122]:
df2['new_salary']= df2['salary']
df2.head()

,First Name,Last Name,department,salary,Phone Number,Joining Date,new_salary
id,,,,,,,
1,Sarah,Mitchell,HR,95000,555-0101,15-03-2021,95000
2,Michael,Chen,HR,88000,555-0102,01-06-2022,88000
3,Emily,Rodriguez,HR,82500,NaN,20-09-2021,82500
4,David,Park,HR,80000,555-0104,10-01-2023,80000
5,Lisa,Thompson,HR,65000,NaN,05-04-2021,65000

## Calculated column
any arithmetic or logical operation can  also be performed columnwise

In [123]:
df2['new_salary_monthly']= df2['salary']/12.0
df2.head()

,First Name,Last Name,department,salary,Phone Number,Joining Date,new_salary,new_salary_monthly
id,,,,,,,,
1,Sarah,Mitchell,HR,95000,555-0101,15-03-2021,95000,7916.666667
2,Michael,Chen,HR,88000,555-0102,01-06-2022,88000,7333.333333
3,Emily,Rodriguez,HR,82500,NaN,20-09-2021,82500,6875.000000
4,David,Park,HR,80000,555-0104,10-01-2023,80000,6666.666667
5,Lisa,Thompson,HR,65000,NaN,05-04-2021,65000,5416.666667

# Dropping a data

we can drop the duplicates but also we can drop a certain column or rows based on the conditions

1. drop columns 
2. drop rows 

here the `axis` is very important

## Axis

axis = 0 → move DOWN (↓)
axis = 1 → move ACROSS (→)

axis = 0 acts on the rows, so this means we get the result for each column. Hence axis = 0 movement along rows and column result 
axis = 1 acts on the columns, so this means we get the result for each row. Hence axis = 1 column movement along columns and row result

when we want to delete a column we are not moving up to down rather we remove from the set of values in the row and vice versa for removing rows. 

When we are doing operations on rows to get the result of a column then we move top to bottom 

| Axis | Movement | What is involved | Calculation result | Deletion effect |
|------|--------|-----------------|------------------|----------------|
| **axis = 0** | ↓ Down | Rows | Column-wise result | Removes **rows** |
| **axis = 1** | → Across | Columns | Row-wise result | Removes **columns** |

## Column Dropping

In [124]:
# dropping a column 
df2.drop("Last Name",axis=1,inplace=True)
df2.head()

,First Name,department,salary,Phone Number,Joining Date,new_salary,new_salary_monthly
id,,,,,,,
1,Sarah,HR,95000,555-0101,15-03-2021,95000,7916.666667
2,Michael,HR,88000,555-0102,01-06-2022,88000,7333.333333
3,Emily,HR,82500,NaN,20-09-2021,82500,6875.000000
4,David,HR,80000,555-0104,10-01-2023,80000,6666.666667
5,Lisa,HR,65000,NaN,05-04-2021,65000,5416.666667

## Row Dropping 

We donot drop a row in general, we either use a condition for this to filter and drop, but we can drop in general too
1. dropping a single row  <- options arg `index`
2. dropping a list of rows <- needed arg `index`
3. dropping based on the conditon <- pass the condition directly and get the dataframe or series and use `.index` to retrive the index values of those that passes the condition and then drop them

In [125]:
# droping a single row 
df2.drop(2,axis=0,inplace=True)
df2.head()

,First Name,department,salary,Phone Number,Joining Date,new_salary,new_salary_monthly
id,,,,,,,
1,Sarah,HR,95000,555-0101,15-03-2021,95000,7916.666667
3,Emily,HR,82500,NaN,20-09-2021,82500,6875.000000
4,David,HR,80000,555-0104,10-01-2023,80000,6666.666667
5,Lisa,HR,65000,NaN,05-04-2021,65000,5416.666667
6,Robert,HR,58000,555-0106,15-11-2022,58000,4833.333333

In [126]:
# droping a list of rows 
df2.drop(index=[3,6],axis=0,inplace=True)
df2.head()

,First Name,department,salary,Phone Number,Joining Date,new_salary,new_salary_monthly
id,,,,,,,
1,Sarah,HR,95000,555-0101,15-03-2021,95000,7916.666667
4,David,HR,80000,555-0104,10-01-2023,80000,6666.666667
5,Lisa,HR,65000,NaN,05-04-2021,65000,5416.666667
7,Jennifer,HR,72000,555-0107,20-05-2023,72000,6000.000000
8,William,HR,91000,555-0108,12-08-2019,91000,7583.333333

In [127]:
# droping rows based on condition
print(df2.shape[0])
df2.drop((df2[df2.salary > 70000]).index, inplace=True)
print(df2.shape[0])

48
13

# Copy
## Refer the og
when we want to refer the original dataframe with another name 
`df1 = df`

Note:- Any change in df1 affects df too

In [128]:
og_df = pd.read_csv(r'techcorp_workforce.csv')
og_df.head()

   id first_name  last_name department  salary phone_number joining_date
0   1      Sarah   Mitchell         HR   95000     555-0101   15-03-2021
1   2    Michael       Chen         HR   88000     555-0102   01-06-2022
2   3      Emily  Rodriguez         HR   82500          NaN   20-09-2021
3   4      David       Park         HR   80000     555-0104   10-01-2023
4   5       Lisa   Thompson         HR   65000          NaN   05-04-2021

In [129]:
copy_df = og_df
copy_df.head()

   id first_name  last_name department  salary phone_number joining_date
0   1      Sarah   Mitchell         HR   95000     555-0101   15-03-2021
1   2    Michael       Chen         HR   88000     555-0102   01-06-2022
2   3      Emily  Rodriguez         HR   82500          NaN   20-09-2021
3   4      David       Park         HR   80000     555-0104   10-01-2023
4   5       Lisa   Thompson         HR   65000          NaN   05-04-2021

In [130]:
copy_df.rename(columns={
    "first_name":"first name".title()
},
inplace=True)
copy_df.head()

   id First Name  last_name department  salary phone_number joining_date
0   1      Sarah   Mitchell         HR   95000     555-0101   15-03-2021
1   2    Michael       Chen         HR   88000     555-0102   01-06-2022
2   3      Emily  Rodriguez         HR   82500          NaN   20-09-2021
3   4      David       Park         HR   80000     555-0104   10-01-2023
4   5       Lisa   Thompson         HR   65000          NaN   05-04-2021

In [131]:
og_df.head()

   id First Name  last_name department  salary phone_number joining_date
0   1      Sarah   Mitchell         HR   95000     555-0101   15-03-2021
1   2    Michael       Chen         HR   88000     555-0102   01-06-2022
2   3      Emily  Rodriguez         HR   82500          NaN   20-09-2021
3   4      David       Park         HR   80000     555-0104   10-01-2023
4   5       Lisa   Thompson         HR   65000          NaN   05-04-2021

## Shallow copy 
Modifying the structure (adding/deleting columns or changing cell values via .loc) in df2 will not affect df.    

But by default in standard Python, a shallow copy can sometimes still mutate nested Python objects (like lists or dicts stored inside cells) in the original DataFrame.  
  
This is the standard way to safely duplicate a DataFrame for normal data analysis steps without worrying about the SettingWithCopyWarning

`df2 = df.copy()`

In [132]:
og_df = pd.read_csv(r'techcorp_workforce.csv')
og_df.head()

   id first_name  last_name department  salary phone_number joining_date
0   1      Sarah   Mitchell         HR   95000     555-0101   15-03-2021
1   2    Michael       Chen         HR   88000     555-0102   01-06-2022
2   3      Emily  Rodriguez         HR   82500          NaN   20-09-2021
3   4      David       Park         HR   80000     555-0104   10-01-2023
4   5       Lisa   Thompson         HR   65000          NaN   05-04-2021

In [133]:
copy_df2 = og_df.copy()
copy_df.head()

   id First Name  last_name department  salary phone_number joining_date
0   1      Sarah   Mitchell         HR   95000     555-0101   15-03-2021
1   2    Michael       Chen         HR   88000     555-0102   01-06-2022
2   3      Emily  Rodriguez         HR   82500          NaN   20-09-2021
3   4      David       Park         HR   80000     555-0104   10-01-2023
4   5       Lisa   Thompson         HR   65000          NaN   05-04-2021

In [134]:
copy_df.rename(columns={
    "first_name":"first name".title()
},
inplace=True)
copy_df.head()

   id First Name  last_name department  salary phone_number joining_date
0   1      Sarah   Mitchell         HR   95000     555-0101   15-03-2021
1   2    Michael       Chen         HR   88000     555-0102   01-06-2022
2   3      Emily  Rodriguez         HR   82500          NaN   20-09-2021
3   4      David       Park         HR   80000     555-0104   10-01-2023
4   5       Lisa   Thompson         HR   65000          NaN   05-04-2021

In [135]:
og_df.head()

   id first_name  last_name department  salary phone_number joining_date
0   1      Sarah   Mitchell         HR   95000     555-0101   15-03-2021
1   2    Michael       Chen         HR   88000     555-0102   01-06-2022
2   3      Emily  Rodriguez         HR   82500          NaN   20-09-2021
3   4      David       Park         HR   80000     555-0104   10-01-2023
4   5       Lisa   Thompson         HR   65000          NaN   05-04-2021

## Deep copy 
Completely isolation between both the dataframes

`df3 = df.copy(deep=True)`

in pandas by default `deep=True`

# Dupliactes
## Remove Duplicates    
Removes the rows with the duplicate values for the given column

`df[['column_name']].drop_duplicates()` 

This works on a dataframe and return a dataframe


`df.drop_duplicates()` takes a complete row and check if the whole row is duplicated anywhere and then drop the rows that are duplicates.   
All the columns of this row is compared with all the columns of the another row.

In [136]:
orders_df.drop_duplicates()

    id  cust_id  order_date order_details  total_order_cost
0    1        3  04-03-2019          Coat               100
1    2        3  01-03-2019         Shoes                80
2    3        3  07-03-2019         Skirt                30
3    4        7  01-02-2019          Coat                25
4    5        7  10-03-2019         Shoes                80
5    6       15  01-02-2019         Boats               100
6    7       15  11-01-2019        Shirts                60
7    8       15  11-03-2019       Slipper                20
8    9       15  01-03-2019         Jeans                80
9   10       15  09-03-2019        Shirts                50
10  11        5  01-02-2019         Shoes                80
11  12       12  11-01-2019        Shirts                60
12  13       12  11-03-2019       Slipper                20
13  14        4  01-02-2019         Shoes                80
14  15        4  11-01-2019        Shirts                60
15  16        3  19-04-2019        Shirts                50
16  17        7  19-04-2019          Suit               150
17  18       15  19-04-2019         Skirt                30
18  19       15  20-04-2019       Dresses               200
19  20       12  11-01-2019          Coat               125
20  21        7  01-04-2019          Suit                50
21  22        7  02-04-2019         Skirt                30
22  23        7  03-04-2019       Dresses                50
23  24        7  04-04-2019          Coat                25
24  25        7  19-04-2019          Coat               125
25  26        3  20-04-2019        Gloves                20
26  27        3  21-04-2019           Tie                25
27  28        3  22-04-2019           Cap                15
28  29        3  23-04-2019        Jacket               120
29  30        1  19-04-2019        Jacket               150
30  31        1  19-04-2019         Shoes               125

In [137]:
odf1= orders_df.copy(deep=True)
unique_details_df = odf1[["order_details"]].drop_duplicates()
type(unique_details_df)

pandas.DataFrame

## Multiple column names 
When multiple columns passed, it removes rows where the entire combination is duplicated:

In [138]:
odf1[['order_details','cust_id']].drop_duplicates().head()

  order_details  cust_id
0          Coat        3
1         Shoes        3
2         Skirt        3
3          Coat        7
4         Shoes        7

## Single column
When a single column needs to be worked on we can use 

`df['column_name'].unique()`

this returns a series of unique values.

In [139]:
odf1['order_details'].unique()

<StringArray>
[   'Coat',   'Shoes',   'Skirt',   'Boats',  'Shirts', 'Slipper',   'Jeans',
    'Suit', 'Dresses',  'Gloves',     'Tie',     'Cap',  'Jacket']
Length: 13, dtype: str

In [140]:
# odf1.unique()

# ---------------------------------------------------------------------------
# AttributeError                            Traceback (most recent call last)
# Cell In[33], line 1
# ----> 1 odf1.unique()

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\generic.py:6206, in NDFrame.__getattr__(self, name)
#    6202             and name not in self._accessors
#    6203             and self._info_axis._can_hold_identifiers_and_holds_name(name)
#    6204         ):
#    6205             return self[name]
# -> 6206         return object.__getattribute__(self, name)

# AttributeError: 'DataFrame' object has no attribute 'unique'

### Note: 
Working on **DATA FRAME** use `drop_duplicates()`

Working on **SERIES** use `unique()`

# Filtering Rows 
Get the rows that are having values satisfying a certain criteria.

This is called as boolean indexing.

`df[df["column_name"] condition "criteria"]`


The expression inside the bracket produces a Series of True/ False values 

Conditions can be `== <= < >= > !=`

In [141]:
df[df["department"] == "HR"]

   first_name  last_name department  salary phone_number joining_date
id
1       Sarah   Mitchell         HR   95000     555-0101   15-03-2021
2     Michael       Chen         HR   88000     555-0102   01-06-2022
3       Emily  Rodriguez         HR   82500          NaN   20-09-2021
4       David       Park         HR   80000     555-0104   10-01-2023
5        Lisa   Thompson         HR   65000          NaN   05-04-2021
6      Robert     Garcia         HR   58000     555-0106   15-11-2022
7    Jennifer        Lee         HR   72000     555-0107   20-05-2023
8     William      Davis         HR   91000     555-0108   12-08-2019
9    Patricia     Wilson         HR   78000          NaN   28-02-2018
46       Mark       Diaz         HR   55000     555-0109   15-01-2024

### Internal Working

`df["department"] == "HR"` <- produces a `series` of `True/ False `

This `Series` of `True` is compared with each row of the `dataframe` <- `df[boolean_series]`

The true rows are displayed.

In [142]:
df[df[["department"]] == "HR"]

   first_name last_name department  salary phone_number joining_date
id
1         NaN       NaN         HR     NaN          NaN          NaN
2         NaN       NaN         HR     NaN          NaN          NaN
3         NaN       NaN         HR     NaN          NaN          NaN
4         NaN       NaN         HR     NaN          NaN          NaN
5         NaN       NaN         HR     NaN          NaN          NaN
6         NaN       NaN         HR     NaN          NaN          NaN
7         NaN       NaN         HR     NaN          NaN          NaN
8         NaN       NaN         HR     NaN          NaN          NaN
9         NaN       NaN         HR     NaN          NaN          NaN
10        NaN       NaN        NaN     NaN          NaN          NaN
11        NaN       NaN        NaN     NaN          NaN          NaN
12        NaN       NaN        NaN     NaN          NaN          NaN
13        NaN       NaN        NaN     NaN          NaN          NaN
14        NaN       NaN        NaN     NaN          NaN          NaN
15        NaN       NaN        NaN     NaN          NaN          NaN
16        NaN       NaN        NaN     NaN          NaN          NaN
17        NaN       NaN        NaN     NaN          NaN          NaN
18        NaN       NaN        NaN     NaN          NaN          NaN
19        NaN       NaN        NaN     NaN          NaN          NaN
20        NaN       NaN        NaN     NaN          NaN          NaN
21        NaN       NaN        NaN     NaN          NaN          NaN
22        NaN       NaN        NaN     NaN          NaN          NaN
23        NaN       NaN        NaN     NaN          NaN          NaN
24        NaN       NaN        NaN     NaN          NaN          NaN
25        NaN       NaN        NaN     NaN          NaN          NaN
26        NaN       NaN        NaN     NaN          NaN          NaN
27        NaN       NaN        NaN     NaN          NaN          NaN
28        NaN       NaN        NaN     NaN          NaN          NaN
29        NaN       NaN        NaN     NaN          NaN          NaN
30        NaN       NaN        NaN     NaN          NaN          NaN
31        NaN       NaN        NaN     NaN          NaN          NaN
32        NaN       NaN        NaN     NaN          NaN          NaN
33        NaN       NaN        NaN     NaN          NaN          NaN
34        NaN       NaN        NaN     NaN          NaN          NaN
35        NaN       NaN        NaN     NaN          NaN          NaN
36        NaN       NaN        NaN     NaN          NaN          NaN
37        NaN       NaN        NaN     NaN          NaN          NaN
38        NaN       NaN        NaN     NaN          NaN          NaN
39        NaN       NaN        NaN     NaN          NaN          NaN
40        NaN       NaN        NaN     NaN          NaN          NaN
41        NaN       NaN        NaN     NaN          NaN          NaN
42        NaN       NaN        NaN     NaN          NaN          NaN
43        NaN       NaN        NaN     NaN          NaN          NaN
44        NaN       NaN        NaN     NaN          NaN          NaN
45        NaN       NaN        NaN     NaN          NaN          NaN
46        NaN       NaN         HR     NaN          NaN          NaN
47        NaN       NaN        NaN     NaN          NaN          NaN
48        NaN       NaN        NaN     NaN          NaN          NaN
49        NaN       NaN        NaN     NaN          NaN          NaN
50        NaN       NaN        NaN     NaN          NaN          NaN
51        NaN       NaN        NaN     NaN          NaN          NaN

In [143]:
df[["department"]] == "HR"

    department
id
1         True
2         True
3         True
4         True
5         True
6         True
7         True
8         True
9         True
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
30       False
31       False
32       False
33       False
34       False
35       False
36       False
37       False
38       False
39       False
40       False
41       False
42       False
43       False
44       False
45       False
46        True
47       False
48       False
49       False
50       False
51       False

### Internal Working

`df[df[["department"]] == "HR"]` <- produces a `dataframe` of `True/ False `

This `dataframe` creates a masking effect on the original dataframe where   
`if mask[i, j] == True:`     
`    keep value`        
`else:`          
`    set NaN`         

so pandas aligns by 
1. row index 
2. column names 

when column name matches between the 2 df (the masking and the original df) then that column gets the value. 

When the column name doesn't match `nan` is filled

In [144]:
odf1[df[["department"]]=="HR"]

    id  cust_id order_date order_details  total_order_cost
0  NaN      NaN        NaN           NaN               NaN
1  NaN      NaN        NaN           NaN               NaN
2  NaN      NaN        NaN           NaN               NaN
3  NaN      NaN        NaN           NaN               NaN
4  NaN      NaN        NaN           NaN               NaN
5  NaN      NaN        NaN           NaN               NaN
6  NaN      NaN        NaN           NaN               NaN
7  NaN      NaN        NaN           NaN               NaN
8  NaN      NaN        NaN           NaN               NaN
9  NaN      NaN        NaN           NaN               NaN
10 NaN      NaN        NaN           NaN               NaN
11 NaN      NaN        NaN           NaN               NaN
12 NaN      NaN        NaN           NaN               NaN
13 NaN      NaN        NaN           NaN               NaN
14 NaN      NaN        NaN           NaN               NaN
15 NaN      NaN        NaN           NaN               NaN
16 NaN      NaN        NaN           NaN               NaN
17 NaN      NaN        NaN           NaN               NaN
18 NaN      NaN        NaN           NaN               NaN
19 NaN      NaN        NaN           NaN               NaN
20 NaN      NaN        NaN           NaN               NaN
21 NaN      NaN        NaN           NaN               NaN
22 NaN      NaN        NaN           NaN               NaN
23 NaN      NaN        NaN           NaN               NaN
24 NaN      NaN        NaN           NaN               NaN
25 NaN      NaN        NaN           NaN               NaN
26 NaN      NaN        NaN           NaN               NaN
27 NaN      NaN        NaN           NaN               NaN
28 NaN      NaN        NaN           NaN               NaN
29 NaN      NaN        NaN           NaN               NaN
30 NaN      NaN        NaN           NaN               NaN

## String matching 
we an use `.str` to match the strings that condition. 
 

 NOTE:-

 `.str` can be used only on the **Dataframe**

In [145]:
df[df["first_name"].str.startswith("Jo")]

   first_name last_name department  salary phone_number joining_date
id
40   Jonathan    Carter    Finance   85000     555-0603   20-10-2021

In [146]:
# df[df[["first_name"]].str.endswith("th")]

# ---------------------------------------------------------------------------
# AttributeError                            Traceback (most recent call last)
# Cell In[153], line 1
# ----> 1 df[df[["first_name"]].str.endswith("th")]

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\generic.py:6206, in NDFrame.__getattr__(self, name)
#    6202             and name not in self._accessors
#    6203             and self._info_axis._can_hold_identifiers_and_holds_name(name)
#    6204         ):
#    6205             return self[name]
# -> 6206         return object.__getattribute__(self, name)

# AttributeError: 'DataFrame' object has no attribute 'str'

In [147]:
df[df["first_name"].str.endswith("th")]

   first_name last_name department  salary phone_number joining_date
id
29    Kenneth    Torres  Marketing   95000     555-0405   10-03-2018

### Partial string matchings

`.contains` workswith regex patterns too.

In [148]:
df[df["first_name"].str.contains("ha")]

   first_name last_name   department  salary phone_number joining_date
id
2     Michael      Chen           HR   88000     555-0102   01-06-2022
20  Stephanie     Clark  Engineering   98000     555-0304   10-03-2023
28     Sharon     Scott    Marketing   91000     555-0404   01-10-2022
40   Jonathan    Carter      Finance   85000     555-0603   20-10-2021

In [149]:
# Case-insensitive
df[df["first_name"].str.lower().str.contains("shar")]

   first_name last_name department  salary phone_number joining_date
id
28     Sharon     Scott  Marketing   91000     555-0404   01-10-2022

# Multiple conditions

Instead of using just a single boolean filter, we can use multiple filters to filter the rows.

we use `& , |, ~` instead of `and, or, not`

This is because the former is an elementwise operator while the later is the scalar operator. 

elementwise operator compares each rows while scalar  operator compares the whole table. 

For filtering we need to compare each rows rather than the whole table.

## And conditions

In [150]:
odf1[
    (odf1["order_details"] == "Coat") &
    (odf1["total_order_cost"] > 100)
]

    id  cust_id  order_date order_details  total_order_cost
19  20       12  11-01-2019          Coat               125
24  25        7  19-04-2019          Coat               125

## Or conditions

In [151]:
df[
    (df.department == "HR") |
    (df.department == "Admin")
    ]

     first_name  last_name department  salary phone_number joining_date
id
1         Sarah   Mitchell         HR   95000     555-0101   15-03-2021
2       Michael       Chen         HR   88000     555-0102   01-06-2022
3         Emily  Rodriguez         HR   82500          NaN   20-09-2021
4         David       Park         HR   80000     555-0104   10-01-2023
5          Lisa   Thompson         HR   65000          NaN   05-04-2021
6        Robert     Garcia         HR   58000     555-0106   15-11-2022
7      Jennifer        Lee         HR   72000     555-0107   20-05-2023
8       William      Davis         HR   91000     555-0108   12-08-2019
9      Patricia     Wilson         HR   78000          NaN   28-02-2018
10        James   Martinez      Admin   87000     555-0201   01-07-2021
11       Amanda     Taylor      Admin   92000          NaN   15-03-2022
12  Christopher   Anderson      Admin   81500     555-0203   22-08-2023
13     Michelle     Thomas      Admin   54000     555-0204   30-11-2021
14       Daniel    Jackson      Admin   62000     555-0205   10-09-2022
15      Jessica      White      Admin   48000          NaN   14-02-2023
16      Matthew     Harris      Admin   85000     555-0207   20-05-2017
46         Mark       Diaz         HR   55000     555-0109   15-01-2024
47       Sandra     Parker      Admin   51000          NaN   01-02-2024

## Or on same column 
We can use `.isin()` for multiple or conditions

In [152]:
df[df["department"].isin(["HR", "Admin"])]

     first_name  last_name department  salary phone_number joining_date
id
1         Sarah   Mitchell         HR   95000     555-0101   15-03-2021
2       Michael       Chen         HR   88000     555-0102   01-06-2022
3         Emily  Rodriguez         HR   82500          NaN   20-09-2021
4         David       Park         HR   80000     555-0104   10-01-2023
5          Lisa   Thompson         HR   65000          NaN   05-04-2021
6        Robert     Garcia         HR   58000     555-0106   15-11-2022
7      Jennifer        Lee         HR   72000     555-0107   20-05-2023
8       William      Davis         HR   91000     555-0108   12-08-2019
9      Patricia     Wilson         HR   78000          NaN   28-02-2018
10        James   Martinez      Admin   87000     555-0201   01-07-2021
11       Amanda     Taylor      Admin   92000          NaN   15-03-2022
12  Christopher   Anderson      Admin   81500     555-0203   22-08-2023
13     Michelle     Thomas      Admin   54000     555-0204   30-11-2021
14       Daniel    Jackson      Admin   62000     555-0205   10-09-2022
15      Jessica      White      Admin   48000          NaN   14-02-2023
16      Matthew     Harris      Admin   85000     555-0207   20-05-2017
46         Mark       Diaz         HR   55000     555-0109   15-01-2024
47       Sandra     Parker      Admin   51000          NaN   01-02-2024

In [153]:
df.shape[0]

51

## Filterning in between ranges

On the column we can use `.between(from, to)` range.

both the extremes are inclusive.

In [154]:
odf1[odf1["total_order_cost"].between(50, 200)]

    id  cust_id  order_date order_details  total_order_cost
0    1        3  04-03-2019          Coat               100
1    2        3  01-03-2019         Shoes                80
4    5        7  10-03-2019         Shoes                80
5    6       15  01-02-2019         Boats               100
6    7       15  11-01-2019        Shirts                60
8    9       15  01-03-2019         Jeans                80
9   10       15  09-03-2019        Shirts                50
10  11        5  01-02-2019         Shoes                80
11  12       12  11-01-2019        Shirts                60
13  14        4  01-02-2019         Shoes                80
14  15        4  11-01-2019        Shirts                60
15  16        3  19-04-2019        Shirts                50
16  17        7  19-04-2019          Suit               150
18  19       15  20-04-2019       Dresses               200
19  20       12  11-01-2019          Coat               125
20  21        7  01-04-2019          Suit                50
22  23        7  03-04-2019       Dresses                50
24  25        7  19-04-2019          Coat               125
28  29        3  23-04-2019        Jacket               120
29  30        1  19-04-2019        Jacket               150
30  31        1  19-04-2019         Shoes               125

In [155]:
odf1.loc[odf1["total_order_cost"].between(50, 200)].reset_index(drop=True)

    id  cust_id  order_date order_details  total_order_cost
0    1        3  04-03-2019          Coat               100
1    2        3  01-03-2019         Shoes                80
2    5        7  10-03-2019         Shoes                80
3    6       15  01-02-2019         Boats               100
4    7       15  11-01-2019        Shirts                60
5    9       15  01-03-2019         Jeans                80
6   10       15  09-03-2019        Shirts                50
7   11        5  01-02-2019         Shoes                80
8   12       12  11-01-2019        Shirts                60
9   14        4  01-02-2019         Shoes                80
10  15        4  11-01-2019        Shirts                60
11  16        3  19-04-2019        Shirts                50
12  17        7  19-04-2019          Suit               150
13  19       15  20-04-2019       Dresses               200
14  20       12  11-01-2019          Coat               125
15  21        7  01-04-2019          Suit                50
16  23        7  03-04-2019       Dresses                50
17  25        7  19-04-2019          Coat               125
18  29        3  23-04-2019        Jacket               120
19  30        1  19-04-2019        Jacket               150
20  31        1  19-04-2019         Shoes               125

In [156]:
odf1.loc[odf1["total_order_cost"].between(50, 200)]

    id  cust_id  order_date order_details  total_order_cost
0    1        3  04-03-2019          Coat               100
1    2        3  01-03-2019         Shoes                80
4    5        7  10-03-2019         Shoes                80
5    6       15  01-02-2019         Boats               100
6    7       15  11-01-2019        Shirts                60
8    9       15  01-03-2019         Jeans                80
9   10       15  09-03-2019        Shirts                50
10  11        5  01-02-2019         Shoes                80
11  12       12  11-01-2019        Shirts                60
13  14        4  01-02-2019         Shoes                80
14  15        4  11-01-2019        Shirts                60
15  16        3  19-04-2019        Shirts                50
16  17        7  19-04-2019          Suit               150
18  19       15  20-04-2019       Dresses               200
19  20       12  11-01-2019          Coat               125
20  21        7  01-04-2019          Suit                50
22  23        7  03-04-2019       Dresses                50
24  25        7  19-04-2019          Coat               125
28  29        3  23-04-2019        Jacket               120
29  30        1  19-04-2019        Jacket               150
30  31        1  19-04-2019         Shoes               125

In [157]:
odf1.loc[odf1["total_order_cost"].between(50, 200)].reset_index(drop=False)

    index  id  cust_id  order_date order_details  total_order_cost
0       0   1        3  04-03-2019          Coat               100
1       1   2        3  01-03-2019         Shoes                80
2       4   5        7  10-03-2019         Shoes                80
3       5   6       15  01-02-2019         Boats               100
4       6   7       15  11-01-2019        Shirts                60
5       8   9       15  01-03-2019         Jeans                80
6       9  10       15  09-03-2019        Shirts                50
7      10  11        5  01-02-2019         Shoes                80
8      11  12       12  11-01-2019        Shirts                60
9      13  14        4  01-02-2019         Shoes                80
10     14  15        4  11-01-2019        Shirts                60
11     15  16        3  19-04-2019        Shirts                50
12     16  17        7  19-04-2019          Suit               150
13     18  19       15  20-04-2019       Dresses               200
14     19  20       12  11-01-2019          Coat               125
15     20  21        7  01-04-2019          Suit                50
16     22  23        7  03-04-2019       Dresses                50
17     24  25        7  19-04-2019          Coat               125
18     28  29        3  23-04-2019        Jacket               120
19     29  30        1  19-04-2019        Jacket               150
20     30  31        1  19-04-2019         Shoes               125

In [158]:
odf1['order_date'] = pd.to_datetime(odf1['order_date'], format='%d-%m-%Y')

odf1[
    odf1['order_date'].between("2019-04-01", "2019-04-30")
    ]

    id  cust_id order_date order_details  total_order_cost
15  16        3 2019-04-19        Shirts                50
16  17        7 2019-04-19          Suit               150
17  18       15 2019-04-19         Skirt                30
18  19       15 2019-04-20       Dresses               200
20  21        7 2019-04-01          Suit                50
21  22        7 2019-04-02         Skirt                30
22  23        7 2019-04-03       Dresses                50
23  24        7 2019-04-04          Coat                25
24  25        7 2019-04-19          Coat               125
25  26        3 2019-04-20        Gloves                20
26  27        3 2019-04-21           Tie                25
27  28        3 2019-04-22           Cap                15
28  29        3 2019-04-23        Jacket               120
29  30        1 2019-04-19        Jacket               150
30  31        1 2019-04-19         Shoes               125

## Order of execution 
1. And executes first
2. Or executes next 

`techcorp_workforce[`   
`       (techcorp_workforce["department"] == "HR") |`        
`       (techcorp_workforce["department"] == "Engineering") & `   
`       (techcorp_workforce["salary"] > 80000)`  
`]`

 What Python actually evaluates:        
 `HR (any salary) OR (Engineering AND salary > 80000)`

 so we need to use `()` to control the order

# NAN handling 

Nan - is similar to none 

this is from numpy 

`np.nan == np.nan    # False (not True!)`

`np.nan != np.nan    # True`

`np.nan > 5          # False`

`np.nan == "text"    # False`

when use any string functions the `nan` values are silently ignored as the return false 

To check the `Nan` we need to use `.isna()` or to neglect `nan` we use `.notna()`

In [159]:
df.phone_number.isna()

id
1     False
2     False
3      True
4     False
5      True
6     False
7     False
8     False
9      True
10    False
11     True
12    False
13    False
14    False
15     True
16    False
17    False
18    False
19     True
20    False
21    False
22     True
23    False
24    False
25    False
26     True
27    False
28    False
29    False
30     True
31    False
32    False
33     True
34    False
35    False
36     True
37    False
38    False
39     True
40    False
41    False
42     True
43    False
44    False
45     True
46    False
47     True
48    False
49    False
50     True
51    False
Name: phone_number, dtype: bool

In [160]:
df.isna().head()

    first_name  last_name  department  salary  phone_number  joining_date
id
1        False      False       False   False         False         False
2        False      False       False   False         False         False
3        False      False       False   False          True         False
4        False      False       False   False         False         False
5        False      False       False   False          True         False

In [161]:
df[df.isna()]

   first_name last_name department  salary phone_number joining_date
id
1         NaN       NaN        NaN     NaN          NaN          NaN
2         NaN       NaN        NaN     NaN          NaN          NaN
3         NaN       NaN        NaN     NaN          NaN          NaN
4         NaN       NaN        NaN     NaN          NaN          NaN
5         NaN       NaN        NaN     NaN          NaN          NaN
6         NaN       NaN        NaN     NaN          NaN          NaN
7         NaN       NaN        NaN     NaN          NaN          NaN
8         NaN       NaN        NaN     NaN          NaN          NaN
9         NaN       NaN        NaN     NaN          NaN          NaN
10        NaN       NaN        NaN     NaN          NaN          NaN
11        NaN       NaN        NaN     NaN          NaN          NaN
12        NaN       NaN        NaN     NaN          NaN          NaN
13        NaN       NaN        NaN     NaN          NaN          NaN
14        NaN       NaN        NaN     NaN          NaN          NaN
15        NaN       NaN        NaN     NaN          NaN          NaN
16        NaN       NaN        NaN     NaN          NaN          NaN
17        NaN       NaN        NaN     NaN          NaN          NaN
18        NaN       NaN        NaN     NaN          NaN          NaN
19        NaN       NaN        NaN     NaN          NaN          NaN
20        NaN       NaN        NaN     NaN          NaN          NaN
21        NaN       NaN        NaN     NaN          NaN          NaN
22        NaN       NaN        NaN     NaN          NaN          NaN
23        NaN       NaN        NaN     NaN          NaN          NaN
24        NaN       NaN        NaN     NaN          NaN          NaN
25        NaN       NaN        NaN     NaN          NaN          NaN
26        NaN       NaN        NaN     NaN          NaN          NaN
27        NaN       NaN        NaN     NaN          NaN          NaN
28        NaN       NaN        NaN     NaN          NaN          NaN
29        NaN       NaN        NaN     NaN          NaN          NaN
30        NaN       NaN        NaN     NaN          NaN          NaN
31        NaN       NaN        NaN     NaN          NaN          NaN
32        NaN       NaN        NaN     NaN          NaN          NaN
33        NaN       NaN        NaN     NaN          NaN          NaN
34        NaN       NaN        NaN     NaN          NaN          NaN
35        NaN       NaN        NaN     NaN          NaN          NaN
36        NaN       NaN        NaN     NaN          NaN          NaN
37        NaN       NaN        NaN     NaN          NaN          NaN
38        NaN       NaN        NaN     NaN          NaN          NaN
39        NaN       NaN        NaN     NaN          NaN          NaN
40        NaN       NaN        NaN     NaN          NaN          NaN
41        NaN       NaN        NaN     NaN          NaN          NaN
42        NaN       NaN        NaN     NaN          NaN          NaN
43        NaN       NaN        NaN     NaN          NaN          NaN
44        NaN       NaN        NaN     NaN          NaN          NaN
45        NaN       NaN        NaN     NaN          NaN          NaN
46        NaN       NaN        NaN     NaN          NaN          NaN
47        NaN       NaN        NaN     NaN          NaN          NaN
48        NaN       NaN        NaN     NaN          NaN          NaN
49        NaN       NaN        NaN     NaN          NaN          NaN
50        NaN       NaN        NaN     NaN          NaN          NaN
51        NaN       NaN        NaN     NaN          NaN          NaN

In [162]:
df[df.notna()]

     first_name  last_name   department  salary phone_number joining_date
id
1         Sarah   Mitchell           HR   95000     555-0101   15-03-2021
2       Michael       Chen           HR   88000     555-0102   01-06-2022
3         Emily  Rodriguez           HR   82500          NaN   20-09-2021
4         David       Park           HR   80000     555-0104   10-01-2023
5          Lisa   Thompson           HR   65000          NaN   05-04-2021
6        Robert     Garcia           HR   58000     555-0106   15-11-2022
7      Jennifer        Lee           HR   72000     555-0107   20-05-2023
8       William      Davis           HR   91000     555-0108   12-08-2019
9      Patricia     Wilson           HR   78000          NaN   28-02-2018
10        James   Martinez        Admin   87000     555-0201   01-07-2021
11       Amanda     Taylor        Admin   92000          NaN   15-03-2022
12  Christopher   Anderson        Admin   81500     555-0203   22-08-2023
13     Michelle     Thomas        Admin   54000     555-0204   30-11-2021
14       Daniel    Jackson        Admin   62000     555-0205   10-09-2022
15      Jessica      White        Admin   48000          NaN   14-02-2023
16      Matthew     Harris        Admin   85000     555-0207   20-05-2017
17        Kevin      Brown  Engineering  125000     555-0301   15-01-2021
18       Angela     Miller  Engineering  118000     555-0302   01-04-2022
19        Brian      Moore  Engineering  105000          NaN   20-06-2021
20    Stephanie      Clark  Engineering   98000     555-0304   10-03-2023
21      Timothy      Lewis  Engineering   75000     555-0305   15-08-2022
22      Rebecca     Walker  Engineering   68000          NaN   01-11-2023
23       George       Hall  Engineering  130000     555-0307   01-09-2016
24        Donna      Allen  Engineering   95000     555-0308   15-12-2019
25         Ryan      Young    Marketing   72000     555-0401   01-05-2021
26        Laura       King    Marketing   85000          NaN   20-02-2022
27         Eric     Wright    Marketing   68000     555-0403   15-07-2023
28       Sharon      Scott    Marketing   91000     555-0404   01-10-2022
29      Kenneth     Torres    Marketing   95000     555-0405   10-03-2018
30        Carol     Nguyen    Marketing   78000          NaN   20-11-2015
31        Jason       Hill        Sales   65000     555-0501   15-02-2021
32          Amy     Flores        Sales   71000     555-0502   20-05-2022
33        Jacob      Green        Sales   58000          NaN   10-08-2021
34     Kathleen      Adams        Sales   82000     555-0504   25-01-2023
35         Gary     Nelson        Sales   76000     555-0505   01-12-2022
36         Anna      Baker        Sales   69000          NaN   15-04-2023
37      Stephen     Rivera        Sales   88000     555-0507   01-07-2017
38     Nicholas   Campbell      Finance   92000     555-0601   01-04-2021
39       Brenda   Mitchell      Finance   78000          NaN   15-07-2022
40     Jonathan     Carter      Finance   85000     555-0603   20-10-2021
41      Shirley    Roberts      Finance   67000     555-0604   01-06-2023
42       Edward      Gomez      Finance   73000          NaN   10-01-2022
43      Cynthia   Phillips      Finance   81000     555-0606   15-09-2023
44      Jeffrey      Evans      Finance  105000     555-0607   01-06-2014
45      Dorothy     Turner      Finance   88000          NaN   20-03-2019
46         Mark       Diaz           HR   55000     555-0109   15-01-2024
47       Sandra     Parker        Admin   51000          NaN   01-02-2024
48         Paul    Collins  Engineering   88000     555-0309   10-03-2024
49     Kimberly    Stewart  Engineering   92000     555-0310   01-12-2021
50       Andrew    Sanchez        Sales   63000          NaN   20-01-2024
51        Betty     Morris      Finance   71000     555-0608   15-11-2021

In [163]:
df[df['phone_number'].isna()]

   first_name  last_name   department  salary phone_number joining_date
id
3       Emily  Rodriguez           HR   82500          NaN   20-09-2021
5        Lisa   Thompson           HR   65000          NaN   05-04-2021
9    Patricia     Wilson           HR   78000          NaN   28-02-2018
11     Amanda     Taylor        Admin   92000          NaN   15-03-2022
15    Jessica      White        Admin   48000          NaN   14-02-2023
19      Brian      Moore  Engineering  105000          NaN   20-06-2021
22    Rebecca     Walker  Engineering   68000          NaN   01-11-2023
26      Laura       King    Marketing   85000          NaN   20-02-2022
30      Carol     Nguyen    Marketing   78000          NaN   20-11-2015
33      Jacob      Green        Sales   58000          NaN   10-08-2021
36       Anna      Baker        Sales   69000          NaN   15-04-2023
39     Brenda   Mitchell      Finance   78000          NaN   15-07-2022
42     Edward      Gomez      Finance   73000          NaN   10-01-2022
45    Dorothy     Turner      Finance   88000          NaN   20-03-2019
47     Sandra     Parker        Admin   51000          NaN   01-02-2024
50     Andrew    Sanchez        Sales   63000          NaN   20-01-2024

In [164]:
df[df['phone_number'].notna()]

     first_name last_name   department  salary phone_number joining_date
id
1         Sarah  Mitchell           HR   95000     555-0101   15-03-2021
2       Michael      Chen           HR   88000     555-0102   01-06-2022
4         David      Park           HR   80000     555-0104   10-01-2023
6        Robert    Garcia           HR   58000     555-0106   15-11-2022
7      Jennifer       Lee           HR   72000     555-0107   20-05-2023
8       William     Davis           HR   91000     555-0108   12-08-2019
10        James  Martinez        Admin   87000     555-0201   01-07-2021
12  Christopher  Anderson        Admin   81500     555-0203   22-08-2023
13     Michelle    Thomas        Admin   54000     555-0204   30-11-2021
14       Daniel   Jackson        Admin   62000     555-0205   10-09-2022
16      Matthew    Harris        Admin   85000     555-0207   20-05-2017
17        Kevin     Brown  Engineering  125000     555-0301   15-01-2021
18       Angela    Miller  Engineering  118000     555-0302   01-04-2022
20    Stephanie     Clark  Engineering   98000     555-0304   10-03-2023
21      Timothy     Lewis  Engineering   75000     555-0305   15-08-2022
23       George      Hall  Engineering  130000     555-0307   01-09-2016
24        Donna     Allen  Engineering   95000     555-0308   15-12-2019
25         Ryan     Young    Marketing   72000     555-0401   01-05-2021
27         Eric    Wright    Marketing   68000     555-0403   15-07-2023
28       Sharon     Scott    Marketing   91000     555-0404   01-10-2022
29      Kenneth    Torres    Marketing   95000     555-0405   10-03-2018
31        Jason      Hill        Sales   65000     555-0501   15-02-2021
32          Amy    Flores        Sales   71000     555-0502   20-05-2022
34     Kathleen     Adams        Sales   82000     555-0504   25-01-2023
35         Gary    Nelson        Sales   76000     555-0505   01-12-2022
37      Stephen    Rivera        Sales   88000     555-0507   01-07-2017
38     Nicholas  Campbell      Finance   92000     555-0601   01-04-2021
40     Jonathan    Carter      Finance   85000     555-0603   20-10-2021
41      Shirley   Roberts      Finance   67000     555-0604   01-06-2023
43      Cynthia  Phillips      Finance   81000     555-0606   15-09-2023
44      Jeffrey     Evans      Finance  105000     555-0607   01-06-2014
46         Mark      Diaz           HR   55000     555-0109   15-01-2024
48         Paul   Collins  Engineering   88000     555-0309   10-03-2024
49     Kimberly   Stewart  Engineering   92000     555-0310   01-12-2021
51        Betty    Morris      Finance   71000     555-0608   15-11-2021

In [165]:
df[df.isna().any(axis=1)]

   first_name  last_name   department  salary phone_number joining_date
id
3       Emily  Rodriguez           HR   82500          NaN   20-09-2021
5        Lisa   Thompson           HR   65000          NaN   05-04-2021
9    Patricia     Wilson           HR   78000          NaN   28-02-2018
11     Amanda     Taylor        Admin   92000          NaN   15-03-2022
15    Jessica      White        Admin   48000          NaN   14-02-2023
19      Brian      Moore  Engineering  105000          NaN   20-06-2021
22    Rebecca     Walker  Engineering   68000          NaN   01-11-2023
26      Laura       King    Marketing   85000          NaN   20-02-2022
30      Carol     Nguyen    Marketing   78000          NaN   20-11-2015
33      Jacob      Green        Sales   58000          NaN   10-08-2021
36       Anna      Baker        Sales   69000          NaN   15-04-2023
39     Brenda   Mitchell      Finance   78000          NaN   15-07-2022
42     Edward      Gomez      Finance   73000          NaN   10-01-2022
45    Dorothy     Turner      Finance   88000          NaN   20-03-2019
47     Sandra     Parker        Admin   51000          NaN   01-02-2024
50     Andrew    Sanchez        Sales   63000          NaN   20-01-2024

## Understanding axis 

axis=0 → ↓ down → rows involved → column result / row deleted

axis=1 → → across → columns involved → row result / column deleted


| Operation | axis=0 | axis=1 |
|----------|--------|--------|
| `sum()` | sum per column | sum per row |
| `mean()` | mean per column | mean per row |
| `drop()` | drop row | drop column |
| `apply()` | apply on columns | apply on rows |

## Counting Nan values 

to count the number of `nan`

`#get count in each column`

`df.isna().sum()`

`.count()` gives the sum of non-null values in a dataframe or series

So for counting `nan` we need to use `.isna().sum()`

In [166]:
df.count()

first_name      51
last_name       51
department      51
salary          51
phone_number    35
joining_date    51
dtype: int64

In [167]:
df['department'].count()

np.int64(51)

In [168]:
df.isna().sum()

first_name       0
last_name        0
department       0
salary           0
phone_number    16
joining_date     0
dtype: int64

to get the percentage of data in a column having `nan`

`df.isna().mean()*100`

In [169]:
df.isna().mean()*100

first_name       0.000000
last_name        0.000000
department       0.000000
salary           0.000000
phone_number    31.372549
joining_date     0.000000
dtype: float64

## Rows with Nan
to get the number of rows with nan we use 

`df.isna().any(axis=1).sum()`

In [170]:
df.isna().any(axis=1)

id
1     False
2     False
3      True
4     False
5      True
6     False
7     False
8     False
9      True
10    False
11     True
12    False
13    False
14    False
15     True
16    False
17    False
18    False
19     True
20    False
21    False
22     True
23    False
24    False
25    False
26     True
27    False
28    False
29    False
30     True
31    False
32    False
33     True
34    False
35    False
36     True
37    False
38    False
39     True
40    False
41    False
42     True
43    False
44    False
45     True
46    False
47     True
48    False
49    False
50     True
51    False
dtype: bool

In [171]:
df.isna().any(axis=1).sum()

np.int64(16)

In [172]:
df.isna().any(axis=1).count()

np.int64(51)

### Differnce in the output 

`.sum()` adds the values <- in python `True = 1` and `False = 0`

but `.count()` counts the non-null vales <- in pthon 0 and  1 are not non-null

## Columns with NAN

In [173]:
df.isna().any(axis=0)

first_name      False
last_name       False
department      False
salary          False
phone_number     True
joining_date    False
dtype: bool

In [174]:
df.isna().any(axis=0).sum()

np.int64(1)

## Fill the `nan` values

Use `.fillna()` to fill the null values, it takes one argument that replaces `nan`

In [175]:
df.phone_number.fillna('Unkown')

id
1     555-0101
2     555-0102
3       Unkown
4     555-0104
5       Unkown
6     555-0106
7     555-0107
8     555-0108
9       Unkown
10    555-0201
11      Unkown
12    555-0203
13    555-0204
14    555-0205
15      Unkown
16    555-0207
17    555-0301
18    555-0302
19      Unkown
20    555-0304
21    555-0305
22      Unkown
23    555-0307
24    555-0308
25    555-0401
26      Unkown
27    555-0403
28    555-0404
29    555-0405
30      Unkown
31    555-0501
32    555-0502
33      Unkown
34    555-0504
35    555-0505
36      Unkown
37    555-0507
38    555-0601
39      Unkown
40    555-0603
41    555-0604
42      Unkown
43    555-0606
44    555-0607
45      Unkown
46    555-0109
47      Unkown
48    555-0309
49    555-0310
50      Unkown
51    555-0608
Name: phone_number, dtype: str

## Drop the `nan` values 

we can drop the record  based on 2 conditions
1. any column has `nan`   <- `.dropna()`
2. specific column has `nan`  <- `.dropna(subset='column-name')`

we use `.dropna()` <- for dropping the record and is need to be stored 

If we use `.dropna(axis=1)` the whole column is dropped 

If we want to drop a row if  and only if all the entries of that row is `nan` then we use `.dropna(how='all')`

In [176]:
# Drop rows where ANY column is NaN
df.dropna().head()

   first_name last_name department  salary phone_number joining_date
id
1       Sarah  Mitchell         HR   95000     555-0101   15-03-2021
2     Michael      Chen         HR   88000     555-0102   01-06-2022
4       David      Park         HR   80000     555-0104   10-01-2023
6      Robert    Garcia         HR   58000     555-0106   15-11-2022
7    Jennifer       Lee         HR   72000     555-0107   20-05-2023

Drop na does not alter the existing table.. we need to store the result in another variable

In [177]:
# Drop rows where a SPECIFIC column is NaN
df.dropna(subset=["phone_number"]).head()

   first_name last_name department  salary phone_number joining_date
id
1       Sarah  Mitchell         HR   95000     555-0101   15-03-2021
2     Michael      Chen         HR   88000     555-0102   01-06-2022
4       David      Park         HR   80000     555-0104   10-01-2023
6      Robert    Garcia         HR   58000     555-0106   15-11-2022
7    Jennifer       Lee         HR   72000     555-0107   20-05-2023

In [178]:
df.isna().sum()

first_name       0
last_name        0
department       0
salary           0
phone_number    16
joining_date     0
dtype: int64

# Sorting data

Sorting  database based on a row 

`.sort_values()` <- ascending          
`.sort_values(ascending =False)` <- descending

In [179]:
# odf1.sort_values()

# ---------------------------------------------------------------------------
# TypeError                                 Traceback (most recent call last)
# Cell In[83], line 1
# ----> 1 odf1.sort_values()

# TypeError: DataFrame.sort_values() missing 1 required positional argument: 'by'

In [180]:
odf1.sort_values('total_order_cost').head()

    id  cust_id order_date order_details  total_order_cost
27  28        3 2019-04-22           Cap                15
7    8       15 2019-03-11       Slipper                20
25  26        3 2019-04-20        Gloves                20
12  13       12 2019-03-11       Slipper                20
26  27        3 2019-04-21           Tie                25

In [181]:
odf1.sort_values(['total_order_cost','cust_id']).head()

    id  cust_id order_date order_details  total_order_cost
27  28        3 2019-04-22           Cap                15
25  26        3 2019-04-20        Gloves                20
12  13       12 2019-03-11       Slipper                20
7    8       15 2019-03-11       Slipper                20
26  27        3 2019-04-21           Tie                25

In [182]:
sorted(odf1)

['cust_id', 'id', 'order_date', 'order_details', 'total_order_cost']

### Differnce in output 

`.sort_values()` <- pandas function, takes the df and works row by row and returns dataframe op

`sorted()` <- python based, takes iterable. for a dataframe the elements are its column this when iterated the value is the column names sorted.

In [183]:
sorted(odf1['total_order_cost'])

[15,
 20,
 20,
 20,
 25,
 25,
 25,
 30,
 30,
 30,
 50,
 50,
 50,
 50,
 60,
 60,
 60,
 80,
 80,
 80,
 80,
 80,
 100,
 100,
 120,
 125,
 125,
 125,
 150,
 150,
 200]

In [184]:
odf1.head()

   id  cust_id order_date order_details  total_order_cost
0   1        3 2019-03-04          Coat               100
1   2        3 2019-03-01         Shoes                80
2   3        3 2019-03-07         Skirt                30
3   4        7 2019-02-01          Coat                25
4   5        7 2019-03-10         Shoes                80

## Creating a new column 
When calculation need & requirements are different then we might need to create a new column for find the values and then sorting them 

this can be avoided if the purpose is only for sorting using lambda 

for example:
`df.sort_values(key=lambda c: c.str.len())`

In [185]:
df["name_len"] = df["first_name"].str.len()
df.sort_values("name_len",ascending=False).head()

,first_name,last_name,department,salary,phone_number,joining_date,name_len
id,,,,,,,
12,Christopher,Anderson,Admin,81500,555-0203,22-08-2023,11
20,Stephanie,Clark,Engineering,98000,555-0304,10-03-2023,9
7,Jennifer,Lee,HR,72000,555-0107,20-05-2023,8
9,Patricia,Wilson,HR,78000,NaN,28-02-2018,8
40,Jonathan,Carter,Finance,85000,555-0603,20-10-2021,8

In [186]:
for x in copy_df["First Name"]:
    print(x)

Sarah
Michael
Emily
David
Lisa
Robert
Jennifer
William
Patricia
James
Amanda
Christopher
Michelle
Daniel
Jessica
Matthew
Kevin
Angela
Brian
Stephanie
Timothy
Rebecca
George
Donna
Ryan
Laura
Eric
Sharon
Kenneth
Carol
Jason
Amy
Jacob
Kathleen
Gary
Anna
Stephen
Nicholas
Brenda
Jonathan
Shirley
Edward
Cynthia
Jeffrey
Dorothy
Mark
Sandra
Paul
Kimberly
Andrew
Betty

In [187]:
copy_df.sort_values(by="First Name", key=lambda c: c.str.len(), ascending=False).head()

    id   First Name last_name   department  salary phone_number joining_date
11  12  Christopher  Anderson        Admin   81500     555-0203   22-08-2023
19  20    Stephanie     Clark  Engineering   98000     555-0304   10-03-2023
6    7     Jennifer       Lee           HR   72000     555-0107   20-05-2023
8    9     Patricia    Wilson           HR   78000          NaN   28-02-2018
39  40     Jonathan    Carter      Finance   85000     555-0603   20-10-2021

# Limiting Data 

## with `.sort_values()`
 
We can limit using 

`.head()` <- top values 

`.tail()` <- bottom values

Useful for multiple column sorting or specific sort order

## without `.sort_values()`

without `sort_values()` we can use 

`.nsmallest(N, "sorting column")` <- for ascending 

`.nlargest(N, "sorting column")` <- for descending

Usualy faster than the other method

In [188]:
df.nlargest(5, "salary")

,first_name,last_name,department,salary,phone_number,joining_date,name_len
id,,,,,,,
23,George,Hall,Engineering,130000,555-0307,01-09-2016,6
17,Kevin,Brown,Engineering,125000,555-0301,15-01-2021,5
18,Angela,Miller,Engineering,118000,555-0302,01-04-2022,6
19,Brian,Moore,Engineering,105000,NaN,20-06-2021,5
44,Jeffrey,Evans,Finance,105000,555-0607,01-06-2014,7

In [189]:
df.nsmallest(3, "salary")

   first_name last_name department  salary phone_number joining_date  name_len
id
15    Jessica     White      Admin   48000          NaN   14-02-2023         7
47     Sandra    Parker      Admin   51000          NaN   01-02-2024         6
13   Michelle    Thomas      Admin   54000     555-0204   30-11-2021         8

# Full Pattern 
In practice, you almost never sort alone. 

The real pattern is a chain: 
1. filter to the rows you care about, 
2. sort by the column that matters, 
3. limit to the top N, and 
4. select only the columns you need. 

This chain is the backbone of exploratory analysis.

In [190]:
df[df["department"] == "Engineering"].sort_values("joining_date", ascending=False).head(5)[["first_name", "last_name", "joining_date"]]

   first_name last_name joining_date
id
19      Brian     Moore   20-06-2021
24      Donna     Allen   15-12-2019
21    Timothy     Lewis   15-08-2022
17      Kevin     Brown   15-01-2021
48       Paul   Collins   10-03-2024

# Aggregate functions 

## number of rows 

`len(dataframe)`

In [191]:
len(odf1)

31

## no. non null values per column 

`df.count()`

In [192]:
odf1.count()

id                  31
cust_id             31
order_date          31
order_details       31
total_order_cost    31
dtype: int64

## unique no. of non-null values per column

`df.nunique()`

In [193]:
odf1.nunique()

id                  31
cust_id              7
order_date          17
order_details       13
total_order_cost    12
dtype: int64

In [194]:
odf1.cust_id.nunique()

7

### Understanding 
`.unique()` works on **series** <- unique values in a particular column and gives the values

`.nunique()` works on both **series and dataframe** <- unique values count in each column of a particular iterable.

## numerical column analysis

### sum of specified column 


`df[ _numerical_column_ ].sum()`

`.sum()` ignores `nan` values

In [195]:
odf1.total_order_cost.sum()

np.int64(2215)

### Mean of the column

`df[ _numerical_column_ ].mean()`

`.mean()` skips `nan` values. 

hence the rows with `nan` values will not be inculed in the mean calculation 

therefore, 
 If you have values 100, 200, and NaN, the mean is 150 (300 / 2), not 100 (300 / 3)

In [196]:
odf1.total_order_cost.mean()

np.float64(71.45161290322581)

## Multiple functions at once 

to use `sum, max, min, mean, count, etc`  we can use `.agg([ _list_of_functions_ ])`

`.agg()` is a function that takes a **Series** and returns a **scalar OR Series**

In [197]:
odf1["total_order_cost"].agg(["sum", "mean", "min", "max","count"])

sum      2215.000000
mean       71.451613
min        15.000000
max       200.000000
count      31.000000
Name: total_order_cost, dtype: float64

### Naming `.agg()` function index

We can name the agg function result 

`df["column_name"].agg({"new_name" : "aggregation_function" , "new_name" : "aggregation_function"})`


The result is a series but this new_names that are assigned acts as an index to the values in the series

In [198]:
result = odf1["total_order_cost"].agg({'total':"sum","avg": "mean"})
print(result)

total    2215.000000
avg        71.451613
Name: total_order_cost, dtype: float64

In [199]:
result['total']

np.float64(2215.0)

In [200]:
type(odf1["total_order_cost"].agg({'total':"sum","avg": "mean"}))

pandas.Series

In [201]:
df['salary'].agg(['min', 'mean', 'max']).rename(
    index={'min': 'lowest_salary', 'mean': 'mean_salary', 'max': 'highest_salary'}
).to_frame().T

        lowest_salary   mean_salary  highest_salary
salary        48000.0  80784.313725        130000.0

In [202]:
type(df['salary'].agg(['min', 'mean', 'max']).rename(
    index={'min': 'lowest_salary', 'mean': 'mean_salary', 'max': 'highest_salary'}
).to_frame().T)

pandas.DataFrame

In [203]:
odf1["total_order_cost"].agg({'total':"sum","avg": "mean"})

total    2215.000000
avg        71.451613
Name: total_order_cost, dtype: float64

We can also use `.rename(index = {"function_name":"index_name","function_name":"index_name"})` 
to rename the `.agg()`calculations

In [204]:
# total sales revenue generated by Samantha and Lisa

sales_df[sales_df['salesperson'].str.lower().isin(["samantha","lisa"])]['sales_revenue'].sum()

np.int64(112650)

In [205]:
df[df['salary']==df['salary'].max()]['first_name']

id
23    George
Name: first_name, dtype: str

#### mindmap 
use list of calculative functions `[]` inside `.agg()` to just perform the calculation and the name of the function becomes the index

use dict with keys as names and vales as the calculative functions `{}` inside `.agg()` to perform calculation and rename index

### Custom functions in `.agg()`

We can add custom function inside `.agg()` function

In [206]:
print(df['salary'].agg(['mean', 'max', lambda x: x.min()]))
print("Normal:\n",df['salary'].agg(['mean', 'max', 'min']))
print("Custom:\n",df['salary'].agg(['mean', 'max', lambda x: x.max() - x.min()]))

mean         80784.313725
max         130000.000000
<lambda>     48000.000000
Name: salary, dtype: float64
Normal:
 mean     80784.313725
max     130000.000000
min      48000.000000
Name: salary, dtype: float64
Custom:
 mean         80784.313725
max         130000.000000
<lambda>     82000.000000
Name: salary, dtype: float64

# Grouping Data

When we want to group the data based on one column and extract the info of another column based on the grouped columns we use `.groupby()`

`df.groupby( 'column_name_to_group' )['column_name_to_perform_calculation'].agg()`

## Exploring Groupby internals

when we group a df based on the column 

we get a DataFrameGroupBy object which when converted to list to read we can see that the the values are tuples of data

In [207]:
type(df.groupby('department'))

pandas.api.typing.DataFrameGroupBy

In [208]:
df.groupby('department')

In [209]:
list(df.groupby('department'))

[('Admin',
       first_name last_name department  salary phone_number joining_date  \
  id
  10        James  Martinez      Admin   87000     555-0201   01-07-2021
  11       Amanda    Taylor      Admin   92000          NaN   15-03-2022
  12  Christopher  Anderson      Admin   81500     555-0203   22-08-2023
  13     Michelle    Thomas      Admin   54000     555-0204   30-11-2021
  14       Daniel   Jackson      Admin   62000     555-0205   10-09-2022
  15      Jessica     White      Admin   48000          NaN   14-02-2023
  16      Matthew    Harris      Admin   85000     555-0207   20-05-2017
  47       Sandra    Parker      Admin   51000          NaN   01-02-2024

      name_len
  id
  10         5
  11         6
  12        11
  13         8
  14         6
  15         7
  16         7
  47         6  ),
 ('Engineering',
     first_name last_name   department  salary phone_number joining_date  \
  id
  17      Kevin     Brown  Engineering  125000     555-0301   15-01-2021
  18     Angela    Miller  Engineering  118000     555-0302   01-04-2022
  19      Brian     Moore  Engineering  105000          NaN   20-06-2021
  20  Stephanie     Clark  Engineering   98000     555-0304   10-03-2023
  21    Timothy     Lewis  Engineering   75000     555-0305   15-08-2022
  22    Rebecca    Walker  Engineering   68000          NaN   01-11-2023
  23     George      Hall  Engineering  130000     555-0307   01-09-2016
  24      Donna     Allen  Engineering   95000     555-0308   15-12-2019
  48       Paul   Collins  Engineering   88000     555-0309   10-03-2024
  49   Kimberly   Stewart  Engineering   92000     555-0310   01-12-2021

      name_len
  id
  17         5
  18         6
  19         5
  20         9
  21         7
  22         7
  23         6
  24         5
  48         4
  49         8  ),
 ('Finance',
     first_name last_name department  salary phone_number joining_date  name_len
  id
  38   Nicholas  Campbell    Finance   92000     555-0601   01-04-2021         8
  39     Brenda  Mitchell    Finance   78000          NaN   15-07-2022         6
  40   Jonathan    Carter    Finance   85000     555-0603   20-10-2021         8
  41    Shirley   Roberts    Finance   67000     555-0604   01-06-2023         7
  42     Edward     Gomez    Finance   73000          NaN   10-01-2022         6
  43    Cynthia  Phillips    Finance   81000     555-0606   15-09-2023         7
  44    Jeffrey     Evans    Finance  105000     555-0607   01-06-2014         7
  45    Dorothy    Turner    Finance   88000          NaN   20-03-2019         7
  51      Betty    Morris    Finance   71000     555-0608   15-11-2021         5),
 ('HR',
     first_name  last_name department  salary phone_number joining_date  \
  id
  1       Sarah   Mitchell         HR   95000     555-0101   15-03-2021
  2     Michael       Chen         HR   88000     555-0102   01-06-2022
  3       Emily  Rodriguez         HR   82500          NaN   20-09-2021
  4       David       Park         HR   80000     555-0104   10-01-2023
  5        Lisa   Thompson         HR   65000          NaN   05-04-2021
  6      Robert     Garcia         HR   58000     555-0106   15-11-2022
  7    Jennifer        Lee         HR   72000     555-0107   20-05-2023
  8     William      Davis         HR   91000     555-0108   12-08-2019
  9    Patricia     Wilson         HR   78000          NaN   28-02-2018
  46       Mark       Diaz         HR   55000     555-0109   15-01-2024

      name_len
  id
  1          5
  2          7
  3          5
  4          5
  5          4
  6          6
  7          8
  8          7
  9          8
  46         4  ),
 ('Marketing',
     first_name last_name department  salary phone_number joining_date  name_len
  id
  25       Ryan     Young  Marketing   72000     555-0401   01-05-2021         4
  26      Laura      King  Marketing   85000          NaN   20-02-2022         5
  27       Eric    Wright  Marketing   68000     555-0403   15-07-2023         4
  28     Sharon     Scott  Marketing   91000     555-0404   01-10-2022         6
  29    Kenneth    Torres  Marketing   95000     555-0405   10-03-2018         7
  30      Carol    Nguyen  Marketing   78000          NaN   20-11-2015         5),
 ('Sales',
     first_name last_name department  salary phone_number joining_date  name_len
  id
  31      Jason      Hill      Sales   65000     555-0501   15-02-2021         5
  32        Amy    Flores      Sales   71000     555-0502   20-05-2022         3
  33      Jacob     Green      Sales   58000          NaN   10-08-2021         5
  34   Kathleen     Adams      Sales   82000     555-0504   25-01-2023         8
  35       Gary    Nelson      Sales   76000     555-0505   01-12-2022         4
  36       Anna     Baker      Sales   69000          NaN   15-04-2023         4
  37    Stephen    Rivera      Sales   88000     555-0507   01-07-2017         7
  50     Andrew   Sanchez      Sales   63000          NaN   20-01-2024         6)]

Applying the another column based on which we need to groupby should should act we get the series object

In [210]:
df.groupby('department')['salary']

In [211]:
list(df.groupby('department')['salary'])

[('Admin',
  id
  10    87000
  11    92000
  12    81500
  13    54000
  14    62000
  15    48000
  16    85000
  47    51000
  Name: salary, dtype: int64),
 ('Engineering',
  id
  17    125000
  18    118000
  19    105000
  20     98000
  21     75000
  22     68000
  23    130000
  24     95000
  48     88000
  49     92000
  Name: salary, dtype: int64),
 ('Finance',
  id
  38     92000
  39     78000
  40     85000
  41     67000
  42     73000
  43     81000
  44    105000
  45     88000
  51     71000
  Name: salary, dtype: int64),
 ('HR',
  id
  1     95000
  2     88000
  3     82500
  4     80000
  5     65000
  6     58000
  7     72000
  8     91000
  9     78000
  46    55000
  Name: salary, dtype: int64),
 ('Marketing',
  id
  25    72000
  26    85000
  27    68000
  28    91000
  29    95000
  30    78000
  Name: salary, dtype: int64),
 ('Sales',
  id
  31    65000
  32    71000
  33    58000
  34    82000
  35    76000
  36    69000
  37    88000
  50    63000
  Name: salary, dtype: int64)]

## Working with Groupby

In [212]:
df.groupby('department').sum()

,first_name,last_name,salary,phone_number,joining_date,name_len
department,,,,,,
Admin,JamesAmandaChristopherMichelleDanielJessicaMat...,MartinezTaylorAndersonThomasJacksonWhiteHarris...,560500,555-0201555-0203555-0204555-0205555-0207,01-07-202115-03-202222-08-202330-11-202110-09-...,56
Engineering,KevinAngelaBrianStephanieTimothyRebeccaGeorgeD...,BrownMillerMooreClarkLewisWalkerHallAllenColli...,994000,555-0301555-0302555-0304555-0305555-0307555-03...,15-01-202101-04-202220-06-202110-03-202315-08-...,62
Finance,NicholasBrendaJonathanShirleyEdwardCynthiaJeff...,CampbellMitchellCarterRobertsGomezPhillipsEvan...,740000,555-0601555-0603555-0604555-0606555-0607555-0608,01-04-202115-07-202220-10-202101-06-202310-01-...,61
HR,SarahMichaelEmilyDavidLisaRobertJenniferWillia...,MitchellChenRodriguezParkThompsonGarciaLeeDavi...,764500,555-0101555-0102555-0104555-0106555-0107555-01...,15-03-202101-06-202220-09-202110-01-202305-04-...,59
Marketing,RyanLauraEricSharonKennethCarol,YoungKingWrightScottTorresNguyen,489000,555-0401555-0403555-0404555-0405,01-05-202120-02-202215-07-202301-10-202210-03-...,31
Sales,JasonAmyJacobKathleenGaryAnnaStephenAndrew,HillFloresGreenAdamsNelsonBakerRiveraSanchez,572000,555-0501555-0502555-0504555-0505555-0507,15-02-202120-05-202210-08-202125-01-202301-12-...,42

In [213]:
df.groupby('department').count()

,first_name,last_name,salary,phone_number,joining_date,name_len
department,,,,,,
Admin,8,8,8,5,8,8
Engineering,10,10,10,8,10,10
Finance,9,9,9,6,9,9
HR,10,10,10,7,10,10
Marketing,6,6,6,4,6,6
Sales,8,8,8,5,8,8

In [214]:
df.groupby('department')['first_name'].count()

department
Admin           8
Engineering    10
Finance         9
HR             10
Marketing       6
Sales           8
Name: first_name, dtype: int64

In [215]:
type(df.groupby('department')['first_name'].count())

pandas.Series

In [216]:
df.groupby('department')['first_name'].count().reset_index(name='name')

    department  name
0        Admin     8
1  Engineering    10
2      Finance     9
3           HR    10
4    Marketing     6
5        Sales     8

In [217]:
type(df.groupby('department')['first_name'].count().reset_index(name='name'))

pandas.DataFrame

when we use agg we get the value

In [218]:
type(df.groupby('department')['salary'].sum())

pandas.Series

In [219]:
df.groupby('department')['salary'].sum().reset_index(name='money')

    department   money
0        Admin  560500
1  Engineering  994000
2      Finance  740000
3           HR  764500
4    Marketing  489000
5        Sales  572000

In [220]:
type(df.groupby('department')['salary'].sum().reset_index(name='money'))

pandas.DataFrame

In [221]:
df.groupby('department')['salary'].agg(['sum'])

                sum
department
Admin        560500
Engineering  994000
Finance      740000
HR           764500
Marketing    489000
Sales        572000

## Rename the calculated column `.reset_index()`

to rename the column we use `.reset_index(name= 'name_to_be_kept')`

behaviour of `.reset_index())`:   
1. working on **series**
2. working on **dataframe**


when `.reset_index()` used on **Series** we use the **argument name `name`** <- this happens when we use single `agg` functions

this updates the name of the column inside `[ ]` in `groupby()`


 `.reset_index()` used on **Data Frame** we use the **argument name `names`** <- this happens when we use multiple  `agg` functions

this updates the name of the column inside `()` in `groupby()`

In [222]:
df.groupby('department')['salary'].agg(['sum'])

                sum
department
Admin        560500
Engineering  994000
Finance      740000
HR           764500
Marketing    489000
Sales        572000

In [223]:
df.groupby('department')['salary'].sum().reset_index(name='salary_grouped')

    department  salary_grouped
0        Admin          560500
1  Engineering          994000
2      Finance          740000
3           HR          764500
4    Marketing          489000
5        Sales          572000

In [224]:
df.groupby('department')['salary'].agg(salary='sum').reset_index()

    department  salary
0        Admin  560500
1  Engineering  994000
2      Finance  740000
3           HR  764500
4    Marketing  489000
5        Sales  572000

In [225]:
df.groupby('department')['salary'].agg(['sum']).rename(columns={'sum':'Grouped salary'})

             Grouped salary
department
Admin                560500
Engineering          994000
Finance              740000
HR                   764500
Marketing            489000
Sales                572000

In [226]:
df.groupby('department')['salary'].agg(['sum']).rename(columns={'sum':'Grouped salary'})

             Grouped salary
department
Admin                560500
Engineering          994000
Finance              740000
HR                   764500
Marketing            489000
Sales                572000

In [227]:
df.groupby('department')['salary'].agg(['sum']).reset_index(names='Department').rename(columns={'sum':'Grouped salary'})

    Department  Grouped salary
0        Admin          560500
1  Engineering          994000
2      Finance          740000
3           HR          764500
4    Marketing          489000
5        Sales          572000

In [228]:
df.groupby('department')['salary'].agg(['sum']).reset_index(names='Department')

    Department     sum
0        Admin  560500
1  Engineering  994000
2      Finance  740000
3           HR  764500
4    Marketing  489000
5        Sales  572000

In [229]:
type(df.groupby('department')['salary'].agg(['sum']).reset_index(names='Department'))

pandas.DataFrame

In [230]:
type(df.groupby('department')['salary'].agg(['sum']))

pandas.DataFrame

In [231]:
df.groupby('department')['salary'].agg('sum').reset_index(name='salary1')

    department  salary1
0        Admin   560500
1  Engineering   994000
2      Finance   740000
3           HR   764500
4    Marketing   489000
5        Sales   572000

The above works while the below code throws excpetion as `.agg()` we used `[]` in the below code, so even if the function is only one `[]` make `.agg()` think that it is expecting multiple functions. Hence the oputput type is **Dataframe**

For a dataframe the correct attribute for `.reset_index()` is **names**

In [232]:
# df.groupby('department')['salary'].agg(['sum']).reset_index(name='salary')

# ---------------------------------------------------------------------------
# TypeError                                 Traceback (most recent call last)
# Cell In[107], line 1
# ----> 1 df.groupby('department')['salary'].agg(['sum']).reset_index(name='salary')

# TypeError: DataFrame.reset_index() got an unexpected keyword argument 'name'. Did you mean 'names'?

In [233]:
df.groupby('department').agg({'salary': 'sum'})

             salary
department
Admin        560500
Engineering  994000
Finance      740000
HR           764500
Marketing    489000
Sales        572000

In [234]:
# df.groupby('department').agg({'salary1': 'sum'})


# ---------------------------------------------------------------------------
# KeyError                                  Traceback (most recent call last)
# Cell In[126], line 1
# ----> 1 df.groupby('department').agg({'salary1': 'sum'})

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\groupby\generic.py:2291, in DataFrameGroupBy.aggregate(self, func, engine, engine_kwargs, *args, **kwargs)
#    2288     kwargs["engine_kwargs"] = engine_kwargs
#    2290 op = GroupByApply(self, func, args=args, kwargs=kwargs)
# -> 2291 result = op.agg()
#    2292 if not is_dict_like(func) and result is not None:
#    2293     # GH #52849
#    2294     if not self.as_index and is_list_like(func):

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\apply.py:294, in Apply.agg(self)
#     291     return self.apply_str()
#     293 if is_dict_like(func):
# --> 294     return self.agg_dict_like()
#     295 elif is_list_like(func):
#     296     # we require a list, but not a 'str'
#     297     return self.agg_list_like()

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\apply.py:511, in Apply.agg_dict_like(self)
#     503 def agg_dict_like(self) -> DataFrame | Series:
#     504     """
#     505     Compute aggregation in the case of a dict-like argument.
# ...
#     767 # eg. {'A' : ['mean']}, normalize all to
#     768 # be list-likes
#     769 # Cannot use func.values() because arg may be a Series

# KeyError: "Label(s) ['salary1'] do not exist"
# Output is truncated. View as a scrollable element or open in a text editor. Adjust cell output settings...

In [235]:
# df.groupby('department')['salary'].agg({'salary_grouped':'sum'})

# --------------------------------------------------------------------------
# SpecificationError                        Traceback (most recent call last)
# Cell In[117], line 1
# ----> 1 df.groupby('department')['salary'].agg({'salary_grouped':'sum'})

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\groupby\generic.py:464, in SeriesGroupBy.aggregate(self, func, engine, engine_kwargs, *args, **kwargs)
#     462 kwargs["engine"] = engine
#     463 kwargs["engine_kwargs"] = engine_kwargs
# --> 464 ret = self._aggregate_multiple_funcs(func, *args, **kwargs)
#     465 if relabeling:
#     466     # columns is not narrowed by mypy from relabeling flag
#     467     assert columns is not None  # for mypy

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\groupby\generic.py:507, in SeriesGroupBy._aggregate_multiple_funcs(self, arg, *args, **kwargs)
#     505 def _aggregate_multiple_funcs(self, arg, *args, **kwargs) -> DataFrame:
#     506     if isinstance(arg, dict):
# --> 507         raise SpecificationError("nested renamer is not supported")
#     509     if any(isinstance(x, (tuple, list)) for x in arg):
#     510         arg = ((x, x) if not isinstance(x, (tuple, list)) else x for x in arg)

# SpecificationError: nested renamer is not supported

In [236]:
df.groupby('department').agg(salary_grouped=('salary', 'sum'))

             salary_grouped
department
Admin                560500
Engineering          994000
Finance              740000
HR                   764500
Marketing            489000
Sales                572000

In [237]:
dep_emp = df.groupby("department")[['first_name','salary']].agg({'first_name':'count','salary':'mean'  }).reset_index(names = 'department').rename(columns = {'first_name':'emp_count','salary':'avg salary'})
emp_fil = dep_emp[(dep_emp['emp_count']>2)& (dep_emp['avg salary']>75000)]
emp_fil

    department  emp_count    avg salary
1  Engineering         10  99400.000000
2      Finance          9  82222.222222
3           HR         10  76450.000000
4    Marketing          6  81500.000000

In [238]:
emp = df.groupby('department')['first_name'].size().reset_index(name='count')
emp[emp['count']>=5]['department'].iloc[0]

'Admin'

In [239]:
emp = df.groupby('department')['first_name'].size().reset_index(name='count')
emp[emp['count']>=5][['department']]

    department
0        Admin
1  Engineering
2      Finance
3           HR
4    Marketing
5        Sales

# Boolean Conditional Approaches

Groupby approach is a good approach for most of the clustering and analysis. 

But for simple tasks like finding the values based on a single specific column alone, it is slower. 

This is case use the functions on the series produced as a result of conditions we pass 

`(df['column_name']  criteria condition ).function()`

eg. `(df['department']=='HR').sum()` 

this produces the count of HR in a company faster than 
`df.groupby('department')['id'].count()['HR']`

In [240]:
#Find the number of inspections for each risk category by inspection type

str(rest_df.columns)

"Index(['business_name', 'business_address', 'business_city', 'business_state',\n       'business_postal_code', 'business_latitude', 'business_longitude',\n       'business_location', 'business_phone_number', 'inspection_id',\n       'inspection_date', 'inspection_score', 'inspection_type',\n       'violation_id', 'violation_description', 'risk_category'],\n      dtype='str')"

# Replacing the data

We can replace the data of an element by passing the value by accessing the element
1. using `.loc()`
2. using `.replace()`

But there is a small issue 

we cannot use 
1. `iloc()`
2. chain indexing to assign values

## Problem with chain indexing

In [241]:
# df[df['department']=='HR']['department'] = 'hr'
#
# C:\Users\vs85\AppData\Local\Temp\ipykernel_15664\3460383380.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
# Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).
#
# Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.
#
# See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
#   df[df['department']=='HR']['department'] = 'hr'

In [242]:
df.department.unique()

<StringArray>
['HR', 'Admin', 'Engineering', 'Marketing', 'Sales', 'Finance']
Length: 6, dtype: str

## Problem with `.iloc()`

In [243]:
df1 = df.copy(deep=True)

In [244]:
# df[df['department']=='HR']['department'] = 'hr'
df1.iloc[df['department']=='HR']

,first_name,last_name,department,salary,phone_number,joining_date,name_len
id,,,,,,,
1,Sarah,Mitchell,HR,95000,555-0101,15-03-2021,5
2,Michael,Chen,HR,88000,555-0102,01-06-2022,7
3,Emily,Rodriguez,HR,82500,NaN,20-09-2021,5
4,David,Park,HR,80000,555-0104,10-01-2023,5
5,Lisa,Thompson,HR,65000,NaN,05-04-2021,4
6,Robert,Garcia,HR,58000,555-0106,15-11-2022,6
7,Jennifer,Lee,HR,72000,555-0107,20-05-2023,8
8,William,Davis,HR,91000,555-0108,12-08-2019,7
9,Patricia,Wilson,HR,78000,NaN,28-02-2018,8
46,Mark,Diaz,HR,55000,555-0109,15-01-2024,4

In [245]:
df['department'].unique()

<StringArray>
['HR', 'Admin', 'Engineering', 'Marketing', 'Sales', 'Finance']
Length: 6, dtype: str

In [246]:
df1.iloc[df['department']=='HR']

,first_name,last_name,department,salary,phone_number,joining_date,name_len
id,,,,,,,
1,Sarah,Mitchell,HR,95000,555-0101,15-03-2021,5
2,Michael,Chen,HR,88000,555-0102,01-06-2022,7
3,Emily,Rodriguez,HR,82500,NaN,20-09-2021,5
4,David,Park,HR,80000,555-0104,10-01-2023,5
5,Lisa,Thompson,HR,65000,NaN,05-04-2021,4
6,Robert,Garcia,HR,58000,555-0106,15-11-2022,6
7,Jennifer,Lee,HR,72000,555-0107,20-05-2023,8
8,William,Davis,HR,91000,555-0108,12-08-2019,7
9,Patricia,Wilson,HR,78000,NaN,28-02-2018,8
46,Mark,Diaz,HR,55000,555-0109,15-01-2024,4

In [247]:
# df1.iloc[df['department']=='HR'] = 'hr'


# ---------------------------------------------------------------------------
# LossySetitemError                         Traceback (most recent call last)
# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\internals\blocks.py:1115, in Block.setitem(self, indexer, value)
#    1114 try:
# -> 1115     casted = np_can_hold_element(values.dtype, value)
#    1116 except LossySetitemError:
#    1117     # current dtype cannot store value, coerce to common dtype

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\dtypes\cast.py:1750, in np_can_hold_element(dtype, element)
#    1748         return element
# -> 1750     raise LossySetitemError
#    1752 if dtype.kind == "f":

# LossySetitemError: 

# During handling of the above exception, another exception occurred:

# TypeError                                 Traceback (most recent call last)
# Cell In[151], line 1
# ----> 1 df1.iloc[df['department']=='HR'] = 'hr'

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\indexing.py:938, in _LocationIndexer.__setitem__(self, key, value)
#     933 self._has_valid_setitem_indexer(key)
#     935 iloc: _iLocIndexer = (
#     936     cast("_iLocIndexer", self) if self.name == "iloc" else self.obj.iloc
# ...
#     472         f"{self.values.dtype}. Please report a bug at "
#     473         "https://github.com/pandas-dev/pandas/issues."
#     474     )

# TypeError: Invalid value 'hr' for dtype 'int64'

In [248]:
df1['department'].unique()

<StringArray>
['HR', 'Admin', 'Engineering', 'Marketing', 'Sales', 'Finance']
Length: 6, dtype: str

df1

| id | first_name | last_name    | department   | salary | phone_number | joining_date | name_len |
|----|------------|--------------|--------------|--------|--------------|--------------|----------|
| 1  | hr         | hr           | hr           | 95000  | 555-0101     | 15-03-2021   | 5        |
| 2  | hr         | hr           | hr           | 88000  | 555-0102     | 01-06-2022   | 7        |
| 3  | hr         | hr           | hr           | 82500  | NaN          | 20-09-2021   | 5        |
| 4  | hr         | hr           | hr           | 80000  | 555-0104     | 10-01-2023   | 5        |
| 5  | hr         | hr           | hr           | 65000  | NaN          | 05-04-2021   | 4        |
| 6  | hr         | hr           | hr           | 58000  | 555-0106     | 15-11-2022   | 6        |
| 7  | hr         | hr           | hr           | 72000  | 555-0107     | 20-05-2023   | 8        |
| 8  | hr         | hr           | hr           | 91000  | 555-0108     | 12-08-2019   | 7        |
| 9  | hr         | hr           | hr           | 78000  | NaN          | 28-02-2018   | 8        |
| 10 | James      | Martinez     | Admin        | 87000  | 555-0201     | 01-07-2021   | 5        |
| 11 | Amanda     | Taylor       | Admin        | 92000  | NaN          | 15-03-2022   | 6        |
| 12 | Christopher| Anderson     | Admin        | 81500  | 555-0203     | 22-08-2023   | 11       |
| 13 | Michelle   | Thomas       | Admin        | 54000  | 555-0204     | 30-11-2021   | 8        |
| 14 | Daniel     | Jackson      | Admin        | 62000  | 555-0205     | 10-09-2022   | 6        |
| 15 | Jessica    | White        | Admin        | 48000  | NaN          | 14-02-2023   | 7        |
| 16 | Matthew    | Harris       | Admin        | 85000  | 555-0207     | 20-05-2017   | 7        |
| 17 | Kevin      | Brown        | Engineering  | 125000 | 555-0301     | 15-01-2021   | 5        |
| 18 | Angela     | Miller       | Engineering  | 118000 | 555-0302     | 01-04-2022   | 6        |

We can note that all the rows of the department == hr is now assigned with the value hr 

this is wrong. 

Lets try a differnet approach :

In [249]:
df1.iloc[df['department']=='HR']['department']

id
1     HR
2     HR
3     HR
4     HR
5     HR
6     HR
7     HR
8     HR
9     HR
46    HR
Name: department, dtype: str

In [250]:
# df1.iloc[df['department']=='HR']['department'] = 'hr'

# ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
# Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

# Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

# See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
#   df1.iloc[df['department']=='HR']['department'] = 'hr'

In [251]:
# df1.iloc[df['department']=='HR','department'] = 'hr'


# ---------------------------------------------------------------------------
# TypeError                                 Traceback (most recent call last)
# Cell In[176], line 1
# ----> 1 df1.iloc[df['department']=='HR','department'] = 'hr'

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\indexing.py:938, in _LocationIndexer.__setitem__(self, key, value)
#     933 self._has_valid_setitem_indexer(key)
#     935 iloc: _iLocIndexer = (
#     936     cast("_iLocIndexer", self) if self.name == "iloc" else self.obj.iloc
#     937 )
# --> 938 iloc._setitem_with_indexer(indexer, value, self.name)

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\indexing.py:1953, in _iLocIndexer._setitem_with_indexer(self, indexer, value, name)
#    1950 # align and set the values
#    1951 if take_split_path:
#    1952     # We have to operate column-wise
# -> 1953     self._setitem_with_indexer_split_path(indexer, value, name)
#    1954 else:
#    1955     self._setitem_single_block(indexer, value, name)

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\indexing.py:2044, in _iLocIndexer._setitem_with_indexer_split_path(self, indexer, value, name)
#    2041 else:
#    2042     # scalar value
#    2043     for loc in ilocs:
# -> 2044         self._setitem_single_column(loc, value, pi)

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\indexing.py:2170, in _iLocIndexer._setitem_single_column(self, loc, value, plane_indexer)
#    2166         self.obj.isetitem(loc, value)
#    2167 else:
#    2168     # set value into the column (first attempting to operate inplace, then
#    2169     #  falling back to casting if necessary)
# -> 2170     dtype = self.obj.dtypes.iloc[loc]
#    2171     if dtype == np.void:
#    2172         # This means we're expanding, with multiple columns, e.g.
#    2173         #     df = pd.DataFrame({'A': [1,2,3], 'B': [4,5,6]})
#    (...)   2176         # Here, we replace those temporary `np.void` columns with
#    2177         # columns of the appropriate dtype, based on `value`.
#    2178         self.obj.iloc[:, loc] = construct_1d_array_from_inferred_fill_value(
#    2179             value, len(self.obj)
#    2180         )

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\indexing.py:1207, in _LocationIndexer.__getitem__(self, key)
#    1205 maybe_callable = com.apply_if_callable(key, self.obj)
#    1206 maybe_callable = self._raise_callable_usage(key, maybe_callable)
# -> 1207 return self._getitem_axis(maybe_callable, axis=axis)

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\indexing.py:1770, in _iLocIndexer._getitem_axis(self, key, axis)
#    1768 key = item_from_zerodim(key)
#    1769 if not is_integer(key):
# -> 1770     raise TypeError("Cannot index by location index with a non-integer key")
#    1772 # validate the location
#    1773 self._validate_integer(key, axis)

# TypeError: Cannot index by location index with a non-integer key

In [252]:
df1.iloc[df1['department'] == 'HR',2]

id
1     HR
2     HR
3     HR
4     HR
5     HR
6     HR
7     HR
8     HR
9     HR
46    HR
Name: department, dtype: str

## The `.iloc()` correct way

In [253]:
df1.iloc[df1['department'] == 'HR',2] = 'hr'
df1.head(10)

,first_name,last_name,department,salary,phone_number,joining_date,name_len
id,,,,,,,
1,Sarah,Mitchell,hr,95000,555-0101,15-03-2021,5
2,Michael,Chen,hr,88000,555-0102,01-06-2022,7
3,Emily,Rodriguez,hr,82500,NaN,20-09-2021,5
4,David,Park,hr,80000,555-0104,10-01-2023,5
5,Lisa,Thompson,hr,65000,NaN,05-04-2021,4
6,Robert,Garcia,hr,58000,555-0106,15-11-2022,6
7,Jennifer,Lee,hr,72000,555-0107,20-05-2023,8
8,William,Davis,hr,91000,555-0108,12-08-2019,7
9,Patricia,Wilson,hr,78000,NaN,28-02-2018,8
10,James,Martinez,Admin,87000,555-0201,01-07-2021,5

In [254]:
df1.iloc[df1['department'] == 'hr',2] = 'HR'
df1.head(10)

,first_name,last_name,department,salary,phone_number,joining_date,name_len
id,,,,,,,
1,Sarah,Mitchell,HR,95000,555-0101,15-03-2021,5
2,Michael,Chen,HR,88000,555-0102,01-06-2022,7
3,Emily,Rodriguez,HR,82500,NaN,20-09-2021,5
4,David,Park,HR,80000,555-0104,10-01-2023,5
5,Lisa,Thompson,HR,65000,NaN,05-04-2021,4
6,Robert,Garcia,HR,58000,555-0106,15-11-2022,6
7,Jennifer,Lee,HR,72000,555-0107,20-05-2023,8
8,William,Davis,HR,91000,555-0108,12-08-2019,7
9,Patricia,Wilson,HR,78000,NaN,28-02-2018,8
10,James,Martinez,Admin,87000,555-0201,01-07-2021,5

## The correct way `.loc()`

In [255]:
df1.loc[df1['department'] == 'HR']['department']

id
1     HR
2     HR
3     HR
4     HR
5     HR
6     HR
7     HR
8     HR
9     HR
46    HR
Name: department, dtype: str

In [256]:
df1.loc[df1['department'] == 'HR', 'department'] = 'hr'
df1.head(10)

,first_name,last_name,department,salary,phone_number,joining_date,name_len
id,,,,,,,
1,Sarah,Mitchell,hr,95000,555-0101,15-03-2021,5
2,Michael,Chen,hr,88000,555-0102,01-06-2022,7
3,Emily,Rodriguez,hr,82500,NaN,20-09-2021,5
4,David,Park,hr,80000,555-0104,10-01-2023,5
5,Lisa,Thompson,hr,65000,NaN,05-04-2021,4
6,Robert,Garcia,hr,58000,555-0106,15-11-2022,6
7,Jennifer,Lee,hr,72000,555-0107,20-05-2023,8
8,William,Davis,hr,91000,555-0108,12-08-2019,7
9,Patricia,Wilson,hr,78000,NaN,28-02-2018,8
10,James,Martinez,Admin,87000,555-0201,01-07-2021,5

In [257]:
df1.loc[df1['department'] == 'hr', 'department'] = 'HR'
df1.head(10)

,first_name,last_name,department,salary,phone_number,joining_date,name_len
id,,,,,,,
1,Sarah,Mitchell,HR,95000,555-0101,15-03-2021,5
2,Michael,Chen,HR,88000,555-0102,01-06-2022,7
3,Emily,Rodriguez,HR,82500,NaN,20-09-2021,5
4,David,Park,HR,80000,555-0104,10-01-2023,5
5,Lisa,Thompson,HR,65000,NaN,05-04-2021,4
6,Robert,Garcia,HR,58000,555-0106,15-11-2022,6
7,Jennifer,Lee,HR,72000,555-0107,20-05-2023,8
8,William,Davis,HR,91000,555-0108,12-08-2019,7
9,Patricia,Wilson,HR,78000,NaN,28-02-2018,8
10,James,Martinez,Admin,87000,555-0201,01-07-2021,5

## The `.replace()` approach 

we can chain the corresponding column and then assign the value using the `.replace()` by passing the current value and the new value as a key value pair. 

`df[df[column] condition criteria][column_name].replace({old_value : new_value})`

In [258]:
df1['department'] = df1['department'].replace({'HR': 'hr'})
df1.head(10)

,first_name,last_name,department,salary,phone_number,joining_date,name_len
id,,,,,,,
1,Sarah,Mitchell,hr,95000,555-0101,15-03-2021,5
2,Michael,Chen,hr,88000,555-0102,01-06-2022,7
3,Emily,Rodriguez,hr,82500,NaN,20-09-2021,5
4,David,Park,hr,80000,555-0104,10-01-2023,5
5,Lisa,Thompson,hr,65000,NaN,05-04-2021,4
6,Robert,Garcia,hr,58000,555-0106,15-11-2022,6
7,Jennifer,Lee,hr,72000,555-0107,20-05-2023,8
8,William,Davis,hr,91000,555-0108,12-08-2019,7
9,Patricia,Wilson,hr,78000,NaN,28-02-2018,8
10,James,Martinez,Admin,87000,555-0201,01-07-2021,5

In [259]:
df1['department'] = df1['department'].replace({'hr': 'HR'})
df1.head(10)

,first_name,last_name,department,salary,phone_number,joining_date,name_len
id,,,,,,,
1,Sarah,Mitchell,HR,95000,555-0101,15-03-2021,5
2,Michael,Chen,HR,88000,555-0102,01-06-2022,7
3,Emily,Rodriguez,HR,82500,NaN,20-09-2021,5
4,David,Park,HR,80000,555-0104,10-01-2023,5
5,Lisa,Thompson,HR,65000,NaN,05-04-2021,4
6,Robert,Garcia,HR,58000,555-0106,15-11-2022,6
7,Jennifer,Lee,HR,72000,555-0107,20-05-2023,8
8,William,Davis,HR,91000,555-0108,12-08-2019,7
9,Patricia,Wilson,HR,78000,NaN,28-02-2018,8
10,James,Martinez,Admin,87000,555-0201,01-07-2021,5

# merge, join and concatenate

Merge and join functions allow you to combine multiple datasets by aligning rows based on common columns or indices.

The concat function allows you to concatenate datasets along a specified axis, either rows or columns.

## Merge

merge is used for combining data on common columns or indices

This is a model function and is not used as a dot function on a dataframe   

Used when we match rows with multiple columns in common. 

This is used when there are 2 dataframes and both have one common column, when we merge the dataframes, both the dataframes are combined like side-by-side, i.e. no. of column increases 

This is performed based on the comparison with the common column. 

Now when the merge is happening, there are potential cases (based on the type of merge) the data(row) can be lost.

When the common column from df1 has 4 rows and column column in df2 has 3 rows there is one row index that is not between them and there are chances that this row from df1 gets deleted

In [260]:

df_customers = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Vignesh", "Ravi", "Kumar"]
})

df_orders = pd.DataFrame({
    "ID": [1, 2],
    "Order": ["Laptop", "Phone"]
})

df_age = pd.DataFrame({
    "Age": [25, 30, 35]
}, index=[1, 2, 3])

df_price = pd.DataFrame({
    "ID": [1, 2, 1],
    "Order": ["Laptop", "Phone", "Tablet"],
    "Price": [50000, 20000, 15000]
})

In [261]:
df_age

   Age
1   25
2   30
3   35

In [262]:
df_customers

   ID     Name
0   1  Vignesh
1   2     Ravi
2   3    Kumar

In [263]:
df_orders

   ID   Order
0   1  Laptop
1   2   Phone

In [264]:
df_price

   ID   Order  Price
0   1  Laptop  50000
1   2   Phone  20000
2   1  Tablet  15000

Important rule to understand:- 
1. Merge works on 2 df at a time
2. Pandas automatically looks at both DataFrames and finds any columns that share the exact same name. If it finds a shared column name, it implicitly uses that column as the merge key

In [265]:
# pd.merge(df_customers,df_orders,df_age)

# ---------------------------------------------------------------------------
# ValueError                                Traceback (most recent call last)
# Cell In[208], line 1
# ----> 1 pd.merge(df_customers,df_orders,df_age)

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\reshape\merge.py:370, in merge(left, right, how, on, left_on, right_on, left_index, right_index, sort, suffixes, copy, indicator, validate)
#     368 left._check_copy_deprecation(copy)
#     369 right_df = _validate_operand(right)
# --> 370 if how == "cross":
#     371     return _cross_merge(
#     372         left_df,
#     373         right_df,
#    (...)    382         validate=validate,
#     383     )
#     384 else:

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\generic.py:1513, in NDFrame.__bool__(self)
#    1511     @final
#    1512     def __bool__(self) -> NoReturn:
# -> 1513         raise ValueError(
#    1514             f"The truth value of a {type(self).__name__} is ambiguous. "
#    1515             "Use a.empty, a.bool(), a.item(), a.any() or a.all()."
#    1516         )

# ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

We can note that the 3rd row of customers df is lost and the merge is based on the column id

In [266]:
temp = pd.merge(df_customers,df_orders)
temp

   ID     Name   Order
0   1  Vignesh  Laptop
1   2     Ravi   Phone

We get a merge error because there is no common column name in  both the dataframes i.e. df_age has no column with name id

In [267]:
# pd.merge(temp,df_age)

# ---------------------------------------------------------------------------
# MergeError                                Traceback (most recent call last)
# Cell In[212], line 1
# ----> 1 pd.merge(temp,df_age)

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\reshape\merge.py:385, in merge(left, right, how, on, left_on, right_on, left_index, right_index, sort, suffixes, copy, indicator, validate)
#     371     return _cross_merge(
#     372         left_df,
#     373         right_df,
#    (...)    382         validate=validate,
#     383     )
#     384 else:
# --> 385     op = _MergeOperation(
#     386         left_df,
#     387         right_df,
#     388         how=how,
#     389         on=on,
#     390         left_on=left_on,
#     391         right_on=right_on,
#     392         left_index=left_index,
#     393         right_index=right_index,
#     394         sort=sort,
#     395         suffixes=suffixes,
#     396         indicator=indicator,
#     397         validate=validate,
#     398     )
#     399     return op.get_result()

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\reshape\merge.py:1010, in _MergeOperation.__init__(self, left, right, how, on, left_on, right_on, left_index, right_index, sort, suffixes, indicator, validate)
#    1003     msg = (
#    1004         "Not allowed to merge between different levels. "
#    1005         f"({_left.columns.nlevels} levels on the left, "
#    1006         f"{_right.columns.nlevels} on the right)"
#    1007     )
#    1008     raise MergeError(msg)
# -> 1010 self.left_on, self.right_on = self._validate_left_right_on(left_on, right_on)
#    1012 (
#    1013     self.left_join_keys,
#    1014     self.right_join_keys,
#    (...)   1017     right_drop,
#    1018 ) = self._get_merge_keys()
#    1020 if left_drop:

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\reshape\merge.py:1899, in _MergeOperation._validate_left_right_on(self, left_on, right_on)
#    1897 common_cols = left_cols.intersection(right_cols)
#    1898 if len(common_cols) == 0:
# -> 1899     raise MergeError(
#    1900         "No common columns to perform merge on. "
#    1901         f"Merge options: left_on={left_on}, "
#    1902         f"right_on={right_on}, "
#    1903         f"left_index={self.left_index}, "
#    1904         f"right_index={self.right_index}"
#    1905     )
#    1906 if (
#    1907     not left_cols.join(common_cols, how="inner").is_unique
#    1908     or not right_cols.join(common_cols, how="inner").is_unique
#    1909 ):
#    1910     raise MergeError(f"Data columns not unique: {common_cols!r}")

# MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

There are 2 types of merging 
1. single column merge <- if a single column matches between 2 df 
2. multi column merge <- when more than 1 column matches between df

Single column merge is the above example 

Multi-column merge is given below

In [268]:
df_price

   ID   Order  Price
0   1  Laptop  50000
1   2   Phone  20000
2   1  Tablet  15000

In [269]:
pd.merge(temp,df_price)

   ID     Name   Order  Price
0   1  Vignesh  Laptop  50000
1   2     Ravi   Phone  20000

In [270]:
pd.merge(temp,df_price, on=['ID','Order'])

   ID     Name   Order  Price
0   1  Vignesh  Laptop  50000
1   2     Ravi   Phone  20000

We could note that the Tablet value of the row is not added in the price :- reason it matches both ID and Order and there is no Order with Tablet. 

There are 2 important keyword args we need to understand 

1. `on` <- it takes a single or list of column names on which the merging has to be performed.
    - pandas can internally analyse whether it needs to go with single column or multi column sort based on the column labels 
2. `how` <- it decides which rows should be kept after merging

| how value | Meaning |
|----------|--------|
| inner | Keep only matching rows |
| left  | Keep all rows from left table |
| right | Keep all rows from right table |
| outer | Keep everything from both |

by default `how` is assigned with `inner`

In [271]:
pd.merge(temp,df_price, on=['ID','Order'],how='inner')

   ID     Name   Order  Price
0   1  Vignesh  Laptop  50000
1   2     Ravi   Phone  20000

`outer` keeps the all the values from both the tables

In [272]:
pd.merge(temp,df_price, on=['ID','Order'],how='outer')

   ID     Name   Order  Price
0   1  Vignesh  Laptop  50000
1   1      NaN  Tablet  15000
2   2     Ravi   Phone  20000

`left` keeps data from the left side merge

In [273]:
pd.merge(temp,df_price, on=['ID','Order'],how='left')

   ID     Name   Order  Price
0   1  Vignesh  Laptop  50000
1   2     Ravi   Phone  20000

In [274]:
pd.merge(df_price,temp, on=['ID','Order'], how='left')

   ID   Order  Price     Name
0   1  Laptop  50000  Vignesh
1   2   Phone  20000     Ravi
2   1  Tablet  15000      NaN

`right` keeps data from the right side merge

In [275]:
pd.merge(temp,df_price, on=['ID','Order'],how='right')

   ID     Name   Order  Price
0   1  Vignesh  Laptop  50000
1   2     Ravi   Phone  20000
2   1      NaN  Tablet  15000

In [276]:
pd.merge(df_price,temp, on=['ID','Order'], how='right')

   ID   Order  Price     Name
0   1  Laptop  50000  Vignesh
1   2   Phone  20000     Ravi


We can note the differnce between `outer` and `left` or `right`

`outer` make sure both the table contributes to the matching so id matched tablets got pushed up as ID matched

`left` or `right` doesn't do that, merge preserves left/right dataframe order

## Join 

Join function is used for combining data on a key column or an index. 

Join is an instance method, which means it can be called on a DataFrame using a dot syntax

By default it implements left join

better than merge

df_customers.set_index("ID").join(df_age)

# Concatenation of Dataframes

We can combine 2 dataframes in of same column names and column counts one after the another in the verticle manner using `.concat()` on **pandas**

`pd.concat([df1,df2])`



pd.concat([df_customers, df_customers])
pd.concat([df_customers, df_orders], axis=1)

In [277]:
orders_df.loc[0]

id                           1
cust_id                      3
order_date          04-03-2019
order_details             Coat
total_order_cost           100
Name: 0, dtype: object

In [278]:
odf = orders_df.to_dict()
odf.keys()

dict_keys(['id', 'cust_id', 'order_date', 'order_details', 'total_order_cost'])

In [279]:
odf['cust_id']

{0: 3,
 1: 3,
 2: 3,
 3: 7,
 4: 7,
 5: 15,
 6: 15,
 7: 15,
 8: 15,
 9: 15,
 10: 5,
 11: 12,
 12: 12,
 13: 4,
 14: 4,
 15: 3,
 16: 7,
 17: 15,
 18: 15,
 19: 12,
 20: 7,
 21: 7,
 22: 7,
 23: 7,
 24: 7,
 25: 3,
 26: 3,
 27: 3,
 28: 3,
 29: 1,
 30: 1}

In [280]:
# odf['cust_id'][0] = 9
# odf['order_details'][0]='Slipper'
# odf['total_order_cost'][0] = 23
for col, val in [('cust_id', 9), ('order_details', 'Slipper'), ('total_order_cost', 23)]: odf[col][0] = val
odf= pd.DataFrame(odf)

In [281]:
odf.head()

   id  cust_id  order_date order_details  total_order_cost
0   1        9  04-03-2019       Slipper                23
1   2        3  01-03-2019         Shoes                80
2   3        3  07-03-2019         Skirt                30
3   4        7  01-02-2019          Coat                25
4   5        7  10-03-2019         Shoes                80

In [282]:
orders_df.head()

   id  cust_id  order_date order_details  total_order_cost
0   1        3  04-03-2019          Coat               100
1   2        3  01-03-2019         Shoes                80
2   3        3  07-03-2019         Skirt                30
3   4        7  01-02-2019          Coat                25
4   5        7  10-03-2019         Shoes                80

In [283]:
con_df = pd.concat([orders_df,odf])
print(con_df.to_string())

    id  cust_id  order_date order_details  total_order_cost
0    1        3  04-03-2019          Coat               100
1    2        3  01-03-2019         Shoes                80
2    3        3  07-03-2019         Skirt                30
3    4        7  01-02-2019          Coat                25
4    5        7  10-03-2019         Shoes                80
5    6       15  01-02-2019         Boats               100
6    7       15  11-01-2019        Shirts                60
7    8       15  11-03-2019       Slipper                20
8    9       15  01-03-2019         Jeans                80
9   10       15  09-03-2019        Shirts                50
10  11        5  01-02-2019         Shoes                80
11  12       12  11-01-2019        Shirts                60
12  13       12  11-03-2019       Slipper                20
13  14        4  01-02-2019         Shoes                80
14  15        4  11-01-2019        Shirts                60
15  16        3  19-04-2019        Shirts                50
16  17        7  19-04-2019          Suit               150
17  18       15  19-04-2019         Skirt                30
18  19       15  20-04-2019       Dresses               200
19  20       12  11-01-2019          Coat               125
20  21        7  01-04-2019          Suit                50
21  22        7  02-04-2019         Skirt                30
22  23        7  03-04-2019       Dresses                50
23  24        7  04-04-2019          Coat                25
24  25        7  19-04-2019          Coat               125
25  26        3  20-04-2019        Gloves                20
26  27        3  21-04-2019           Tie                25
27  28        3  22-04-2019           Cap                15
28  29        3  23-04-2019        Jacket               120
29  30        1  19-04-2019        Jacket               150
30  31        1  19-04-2019         Shoes               125
0    1        9  04-03-2019       Slipper                23
1    2        3  01-03-2019         Shoes                80
2    3        3  07-03-2019         Skirt                30
3    4        7  01-02-2019          Coat                25
4    5        7  10-03-2019         Shoes                80
5    6       15  01-02-2019         Boats               100
6    7       15  11-01-2019        Shirts                60
7    8       15  11-03-2019       Slipper                20
8    9       15  01-03-2019         Jeans                80
9   10       15  09-03-2019        Shirts                50
10  11        5  01-02-2019         Shoes                80
11  12       12  11-01-2019        Shirts                60
12  13       12  11-03-2019       Slipper                20
13  14        4  01-02-2019         Shoes                80
14  15        4  11-01-2019        Shirts                60
15  16        3  19-04-2019        Shirts                50
16  17        7  19-04-2019          Suit               150
17  18       15  19-04-2019         Skirt                30
18  19       15  20-04-2019       Dresses               200
19  20       12  11-01-2019          Coat               125
20  21        7  01-04-2019          Suit                50
21  22        7  02-04-2019         Skirt                30
22  23        7  03-04-2019       Dresses                50
23  24        7  04-04-2019          Coat                25
24  25        7  19-04-2019          Coat               125
25  26        3  20-04-2019        Gloves                20
26  27        3  21-04-2019           Tie                25
27  28        3  22-04-2019           Cap                15
28  29        3  23-04-2019        Jacket               120
29  30        1  19-04-2019        Jacket               150
30  31        1  19-04-2019         Shoes               125

We can note that the data is having the same default index i.e. after concatenation the dataframe2 also starts with 0

This is not good if we use loc

In [284]:
con_df.loc[0]

   id  cust_id  order_date order_details  total_order_cost
0   1        3  04-03-2019          Coat               100
0   1        9  04-03-2019       Slipper                23

To avoid this we use `.reset_index(drop=True)`

In [285]:
con_df.reset_index(drop=True,inplace=True)
con_df.loc[0]

id                           1
cust_id                      3
order_date          04-03-2019
order_details             Coat
total_order_cost           100
Name: 0, dtype: object

# Date-Time Format

There can be cases where we'll have a column with date and time as values.

To handle these columns when imported it will be usually of type obj meaning they are string

It is important to convert such columns into date and time format using 

`df['column_name'] = pd.to_datetime(df['column_name'])`

In [286]:
odf.info()

<class 'pandas.DataFrame'>
Index: 31 entries, 0 to 30
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                31 non-null     int64
 1   cust_id           31 non-null     int64
 2   order_date        31 non-null     str
 3   order_details     31 non-null     str
 4   total_order_cost  31 non-null     int64
dtypes: int64(3), str(2)
memory usage: 1.5 KB

In [287]:
# this is of type str

odf['order_date'].head()

0    04-03-2019
1    01-03-2019
2    07-03-2019
3    01-02-2019
4    10-03-2019
Name: order_date, dtype: str

Directly using this on pandas will cause an issue, because the default pandas format for date and time is **YYYY-MM-DD HH:MM:SS**

Since our data is of type DD-MM-YYY it will throw error

In [288]:
# odf.order_date = pd.to_datetime(odf.order_date)
# odf.info()


# ---------------------------------------------------------------------------
# ValueError                                Traceback (most recent call last)
# Cell In[185], line 1
# ----> 1 odf.order_date = pd.to_datetime(odf.order_date)
#       2 odf.info()

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\tools\datetimes.py:1040, in to_datetime(arg, errors, dayfirst, yearfirst, utc, format, exact, unit, origin, cache)
#    1038         result = arg.map(cache_array)
#    1039     else:
# -> 1040         values = convert_listlike(arg._values, format)
#    1041         result = arg._constructor(values, index=arg.index, name=arg.name)
#    1042 elif isinstance(arg, (ABCDataFrame, abc.MutableMapping)):

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\tools\datetimes.py:435, in _convert_listlike_datetimes(arg, format, name, utc, unit, errors, dayfirst, yearfirst, exact)
#     433 # `format` could be inferred, or user didn't ask for mixed-format parsing.
#     434 if format is not None and format != "mixed":
# --> 435     return _array_strptime_with_fallback(arg, name, utc, format, exact, errors)
#     437 result, tz_parsed = objects_to_datetime64(
#     438     arg,
#     439     dayfirst=dayfirst,
#    (...)    443     allow_object=True,
#     444 )
#     446 if tz_parsed is not None:
#     447     # We can take a shortcut since the datetime64 numpy array
#     448     # is in UTC

# File ~\AppData\Roaming\Python\Python313\site-packages\pandas\core\tools\datetimes.py:470, in _array_strptime_with_fallback(arg, name, utc, fmt, exact, errors)
#     459 def _array_strptime_with_fallback(
#     460     arg,
#     461     name,
#    (...)    465     errors: str,
#     466 ) -> Index:
#     467     """
#     468     Call array_strptime, with fallback behavior depending on 'errors'.
#     469     """
# --> 470     result, tz_out = array_strptime(arg, fmt, exact=exact, errors=errors, utc=utc)
#     471     if tz_out is not None:
#     472         unit = np.datetime_data(result.dtype)[0]

# File pandas/_libs/tslibs/strptime.pyx:563, in pandas._libs.tslibs.strptime.array_strptime()
# --> 563 'Could not get source, probably due dynamically evaluated source code.'

# File pandas/_libs/tslibs/strptime.pyx:511, in pandas._libs.tslibs.strptime.array_strptime()
# --> 511 'Could not get source, probably due dynamically evaluated source code.'

# File pandas/_libs/tslibs/strptime.pyx:617, in pandas._libs.tslibs.strptime._parse_with_format()
# --> 617 'Could not get source, probably due dynamically evaluated source code.'

# ValueError: time data "19-04-2019" doesn't match format "%m-%d-%Y". You might want to try:
#     - passing `format` if your strings have a consistent format;
#     - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
#     - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

To handle this we have 2 approaches 
1. internal attribute to denote date is the first element <- `dayfirst = True`
2. custom format of date time <- `format='%d-%m-%Y'`

additionaly we can use `errors='coerce'` to eliminate the error date entries and mark them as `NaT`

In [289]:
odf.order_date = pd.to_datetime(odf.order_date,format='%d-%m-%Y')
odf.info()

<class 'pandas.DataFrame'>
Index: 31 entries, 0 to 30
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                31 non-null     int64
 1   cust_id           31 non-null     int64
 2   order_date        31 non-null     datetime64[us]
 3   order_details     31 non-null     str
 4   total_order_cost  31 non-null     int64
dtypes: datetime64[us](1), int64(3), str(1)
memory usage: 1.5 KB

In [290]:
odf.order_date.head()

0   2019-03-04
1   2019-03-01
2   2019-03-07
3   2019-02-01
4   2019-03-10
Name: order_date, dtype: datetime64[us]

## Exctracting date-month-year

Once we convert the format it is easier to extract the date-month-year from the single column 

```df['year'] = df['date_time_column_name'].dt.year
df['month'] = df['date_time_column_name'].dt.month   #gets the month number
df['monthName'] = df['date_time_column_name'].dt.month_name()  # gets the name of the month
df['Date'] = df['date_time_column_name'].dt.date  
df['day of the week'] = df['date_time_column_name'].dt.dayofweek    # what is the day number in the 7 days of a week
df['week'] = df['date_time_column_name'].dt.week   # week in the year
```

In [291]:
odf['order_year'] = odf.order_date.dt.year
odf['order_month'] = odf.order_date.dt.month
odf['order_monthName'] = odf.order_date.dt.month_name()
odf['order_Date'] = odf.order_date.dt.date
odf.head()

,id,cust_id,order_date,order_details,total_order_cost,order_year,order_month,order_monthName,order_Date
0,1,9,2019-03-04,Slipper,23,2019,3,March,2019-03-04
1,2,3,2019-03-01,Shoes,80,2019,3,March,2019-03-01
2,3,3,2019-03-07,Skirt,30,2019,3,March,2019-03-07
3,4,7,2019-02-01,Coat,25,2019,2,February,2019-02-01
4,5,7,2019-03-10,Shoes,80,2019,3,March,2019-03-10

#  Function vs Output Type


##  1. Selection / Access

| Function | Operates On | Returns | Description |
|--------|------------|--------|-------------|
| `df['col']` | DataFrame | Series | Select one column |
| `df[['col1','col2']]` | DataFrame | DataFrame | Select multiple columns |
| `df.loc[]` | DataFrame | Series/DataFrame | Label-based selection |
| `df.iloc[]` | DataFrame | Series/DataFrame | Position-based selection |

## 2. Basic Info & Structure

| Function | Returns | Description |
|--------|--------|-------------|
| `df.head()` | DataFrame | First 5 rows |
| `df.tail()` | DataFrame | Last 5 rows |
| `df.info()` | None | Summary (prints only) |
| `df.describe()` | DataFrame | Stats summary |
| `df.shape` | tuple | (rows, cols) |
| `df.columns` | Index | Column names |
| `df.index` | Index | Row index |

## 3. Aggregations

| Function | Returns | Notes |
|--------|--------|------|
| `df.sum()` | Series | Column-wise sum |
| `df.mean()` | Series | Column-wise mean |
| `df.count()` | Series | Non-null count |
| `df.min()` / `df.max()` | Series | Min / Max |
| `df.agg()` | Series/DataFrame | Depends on input |

### `.agg()`

| Columns | Functions | Output |
|--------|----------|--------|
| 1 | 1 | scalar |
| 1 | many | Series |
| many | 1 | Series |
| many | many | DataFrame |

## 4. Column-Level (Series operations via DF)

| Function | Returns | Notes |
|--------|--------|------|
| `df['col'].sum()` | scalar | Single value |
| `df['col'].unique()` | ndarray | Unique values |
| `df['col'].nunique()` | scalar | Count |
| `df['col'].value_counts()` | Series | Frequency |

## 5. Missing Values

| Function | Returns |
|--------|--------|
| `df.dropna()` | DataFrame |
| `df.fillna()` | DataFrame |
| `df.isna()` | DataFrame (bool) |
| `df.notna()` | DataFrame (bool) |

##  6. Grouping

| Function | Returns |
|--------|--------|
| `df.groupby()` | GroupBy object |
| `grouped.sum()` | DataFrame/Series |
| `grouped['col'].sum()` | Series |
| `grouped.agg()` | DataFrame/Series |

`.sum()` is just one method, all the other methods like `.count()`,`.mean()`, etc. behave similarly  

| Operation | Column Selection | Functions | Output |
|----------|----------------|----------|--------|
| `grouped.sum()` | 1 column | 1 | Series |
| `grouped.sum()` | many columns | 1 | DataFrame |
| `grouped.agg()` | 1 column | 1 | Series |
| `grouped.agg()` | 1 column | many | DataFrame |
| `grouped.agg()` | many columns | any | DataFrame |



`grouped = df.groupby('column_name')`

## 7. Sorting

| Function | Returns |
|--------|--------|
| `df.sort_values()` | DataFrame |
| `df.sort_index()` | DataFrame |

## 8. Index Operations

| Function | Returns |
|--------|--------|
| `df.set_index()` | DataFrame |
| `df.reset_index()` | DataFrame |

##  9. Duplicates

| Function | Returns |
|--------|--------|
| `df.drop_duplicates()` | DataFrame |
| `df.duplicated()` | Series (bool) |

## 10. Transformations

| Function | Returns |
|--------|--------|
| `df.apply()` | Series/DataFrame |
| `df.map()` | Series |
| `df.applymap()` | DataFrame |

## 11. Merge / Combine

| Function | Returns |
|--------|--------|
| `pd.merge()` | DataFrame |
| `df.join()` | DataFrame |
| `pd.concat()` | DataFrame |

##  12. Boolean Filtering

| Expression | Returns |
|-----------|--------|
| `df[condition]` | DataFrame |
| `df['col'] > 10` | Series (bool) |

## Master map

### Step 1: Selecting?
- `df['col']` → Series  
- `df[['col1','col2']]` → DataFrame  

### Step 2: Aggregating?
- Yes:
  - 1 value → scalar  
  - Multiple columns → Series  
  - Multiple functions → DataFrame  

### Step 3: Groupby?
- Yes:
  - 1 value per group → Series  
  - Multiple values per group → DataFrame